var h;
if(!window.__idm_init__&&navigator.platform.startsWith("Win")&&document.documentElement.localName=="html"){window.__idm_init__=!0;typeof browser=="undefined"&&(browser=chrome);navigator.userAgent.includes("Edg/");navigator.userAgent.includes("OPR/");navigator.userAgent.includes("YaBrowser/");const W=Object.values,N=Array.from,O=Array.prototype.includes,J=Math.random,X=Function.call.bind(Array.prototype.slice),P=Function.apply.bind(Array.prototype.push),H=Function.call.bind(Array.prototype.forEach),Y=
Function.apply.bind(String.fromCharCode,null),Z=Function.call.bind(String.prototype.charCodeAt),aa=String.fromCharCode,ba=["date","content-type","content-length"];function ca(a,b){return fetch(a,b).catch(()=>null)}function da(a,b){b&&(a[b]=!0);return a}function B(a){return a.replace(/[a-z]/gi,function(b){return aa((b=Z(b))+((b&31)>13?-13:13))})}const ea={16:!0,17:!0,18:!0,45:!0,46:!0},K=O.bind(["video","audio","object","embed"]),C=RegExp("(?!)"),fa=RegExp(" *\\$([<>{}|&*+=@!#%:?^~-])(\\d*) *"),ha=
RegExp.prototype.test.bind(/^rgba?\(\d+,\s*\d+,\s*\d+,\s*0\)/),ia=globalThis,I=window.self===window.top;var x=window.origin||document.origin||location.origin,D=location,L=location.hostname.toLowerCase()+location.pathname+location.search,Q;function R(){browser.runtime.getFrameId?this.ma=browser.runtime.getFrameId(window):I&&(this.ma=0);this.Ja=[];this.na=[];this.Y=[];this.v={};this.kb();window.__idm_connect__=this.kb.bind(this,!0);this.i(1,window,"resize",this.Dc);this.i(1,window,"scroll",this.Ec);
this.i(1,window,"blur",this.vc);this.i(1,window,"keydown",this.tb,!0);this.i(1,window,"keyup",this.tb,!0);this.i(1,window,"mousedown",this.xc,!0);this.i(1,window,"mouseup",this.zc,!0);this.i(1,window,"mousemove",this.yc,!0);this.i(1,window,"click",this.wc,!0);this.i(1,document,"beforeload",this.tc,!0);this.i(1,document,"DOMContentLoaded",this.sb);document.readyState!="interactive"&&document.readyState!="complete"||this.sb()}h=R.prototype;h.Ka="idmrs:///";h.xa=C;h.u=0;h.B=0;h.oa=-1;h.pa=-1;h.zb=1;
h.o="";h.$=0;h.l="";h.ca="";h.L="";h.qa="";h.Wa=C;h.cb=RegExp(B('\\olgpst\\.frg\\(\\{(?=.*?"RKCREVZRAG_SYNTF":)(?=.*?"FGF":(\\q{5,})\\o|)(?=.*?"QNGNFLAP_VQ":"(.+?)"|)(?=.*?"YBTTRQ_VA":(\\j+)\\o|)(?=.*?"RBZ_IVFVGBE_QNGN":"(.+?)"|)(?=.*?"IVFVGBE_QNGN":"(.+?)"|)(?=.*?"CYNLRE_WF_HEY":"(.+?)"|)(?=.*?"FRFFVBA_VAQRK":"(\\q)"|)'),"s");h.M=C;h.fb=C;h.Xa=C;h.I={};h.Ya="(?!)";h.Za="(?!)";h.$a=B('\\oshapgvba\\((\\j+)\\)\\{ine\\f+(\\j+)=[^?;,]*?(?:\\.fcyvg\\.\\j+\\(\\1,|\\1\\.fcyvg\\()(?:.+?\\ovs\\f*\\(glcrbs\\f+([\\j$]+)===?(([\\j$]+)[^()]+|"haqrsvarq")\\)\\f*erghea\\o)?.+?\\{erghea\\f+(?:([\\j$]+)\\[\\q+\\]|[^();,]+?)\\+\\f*\\1\\}\\f*erghea\\o[^{};]+?(?:\\.wbva\\.\\j+\\(\\2,|\\2\\.wbva\\o)[^{};]+?\\}');
h.ab=B("(?<=\\oine\\f+)${3.3}=.+?(?=[;,}])");h.bb=B("(?<=\\oine\\f+)${3.5}=(([\"']).*?\\2\\.fcyvg\\(([\"']).\\3\\)|\\[(?:(?:\".*?\"|'.*?')(?:,\\f*|(?=\\])))+\\])(?=[;,])");h.eb=B('$> *[ebyr="znva"]:abg(uvqqra) ivqrb, :fpbcr >qvi#cynlre ivqrb, lgzhfvp-cynlre ivqrb');h.gb=B("$> lgzhfvp-cynlre qvi#fbat-vzntr vzt");h.Va=B("$<< $> :fpbcr >ivqrb +qvi >pnainf");h.hb=B("$= lg.pbasvt_.RBZ_IVFVGBE_QNGN $= lgpst.qngn_.RBZ_IVFVGBE_QNGN $= lg.pbasvt_.IVFVGBE_QNGN $= lgpst.qngn_.IVFVGBE_QNGN");h.wa=C;h.ua=B('$< qvi#jngpu_srrq qvi.k1a6lekg:svefg-puvyq:abg(:bayl-puvyq), qvi.k10pvuf4 qvi[ebyr="znva"]:svefg-puvyq:unf(+qvi[ebyr="pbzcyrzragnel"])');
h.va="$= poster";h.ra=":root:empty";h.ta=0;h.sa=C;h.Ba=C;h.Da='$& div.xxzkxad $& :scope >div[class] $& section main[role="main"] $& :scope >div $& div:first-child >div[role="button"][aria-hidden], article[role="presentation"] $& div:first-child >div[style]:first-child:empty < $& div[role="presentation"] >div >ul';h.Fa="$& :scope >div:not([class]) >div[class] $& div.xg6iff7, div.xippug5 $& section.x5qyhuo >div:first-child $&10 :scope >div:not([role]):only-child";h.Ca='$& div.xzkaem6 div[aria-modal][role="dialog"] div >article <';
h.Ea="*.return.return.memoizedProps.coreVideoPlayerMetaData.videoFBID";h.Qa=C;h.Ra=RegExp("^(?:[^/]+|player\\.vimeo\\.com/video)/(\\d{2,})");h.Ua="$| video:scope $| video";h.Sa="$> :scope >div.player";h.Ta="$& div.vp-video $& div.vp-telecine";h.kb=function(a){this.ub(-1);this.g=a=browser.runtime.connect({name:(I?"top":"sub")+(a?":retry":"")+(location.protocol=="file:"?":file":"")});this.i(-1,a,"onMessage",this.Bc);this.i(-1,a,"onDisconnect",this.Ac)};h.Ac=function(){browser.runtime.lastError;this.ub();
this.g=this.X=null;window.__idm_init__=!1;window.__idm_connect__=null};h.Bc=function(a){switch(a.shift()){case 11:this.Ub.apply(this,a);break;case 17:this.Vb.apply(this,a);break;case 12:this.Xb.apply(this,a);break;case 13:this.dc=a.shift();break;case 14:this.$b.apply(this,a);break;case 15:this.ac.apply(this,a);break;case 16:this.cc.apply(this,a);break;case 18:this.Zb.apply(this,a);break;case 19:this.bc.apply(this,a)}};h.Gc=function(a,b){var c=this.G>=105;let d=this.G>=108,e=this.G>=113;switch(this.A=
a){case 1:this.K=this.ec=!0;this.$=2;if(a=b.shift())this.l=a;if(a=b.shift())this.ca=a;if(a=b.shift())this.Wa=RegExp(a,"s");if(a=b.shift())this.M=RegExp(a);if(a=b.shift())this.fb=RegExp(a);if(a=b.shift())this.I=a.split(/[|:]/).reduce(da,{});if(a=b.shift())this.Xa=RegExp(a);if(a=b.shift())this.Ya=a;if(a=b.shift())this.Za=a;(a=b.shift())&&c&&(this.$a=a);(a=b.shift())&&c&&(this.ab=a);(a=b.shift())&&c&&(this.bb=a);(a=b.shift())&&d&&(this.cb=RegExp(a,"s"));(a=b.shift())&&d&&(this.eb=a);if(a=b.shift())this.Va=
a;if(a=b.shift())this.Pa=a;if(a=b.shift())this.rc=a;if(a=b.shift())this.hb=a;if(a=b.shift())this.sc=a;if(a=b.shift())this.gb=a;break;case 2:this.mb();this.K=!0;this.$=3;if(a=b.shift())this.l=a;if(a=b.shift())this.L=a;if(a=b.shift())this.wa=RegExp(a);if(a=b.shift())this.Cb=a;if(a=b.shift())this.Fb=a;(a=b.shift())&&e&&(this.ua=a);if(a=b.shift())this.Aa=a.startsWith("$")?a:`$< ${a.slice(1)} <`;if(a=b.shift())this.Gb=a;if(a=b.shift())this.Bb=a.startsWith("$")?a:`$* ${a}`;if(a=b.shift())this.Ga=a.startsWith("$")?
a:`$< ${a.slice(1)} <`;if(a=b.shift())this.Hb=a;if(a=b.shift())this.yb=a.startsWith("$")?a:`$* ${a}`;if(a=b.shift())this.va=a;if(a=b.shift())this.ra=a;if(c=b.shift())this.ta=c;if(a=b.shift())this.Db=a;if(a=b.shift())this.sa=RegExp(a);break;case 4:this.mb();this.K=!0;if(a=b.shift())this.l=a;if(a=b.shift())this.ca=a;if(a=b.shift())this.L=a;if(a=b.shift())this.Ba=RegExp(a);if(a=b.shift())this.Ob=a;if(a=b.shift())this.Kb=a;(a=b.shift())&&e&&(this.Da=a);(a=b.shift())&&e&&(this.Fa=a);if(a=b.shift())this.Jb=
a;(a=b.shift())&&e&&(this.Ca=a);if(a=b.shift())this.Ha=a;if(a=b.shift())this.Nb=a;b.shift();(a=b.shift())&&e&&(this.Ea=a);(a=b.shift())&&e&&(this.Mb=RegExp(a));break;case 3:if(a=b.shift())this.Qa=RegExp(a);if(a=b.shift())this.Ra=RegExp(a);if(a=b.shift())this.Ua=a;if(a=b.shift())this.Sa=a;if(a=b.shift())this.Ta=a;break;case 5:this.K=!0;if(a=b.shift())this.l=a;if(a=b.shift())this.L=a;if(a=b.shift())this.Wb=a;break;default:this.K=!0;if(a=b.shift())this.l=a;if(a=b.shift())this.Oa=a}this.l.includes("^/")&&
((b=this.ca)?b="https?://"+b.slice(+b.startsWith("^"),-b.endsWith("$")||void 0):b=x.replaceAll(".","\\."),this.l=this.l.replaceAll("^/",`^(?:${b})?/`))};h.ha=function(a){if(this.A&&this.U(arguments))switch(this.A){case 1:this.qc(a);break;case 2:this.lc(a);break;case 4:this.mc(a);break;case 3:this.oc(a);break;case 5:this.nc(a)}};h.ea=function(a){let b=this.g;for(let c of document.getElementsByTagName("script"))!c.src&&a.test(c.text)&&b.postMessage([34,null,-1,c.type,c.text]);b.postMessage([34,this.C()])};
h.ka=function(a,b,c,d){if(this.Ab&&c){let e=a instanceof Element?this.R(a):0,f=this.Y,g=f.indexOf(null);g<0&&(g=f.length);f[g]=[a,b,d];this.la(1229212981,g,e,c)}else d(a,b)};h.Cc=function(a,b){var c=this.Y.splice(a,1,null).shift();if(c){a=c[0];let d=c[1];c=c[2];a instanceof Element&&!document.contains(a)&&(b=void 0);c(a,d,b)}};h.Fc=function(a){var b=a.data;if(Array.isArray(b)&&a.origin==x)switch(b[0]){case 1229212977:this.Ab=!0;a=btoa(J().toString().substr(2,9));b=btoa(J().toString().substr(2,9));
this.la(1229212978,this.X,this.o,a,b,ba,this.qa,this.K,this.ec,this.l,this.L);break;case 1229212979:this.g.postMessage([46,b[1],b[2],b[3]]);break;case 1229212980:this.g.postMessage([36,b[1],b[2]]);break;case 1229212982:this.Cc(b[1],b[2])}};h.la=function(a,...b){window.postMessage(X(arguments),"/")};h.fa=function(){let a=window.devicePixelRatio,b=document.width,c=document.body.scrollWidth;b&&c&&(a=b==c?0:b/c);return a};h.mb=function(){this.o||(this.o=btoa(J().toString().substr(2,9)))};h.R=function(a){let b,
c=a.j;c||(c=a.j=this.X<<13|this.zb++,this.v[c]=a,(b=this.o)&&a.setAttribute(b,c));return c};h.O=function(a){let b=this.o,c=this.v;b&&a.removeAttribute(b);Q&&(a.removeAttribute("__idm_uri__"),a.removeAttribute("__idm_obs__"));a.F&&(window.clearTimeout(a.F),a.F=null);a.D&&(a.D.disconnect(),a.D=null);this.Z.unobserve(a);this.V.unobserve(a);delete c[a.j];delete c[a.m];delete c[a.h];a.j=a.m=a.h=a.J=a.S=null};h.ib=function(a,b,c,d,e){let f=this.v,g=this.R(a);if(b||c){if(b&&f[b]||c&&f[c])return;d||=a.localName;
a.m=b;a.h=c||=`${this.Ka}${d}/${b}`;b&&(f[b]=a);c&&(f[c]=a);Q&&a.setAttribute("__idm_uri__",c)}a.D||(b=a.D=new MutationObserver(this.W.bind(this)),Q&&a.setAttribute("__idm_obs__",1),b.observe(a,{attributes:!0,attributeFilter:["style"]}),b.observe(a.parentElement,{childList:!0}),this.Z.observe(a),e&&this.V.observe(a));this.A==1&&t(a,this.Pa)&&(a.ga=!0,a.fc=10);return g};h.H=function(a,b,c,d,e){if(b=this.ib(a,b,c,d,e))c=this.P(a),this.g.postMessage([41,b,a.localName,a.src||a.data,a.h,a.m,c])};h.jb=
function(a,b,c){if(!a.j&&b.j){Q&&a.setAttribute("__idm_uri__",b.h);a.S=new WeakRef(b);b.S=new WeakRef(a);if(!a.D){let d=a.D=new MutationObserver(this.W.bind(this));Q&&a.setAttribute("__idm_obs__",1);d.observe(a,{attributes:!0,attributeFilter:["style"]});d.observe(a.parentElement,{childList:!0});this.Z.observe(a)}this.V.observe(a);this.V.observe(b);c&&this.wb(a,b)}};h.Ib=function(a){if(!a.j){var b=a.S;b&&((b=b.deref())?this.wb(a,b):a.S=null)}};h.wb=function(a,b){let c=this.o,d=this.v,e=a.j=b.j,f=a.m=
b.m,g=a.h=b.h;b.j=b.m=b.h=null;c&&b.removeAttribute(c);c&&a.setAttribute(c,e);d[e]=a;f&&(d[f]=a);g&&(d[g]=a)};h.Tb=function(a,b,c,d,e,f){let g,l,m,p;let n,k,r=window.getComputedStyle.bind(window);try{let w=0;m=document.activeElement;m&&K(m.localName)||(m=document.elementFromPoint(this.oa,this.pa))&&!K(m.localName)&&(m=null);for(let q of document.querySelectorAll("video,audio,object,embed")){let z=q.localName,y;var v=z=="object"||z=="embed";if(v){let G=q.type.toLowerCase();if(G.startsWith("text/")||
G.startsWith("image/"))continue;if(z=="embed"&&G!="application/x-shockwave-flash")continue}if(q.h&&!q.ga&&(e||f))if(e?e==q.m:f==q.h)g=q;else continue;else if(y=q.src||q.data)y!=a&&y!=b||(g=q);else if(!v)for(let G of q.getElementsByTagName("source"))if((y=G.src)&&(y==a||y==b)&&(g=q))break;if(g)if(r(q).objectFit=="cover")l=q,g=null;else break;if(l||m||p)continue;if(y){if((y==c||y==d)&&(p=q))continue;if(z=="video"&&y.startsWith("data:audio/"))continue}let E=q.clientWidth,A=q.clientHeight;if(!E||!A)continue;
let S=q.getBoundingClientRect();if(S.right+window.scrollX<=0||S.bottom+window.scrollY<=0)continue;let T=r(q);if(q.J||T.visibility=="hidden"||T.display=="none"){z=="video"&&(k||=q);continue}v=E*A;if(w<v&&E*1.35>A&&E<A*3){w=v;var u=q}n||=q}}catch(w){}(a=g||l||m||p)?a.localName!="video"&&r(a).visibility=="hidden"&&(a=null):a=u||n||k;a&&(a.localName!="embed"||a.clientWidth||a.clientHeight||(u=a.parentElement,u.localName=="object"&&(a=u)),this.ib(a,e,f));return a};h.Sb=function(a,b,c){let d=null,e,f=browser.runtime.getFrameId;
for(let g of document.getElementsByTagName("iframe")){let l=g.pb;l==null&&f&&(l=g.pb=f(g));if(l==a){d=g;break}else d||!(e=g.src)||e!=b&&e!=c||(d=g)}return d&&this.R(d)};h.P=function(a){let b=null;try{let c=window.getComputedStyle(a),d=a.getBoundingClientRect(),e=this.$,f=Math.round(d.width),g=Math.round(d.height),l;if(c.visibility=="hidden"&&!a.contentWindow)return f>g*5?null:!1;if(c.opacity==0||a.J)return!1;if(this.A==1&&a.offsetTop+a.offsetHeight==0){for(let u=a;u=u.parentElement;){let w=window.getComputedStyle(u);
if(w.display!="block")break;if(w.opacity==0)return!1}d=a.parentElement.parentElement.getBoundingClientRect();e=0;c.display=="none"&&t(a,this.Va)&&(f=Math.round(d.width),g=Math.round(d.height))}let m=Math.round(d.left)+a.clientLeft,p=Math.round(d.top)+a.clientTop;for(let u=0,w=0,q=a,z=c,y,E;e--&&z.display=="block"&&(y=q.parentElement)&&y.localName=="div";q=y,z=E){E=window.getComputedStyle(y);u-=q.offsetLeft;w-=q.offsetTop;if(E.overflowX=="hidden"){let A=f-y.offsetWidth-u;u>0&&(f-=u,m+=u);A>0&&(f-=
A);e=0}if(E.overflowY=="hidden"){let A=g-y.offsetHeight-w;w>0&&(g-=w,p+=w);A>0&&(g-=A);e=0}}switch(a.localName){case "video":document.contains(a)&&(a.videoWidth||a.h||a.readyState<1&&a.networkState==2)&&(b=!1);if(f<15||g<10)return b;break;case "audio":if(f<1&&g<1)return b;l=!0}let n=document.documentElement,k=n.scrollWidth||n.clientWidth||document.body.scrollWidth,r=n.scrollHeight||n.clientHeight||document.body.scrollHeight;if(m>=k||p>=r||l&&!m&&!p)return b;m==0&&p==-r&&f==k&&g==r&&(p=0);let v=a.fc||
0;b=[m,p+v,m+f,p+g-v,this.fa()]}catch(c){}return b};h.Lb=function(a){var b=a.hc;if(b){b=document.elementsFromPoint((b.left+b.right)/2,(b.top+(b.top+b.bottom)/2)/2);for(var c,d;(c=b.shift())&&!c.isSameNode(a);){let e=window.getComputedStyle(c);if(e.visibility=="visible"&&e.opacity!="0"&&!ha(e.backgroundColor)){d=!0;break}}a.J=d}};h.C=function(){let a=I?80:90;try{var b=window.top.document.title}catch(c){}b||(b=(b=document.head.querySelector('meta[property="og:title"]'))&&b.getAttribute("content"),a=
70);b&&(b=b.replace(/^\(\d+\)/,"").replace(/[ \t\r\n\u25B6]+/g," "),b=new String(b.trim()),b.src=a);return b};h.Yb=function(){if(!document.elementsFromPoint)return 0;var a=document.documentElement;let b=a.clientWidth||a.offsetWidth;a=(a.clientHeight||window.innerHeight)/4;var c=document.elementsFromPoint(0,0);let d=0,e=0,f=0;for(let l of c)if(l.offsetWidth>=b){var g=window.getComputedStyle(l);g.opacity>=.95&&(c=g.zIndex,g.position=="fixed"?(g=l.offsetHeight+l.offsetTop,d<g&&g<a&&(d=g,e=c)):f<c&&(f=
c))}e<f&&(d=0);return d};h.Ub=function(a,b,c,d,e,f,g,l,m,p,n,k,...r){this.G=a;this.X=b;if(n||=D.hostname.toLowerCase().split(".").at(-2))this.xa=RegExp(`^(?:\\(\\d+\\)\\s+)?(.+?)\\s+[-|@]+\\s*${n}$`,"i"),this.Ka=`idmrs://${n}/`;if(d){this.ma=d;try{window.frameElement&&(window.frameElement.pb=d)}catch(v){}}this.ob(f);m&&(this.qa=m);e&&this.Gc(e,r);p&&(Q=!0,ia.idm=this,this.o="__idm_id__",U("text/javascript",p));k&&(this.i(2,window,"message",this.Fc),U("text/javascript",k));document.readyState=="loading"?
this.La=!0:this.ha()};h.Vb=function(a){L=location.hostname.toLowerCase()+location.pathname+location.search;this.Ma&&this.u&&(this.u=0,this.Na=window.setTimeout(this.ja.bind(this,!1),3E3));this.ha(!0);a&&this.ob();for(let b of new Set(W(this.v)))this.Lb(b)};h.bc=async function(a,b,c,d,e,f){let g=new Headers,l=AbortSignal.timeout(1E7);d={method:d,headers:g,body:f,signal:l,priority:"high",cache:"force-cache"};if(e&&e.length){for(let p of e)g.append(p.name,p.value);g.has("referer")&&(d.referrer=g.get("referer"))}g.has("accept")||
g.append("accept","*/*");g.append("accept",`application/vnd.t1c.int-${a}`);c=await ca(c,d);let m;c&&c.status==200&&(b<0?(b=await c.arrayBuffer(),b=Y(b instanceof ArrayBuffer?new Uint8Array(b):b)):b=await c.text(),m=b);this.g.postMessage([45,a,m])};h.ob=function(a){if(this.U(arguments)){var b=[21,D.href,document.referrer];a&&b.push(document.getElementsByTagName("video").length,document.getElementsByTagName("audio").length);this.g.postMessage(b)}};h.$b=function(a){var b=a?this.U(arguments):1;if(b>0||
b<0&&this.A!=1){b=this.C();let c=this.fa(),d=this.Yb();this.g.postMessage([24,b,b&&b.src,c,d])}};h.cc=function(a,b,c,d,e){c||=this.Sb(b,d,e);d=(d=c&&this.v[c])&&this.P(d);this.g.postMessage([22,a,b,c,d])};h.Zb=function(a,b){let c,d,e=document.getElementsByTagName("a");for(let f of e)try{if(f.href==b){c=f.download||null;d=f.innerText.trim()||f.title||null;break}}catch(g){}this.g.postMessage([35,a,c,d])};h.ac=function(a,b,c,d,e,f,g,l){if(this.U(arguments)){var m=[23,a,b,!1],p,n;var k=this.v;if(b)(k=
k[b])||(m[3]=!0);else{k=l&&k[l]||g&&k[g];if(!k||k.ga)k=this.Tb(c,d,e,f,l,g);if(k){if(this.Oa&&(p=t(k,this.Oa)))var r=200;else if(p=k.getAttribute("operadetachedviewtitle"))r=130;m[2]=b=k.j;m[5]=k.localName;m[6]=k.src||k.data}else if(l||g)m[3]=!0;!p&&(p=this.C())&&(r=p.src,(n=this.xa.exec(p))&&(p=n[1]));m[7]=p;m[8]=r}if(k)if(p=this.P(k),p!=null||document.contains(k)){if(m[4]=p,a&&this.A==1&&this.ba)try{m[9]=window.sessionStorage.getItem(this.ba)}catch(v){}}else this.O(k),m[3]=!0;this.g.postMessage(m)}};
h.Xb=function(a,b,c,d){let e=d?RegExp(d,"i"):null;d=this.nb(document,e,b);let f=document.getElementsByTagName("iframe");for(let g of f)try{let l=g.contentDocument;l&&!g.src&&P(d,this.nb(l,e,b))}catch(l){}a=[27,a,this.ma,d.length];c||(a[4]=d,a[5]=D.href,I&&(a[6]=D.href,a[7]=document.title));this.g.postMessage(a)};h.nb=function(a,b,c){let d=[],e={};var f="";let g="",l=!c,m;if(c&&(m=a.getSelection(),!m||m.isCollapsed&&!m.toString().trim()))return d;for(let n of a.getElementsByTagName("a"))if(l||m.containsNode(n,
!0))try{let k=n.href;k&&!e[k]&&b.test(k)&&(e[k]=d.push([k,2,n.download||null,n.innerText.trim()||n.title]));c&&e[k]&&(g+=n.innerText,g+="\n")}catch(k){}for(let n of a.getElementsByTagName("area"))if(l||m.containsNode(n,!0))try{let k=n.href;k&&!e[k]&&b.test(k)&&(e[k]=d.push([k,2,null,n.alt]))}catch(k){}for(let n of a.getElementsByTagName("img"))if(l||m.containsNode(n,!0))try{let k=n.src;k&&!e[k]&&b.test(k)&&(e[k]=d.push([k,3,null,`<<<=IDMTRANSMITIMGPREFIX=>>>${n.alt}`]));l&&n.onclick&&(f+=n.onclick,
f+="\n")}catch(k){}if(c){if(f=m.toString()){c=this.N(g);for(var p of this.N(f))p&&!e[p]&&b.test(p)&&!c.includes(p)&&(e[p]=d.push([p,1]))}for(let n of a.getElementsByTagName("textarea"))if(a=n.selectionStart,f=n.selectionEnd,(p=m.isCollapsed&&a<f)||m.containsNode(n,!0))try{let k=p?n.value.substring(a,f):n.value;for(let r of this.N(k))r&&!e[r]&&b.test(r)&&(e[r]=d.push([r,1]))}catch(k){}}else{for(let n of a.getElementsByTagName("iframe"))try{let k=n.src;k&&!e[k]&&b.test(k)&&(e[k]=d.push([k,4]))}catch(k){}for(let n of a.getElementsByTagName("script"))f+=
n.innerText,f+="\n";if(f)for(let n of this.N(f))n&&!e[n]&&b.test(n)&&(e[n]=d.push([n,5]))}return d};h.N=function(a){if(!this.Ia){var b="\\b\\w+://(?:[%T]*(?::[%T]*)?@)?[%H.]+\\.[%H]+(?::\\d+)?(?:/(?:(?: +(?!\\w+:))?[%T/~;])*)?(?:\\?[%Q]*)?(?:#[%T]*)?".replace(/%\w/g,function(d){return this[d]}.bind({"%H":"\\w\\- -﻿","%T":"\\w\\-.+*()$!,% -﻿","%Q":"^\\s\\[\\]{}()"}));this.Ia=RegExp(b,"gi")}let c=[];for(;b=this.Ia.exec(a);)c.push(b.shift());return c};h.U=function(a){let b=this.u;b||(a=N(a&&a.callee?
a:arguments),a.unshift(arguments.callee.caller),this.na.push(a));return b};h.sb=function(a){let b;try{b=window.top.document.getElementsByTagName("title")[0]}catch(c){}this.u=a&&b?-1:1;b&&(a=this.Ma,a||(a=this.Ma=new MutationObserver(this.ja.bind(this))),a.observe(b,{childList:!0}),Q&&b.setAttribute("__idm_obs__",1));this.Z=new ResizeObserver(this.W.bind(this));this.V=new IntersectionObserver(this.W.bind(this),{threshold:.2});this.La&&(this.La=!1,this.ha());for(let c,d=this.na;c=d.shift();)c.shift().apply(this,
c)};h.W=function(a){if(this.g)for(let b of a)if(b.target.j)if(a=b.target,a.isConnected){let c=b.isIntersecting;if(c!=null){let d=a.J;a.J=!c;a.hc=c?b.intersectionRect:null;c&&d&&this.Ib(a)}a.F&&window.clearTimeout(a.F);a.F=window.setTimeout(this.uc.bind(this,a),200)}else this.g.postMessage([23,null,a.j,!0]),this.O(a)};h.uc=function(a){if(!this.g)return this.O(a);a.F=null;let b=document.contains(a),c;if(b){if(c=this.P(a),this.A==1&&a.ga)if(c){let d=t(a,this.Pa);d?.href&&d.href!=a.h&&this.H(a,null,d.href)}else a.h=
a.m=null,b=!1}else this.O(a);this.g.postMessage([23,null,a.j,!b,c])};h.ja=function(a){if(a)window.clearTimeout(this.Na),this.Na=window.setTimeout(this.ja.bind(this,!1),1E3);else{this.u<0?this.u=1:++this.u;for(let b,c=this.na;b=c.shift();)b.shift().apply(this,b)}};h.tc=function(a){var b=a.target;let c=b.localName;K(c)&&a.url&&(b=this.R(b),this.g.postMessage([25,b,c,a.url]))};h.tb=function(a){!a.repeat&&ea[a.keyCode]&&this.g.postMessage([31,a.keyCode,a.type=="keydown"])};h.xc=function(a){this.dc&&this.g.postMessage([28]);
if(a.button==0){let b=a.view.getSelection();b?.isCollapsed&&!b.toString().trim()&&(this.B=1);this.g.postMessage([32,a.button,!0])}};h.zc=function(a){if(a.button==0){this.oa=a.clientX;this.pa=a.clientY;this.g.postMessage([32,a.button,!1]);let b=a.view.getSelection();b&&this.B&&(this.B=b.isCollapsed&&!b.toString().trim()?0:2)&&this.g.postMessage([26,a.clientX,a.clientY,this.fa()])}};h.yc=function(){this.B==2&&(this.B=0)};h.wc=function(a){a=a.target;a.localName=="a"&&this.g.postMessage([39,a.hasAttribute("download"),
a.href,a.download])};h.Ec=function(){this.g.postMessage([29])};h.Dc=function(a){a=a.target;this.g.postMessage([30,a.innerWidth,a.innerHeight])};h.vc=function(){this.B=0;this.g.postMessage([33])};h.i=function(a,b,c,d,...e){e=N(arguments);e[3]=d.bind(this);this.Ja.push(e);a<0?(b=b[c],b.addListener.apply(b,e.slice(3))):b.addEventListener.apply(b,e.slice(2))};h.ub=function(a){let b=this.Ja;for(let c=0;c<b.length;c++){let d=b[c][0];if(a&&a!=d)continue;let e=b.splice(c--,1).pop(),f=e.splice(0,2).pop();
d<0?(f=f[e.shift()],f.removeListener.apply(f,e)):f.removeEventListener.apply(f,e)}};h.qc=function(a){this.aa&&(window.clearTimeout(this.aa),this.aa=null);var b=this.fb.exec(D.pathname+D.search);b&&this.xb(b[1]);if(!a){this.la(1229212983,this.sc);var c,d;a=0;for(var e of document.getElementsByTagName("script")){if(e.src){if(b=this.M.exec(e.src))a|=1,this.I[b[1]]?d=b[1]:c=e.src}else if(b=this.cb.exec(e.text)){a|=2;var f=b[1]&&parseInt(b[1],10);var g=b[2];var l=b[3]=="true";var m=b[4]||b[5];var p=b[7]&&
parseInt(b[7],10);if(b=this.M.exec(b[6]))this.I[b[1]]?d=b[1]:c||=x+b[0]}else if(this.Wa.test(e.text)){a|=4;var n=e.outerHTML}if(a==7)break}b=this.G>=101;e=this.G>=105;(a=l?g:m)?this.ba=V(a):this.ka(window,l||!b?136:138,l?this.rc:this.hb,this.Ic.bind(this));if(d||f||g||m||p||l!=null)var k={[124]:d,[144]:c,[118]:f,[136]:l||b?g:m,[138]:m,[143]:p,[139]:l};c&&e?(d=new XMLHttpRequest,d.responseType="text",d.timeout=1E4,d.onreadystatechange=this.Jc.bind(this,c,k,n,d),d.open("GET",c,!0),d.send()):(k&&this.g.postMessage([37,
1,2,k]),n&&this.g.postMessage([34,this.C(),null,null,n]))}};h.xb=function(a,b,c){let d=!b;d&&(b=t(document.body,this.gb));let e=t(document.body,this.eb),f=!!e?.offsetWidth,g=!f&&b||e;g&&d&&this.H(g,a,null,"video");e&&b&&e!==b&&(d&&f?this.jb(b,e):this.jb(e,b,f));!e&&(c||=0)<10&&(this.aa=window.setTimeout(this.xb.bind(this,a,b,++c),500))};h.Jc=function(a,b,c,d){if(d.readyState==4){var e=d.response,f=this.M.exec(a);a=this.Xa.exec(e);var g=f&&f[1],l=a&&parseInt(a[1]||a[2],10);if(l&&(!this.I[l]||!this.I[g])){a=
[null,119,120,135,141,142];f=[null,this.Ya,this.Za,this.$a,this.ab,this.bb];d={[118]:l,[124]:g,[144]:d.responseURL};let m=[];g=!0;for(l=0;g&&++l<f.length;){let p=f[l];l>1&&(p=p.replace(/\$\{(\d+)\.(\d+)\}/g,(n,k,r)=>m[k][r].replaceAll("$","\\$")));try{g=m[l]=RegExp(p,"s").exec(e)}catch(n){g=null}}if(l>=3){for(e=1;e<a.length;e++)m[e]&&(d[a[e]]=m[e][0]);this.g.postMessage([37,1,1,d])}else this.G>=110&&(d[140]=e,this.g.postMessage([37,1,4,d]))}b&&this.g.postMessage([37,1,2,b]);c&&this.g.postMessage([34,
this.C(),null,null,c])}};h.Ic=function(a,b,c){c&&(this.ba=V(c),this.g.postMessage([37,1,2,{[b]:c}]))};function V(a){let b=0,c=6038198,d=0,e;for(e=a.length>>1;b<e;b++)c=c*31+a.charCodeAt(b)|0;for(e=a.length;b<e;b++)d=d*31+a.charCodeAt(b)|0;return c.toString(16)+d.toString(16)}h.lc=function d(b,c){b?(c&&b.shift().disconnect(),this.ia.disconnect(),this.za.disconnect(),this.ya.clear()):(this.ea(this.wa),this.ia=new MutationObserver(this.Qb.bind(this)),this.za=new MutationObserver(this.Pb.bind(this)),
this.ya=new Set);if(c=this.Eb=t(document.body,this.Fb)){if(b=this.ia,b.observe(c,{childList:!0}),Q&&c.setAttribute("__idm_obs__","P"),!this.lb(c,!0)&&(c=t(c,this.Gb))){var e=t(c,this.Aa);e?(b.observe(e,{childList:!0}),Q&&e.setAttribute("__idm_obs__","P"),b.observe(c,{childList:!0}),Q&&c.setAttribute("__idm_obs__","P")):(b.observe(c.parentNode,{childList:!0}),Q&&c.parentNode.setAttribute("__idm_obs__","P"))}}else!b&&(c=t(document.body,this.Cb))&&(e=new MutationObserver(d.bind(this,b=[])),b.push(e),
e.observe(c,{childList:!0}),Q&&c.setAttribute("__idm_obs__","R"))};h.lb=function(b,c){let d=this.ia,e=this.Aa,f=this.Bb,g=this.za,l=this.ya,m=0;for(let p of t(b,f,[]))l.has(p)||t(p,f)||(l.add(p),g.observe(p,{childList:!0,subtree:!0}),Q&&p.setAttribute("__idm_obs__","M"),c&&(b=t(p,e))&&(m++,d.observe(b,{childList:!0}),Q&&b.setAttribute("__idm_obs__","P")),H(p.getElementsByTagName("video"),this.da.bind(this)));return m};h.Qb=function(b){let c=this.Eb;for(let d of b){b=d.target.isSameNode(c);for(let e of d.addedNodes)e.nodeType==
1&&this.lb(e,b)}};h.Pb=function(b){let c=this.Y,d=this.Ga;for(let e of b)for(let f of e.addedNodes)if(f.nodeType==1)if(b=f.getElementsByTagName("video"),b.length)H(b,this.da.bind(this));else for(let g of c)if(g){b=g[0];let l=t(b,d);l&&l.contains(f)&&this.da(b,!0)}};h.da=function(b,c){if(!b.h){var d=t(b,this.Ga),e=d&&t(d,this.Hb),f=t(b,this.va);if(!e&&!f){let l=this.ra,m=this.ta,p=O.bind(["div","span","a"]),n,k,r,v,u,w;for(let q=d;!f&&q&&m--&&p(q.localName);q=q.parentNode){k=q;let z;f=q;var g=`${l}:scope:first-child:only-of-type`;
for(z=0;g[z]=="<";z++);z&&(g=g.slice(z));for(f=f.closest(g);f&&z--;f=f.parentElement);!f&&(r=q.previousSibling)&&r.localName=="div"&&(n||=q.querySelector('div[role="slider"]'),(u=q.querySelectorAll(l)).length==1?f=u[0]:(v=q.nextSibling)&&(u=v.querySelectorAll("ul:scope "+l)).length==1?f=u[0]:(u=r.querySelectorAll(l)).length>1&&(f=u[u.length-1]))}f||(w=this.sa.exec(D.href)?.[1]);w&&t(b,this.ua)&&(e=w,f=D);!f&&k&&(u=t(k,this.yb,[])).length==1&&(f=u[0]);!f&&d&&(f=d.querySelector(`:scope >${l}`));f?f=
f.href:w&&b===document.getElementsByTagName("video")[0]&&(e=w)}e||f?this.H(b,e,f):c||this.ka(b,0,this.Db,this.Rb.bind(this))}};h.Rb=function(b,c,d){d&&this.H(b,d)};h.mc=function(b){!b&&(this.ea(this.Ba),b=t(document.body,this.Ob))&&(F(b,this.Kb,this.jc.bind(this)),F(b,this.Da,this.T.bind(this)),F(b,this.Fa,this.T.bind(this)),F(document.body,this.Ca,this.T.bind(this)))};h.qb=function(b,c,d){!c&&document.getElementsByTagName("video").length==1&&(c=this.Mb.exec(D.href))&&(c=c[1]);this.H(b,c,d,"video",
!0)};h.jc=function(b){for(let c of t(b,this.Jb,[]))H(t(c,this.Ha,[]),this.rb.bind(this))};h.T=function(b,c){c==41&&F(b,"$& :scope >div >div:only-child",this.T.bind(this));H(t(b,this.Ha,[]),this.rb.bind(this))};h.rb=function(b){if(!b.h){var c=t(b,this.Nb);c?this.qb(b,null,c):this.ka(b,0,this.Ea,this.kc.bind(this))}};h.kc=function(b,c,d){d&&this.qb(b,d)};h.oc=function(b){b||(this.ea(this.Qa),(b=t(document.body,this.Sa))&&F(b,this.Ta,this.Hc.bind(this)))};h.Hc=function(b){if(b=t(b,this.Ua)){let c=this.Ra.exec(L);
c&&this.H(b,c[1])}};h.nc=function(b){if(!b){var c=t(document.body,this.Wb);c&&(b=this.C(),c=c.outerHTML,this.g.postMessage([34,b,null,null,c.slice(0,c.indexOf(">")+1)]))}};function U(b,c){b=document.createElement(b.startsWith("image/")?"img":"script");b.src=browser.runtime.getURL(c);b.onload=b.remove.bind(b);document.documentElement.appendChild(b)}function t(b,c,d){function e(k,r,v){for(;v&&r--;)v=v.parentElement;v&&(isNaN(k)||this.push(k),this.push(v));return v}if(!c)return d;let f,g,l,m=!0,p=d||
[],n=c.split(fa);for(n.length==1?n.unshift(">",NaN):n.shift();b&&(f=n.shift());){c=parseInt(n.shift(),10);g=n.shift().trim();for(l=1;g[g.length-l]=="<";l++);--l&&(g=g.slice(0,-l).trim());switch(f){case "<":b=M(g?b.closest(g):b,l);m=!0;break;case ">":b=M(b.querySelector(g),l);m=!0;break;case "{":b.closest(g)&&(b=null);break;case "}":b.querySelector(g)&&(b=null);break;case "|":if(g=g.endsWith(":scope")?b.closest(g):b.querySelector(g))return M(g,l);m=!1;break;case "&":b=e.call(p,c,l,b.querySelector(g));
m=!1;break;case "*":b.querySelectorAll(g).forEach(e.bind(p,c,l));m=!1;break;case "+":g=g?g.endsWith(":scope")?b.closest(g):b.querySelector(g):b;e.call(p,c,l,g);m=!1;break;case "=":if(g=b.getAttribute(g))return g;m=!1;break;case "@":if(g=b.textContent.trim())return g;m=!1}}return p.length?p:m&&b||d}function F(b,c,d,e,f,g,l){if(e==null){e=[];f=t(b,c,[]);var m=f.at(-1),p=m&&typeof f.at(-2)=="number"?f.splice(-2,1).pop():null;e[0]=p;l=new MutationObserver(F.bind(null,b,c,d,e,f));l.observe(b,{childList:!0});
Q&&b.setAttribute("__idm_watch__",1);Q&&f.forEach(k=>k.setAttribute("__idm_watch__",1));for(var n of f)l.observe(n,{childList:!0});f.length&&d(m,p)}else for(m of g){for(p of m.addedNodes)if(p.nodeType==1)if(n=t(b,c,[]).slice(f.length),(g=n.at(-1))&&p.contains(g)){let k=typeof n.at(-2)=="number"?n.splice(-2,1).pop():null;e[0]=k;P(f,n);Q&&n.forEach(r=>r.setAttribute("__idm_watch__",1));for(let r of n)l.observe(r,{childList:!0});for(let r of g.children)d(r,k)}else m.target.isSameNode(f.at(-1)||b)&&d(p,
e[0]);for(let k of m.removedNodes)if(k.nodeType==1)for(n=0;n<f.length;n++)if(k.contains(f[n])){f.splice(n);break}}}function M(b,c){for(;b&&c--;b=b.parentElement);return b}new R}!0;
