(function(){function ta(c){let a=5381,b=c.length;for(let d=0;d<b;d++)a=a*33+c.charCodeAt(d)>>>0;return a}function ua(c,a){m.apply(this,arguments);try{if(M.test(a)){let b=this[W],d=`${N}-${++va}`;b[O]=d;this.addEventListener(wa,Ja.bind(this,d))}}catch(b){}}function Ka(c,a){try{let b=this[W];b[O]&&c.toLowerCase()==v&&(b[X]=!0)}catch(b){}r.apply(this,arguments)}function La(c){try{let a=this[W],b=a[O];if(b){let d=a[X];delete a[X];delete a[O];d||r.call(this,v,ia);r.call(this,v,`${ja}.pxr-${b}`)}}catch(a){}x.apply(this,
arguments)}function Ja(c){try{if(c){let a=this[xa],b=ka.exec(a);y([1229212980,c,b&&(b[1]||a)||null],"/")}}catch(a){}}function la(c,a){let b,d;var e;try{let h=Y(c);if(b=M.test(h?c[Z]:c))d=`${N}-${++va}`,h?e=c[k]:a?e=a[k]:a=arguments[1]={},e||=a[k]=new q[ma],e.has(v)||e.append(v,ia),e.append(v,`${ja}.pfm-${d}`)}catch(h){}e=n.apply(this,arguments);if(b)try{return e.then(Ma.bind(this,d))}catch(h){}return e}function Ma(c,a){try{if(a.ok&&a[p]){a[t]=P.bind(a,c,a[t],1);a[z]=P.bind(a,c,a[z],2);a[A]=P.bind(a,
c,a[A],3);a[B]=P.bind(a,c,a[B],4);a[C]=P.bind(a,c,a[C],5);a[na]=Na.bind(a,c,a[na]);let b=a[p];b[D]=ya.bind(b,a,c,b[D]);b[oa]=ya.bind(b,a,c,b[oa])}else y([1229212980,c],"/")}catch(b){}return a}function P(c,a,b,...d){a=a.apply(this,d);try{Q(this[k],w)||(E(this[k],w,{}),a=a.then(aa.bind(null,c,b)))}catch(e){}return a}function Na(c,a,...b){try{if(!Q(this[k],w)){E(this[k],w,{});let d=a.apply(this)[p][D]();d[R]().then(ba.bind(d,c,[]))}}catch(d){}return a.apply(this,b)}function ya(c,a,b,...d){let e=this;
try{if(!Q(c[k],w)){E(c[k],w,{});let [h,f]=this[pa](),F=f[D]();F[R]().then(ba.bind(F,a,[]));e=h}}catch(h){}return b.apply(e,d)}function ba(c,a,b){b.done?aa(c,1,a.join("")):(a.push(ca(b.value,za)),this[R]().then(ba.bind(this,c,a)))}function Aa(...c){return S(this,1,u,c)}function Oa(...c){return S(this,2,G,c)}function Pa(...c){return S(this,3,H,c)}function Qa(...c){return S(this,4,I,c)}function Ra(...c){return S(this,5,J,c)}function S(c,a,b,d){b=b.apply(c,d);try{let e=c[Z];if(e&&M.test(e)){let h=qa.map(ra[K].bind(c[k]));
h.unshift(e);let f=ta(h.join("|"));b=b.then(aa.bind(null,`${N}-${f}`,a))}}catch(e){}return b}function Sa(...c){let a,b;try{a=this[k],b=a[p]}catch(d){}if(b===void 0&&(b=L.apply(this,c)))try{let d=this[Z];if(d&&M.test(d)){let e=qa.map(ra[K].bind(a));e.unshift(d);let h=ta(e.join("|"));c=`${N}-${h}`;let [f,F]=b[pa](),da=F[D]();a[p]=b=f;da[R]().then(ba.bind(da,c,[]))}else a[p]=b}catch(d){}return b}function aa(c,a,b){try{let d;switch(a){case 1:d=b;break;case 2:d=JSON.stringify(b);break;case 3:d=ca(new Uint8Array(b));
break;case 4:d=ca(b);break;case 5:d=b[t]().then(aa.bind(null,c,1))}if(!Y(d)){let e=ka.exec(d??"");y([1229212980,c,e&&(e[1]||d)||null],"/")}}catch(d){}return b}function sa(c,a){let b=c;a=a.split(".");if(Y(b))if(a[0]=="*"){a.shift();for(let d of Ta(c))try{if(Y(b=c[d])&&Ua(b,a[0])){for(let e of a)b=b[e];if(b!==void 0)return b}}catch(e){}}else try{for(let d of a)b=b[d];return b}catch(d){}}function Ba(c,a){for(;c&&a--;c=c.parentElement);return c}const Va=Array.isArray,Y=Object.isExtensible,q=globalThis,
Wa=window.origin||document.origin||location.origin,y=window.postMessage.bind(window);let va=0,l,g,ra,ca,za,T,N=0,Ca,O,X,qa,Q,E,Da,U,ea,fa,W,wa,xa,V,k,p,t,z,D,oa,ma,v,ia,ja,Ea,Z,K,pa,R,C,A,B,Fa,Ga,na,w,M,ka,m,x,r,n,u,G,H,I,J,L;const Ua=Object.hasOwn||Function.call.bind(Object.prototype.hasOwnProperty),Ta=Object.getOwnPropertyNames,Xa=RegExp(" *\\$([<>=]) *");window.addEventListener("message",function(c){var a=c.data;if(Va(a)&&c.origin==Wa)switch(a.shift()){case 1229212978:var b,d,e;[N,Ca,O,X,qa,b,
h,d,f,e]=a;if(!b)break;[Da,U,ea,fa,W,wa,xa,V,k,p,t,z,D,oa,ma,v,ia,ja,Ea,Z,K,pa,R,C,A,B,Fa,Ga,na,w]=b.split("|");Q=Object[Fa];E=Object[Ga];if(f)M=RegExp(f),ka=RegExp(e);else var h=d=!1;(b=h)?(l||=q[Da].prototype,m||(m=l[U],l[U]=ua),l[U]!==ua&&(m=null),!x&&m&&(x=l[ea],l[ea]=La),!r&&m&&(r=l[fa],l[fa]=Ka)):(m&&(l[U]=m,m=null),x&&(l[ea]=x,x=null),r&&(l[fa]=r,r=null));d?(g||=q[Ea].prototype,ra||=q[ma].prototype,ca||=TextDecoder.prototype.decode.bind(new TextDecoder("utf-8")),za||={stream:!0},n||(n=q[V],
q[V]=la),q[V]!==la&&(n=null,u||(u=g[t],g[t]=Aa),g[t]===Aa?(G||(G=g[z],g[z]=Oa),H||(H=g[A],g[A]=Pa),I||(I=g[B],g[B]=Qa),J||(J=g[C],g[C]=Ra),L||(L=Q(g,p)[K],E(g,p,{[K]:Sa}))):u=null)):(n&&(q[V]=n,n=null),u&&(g[t]=u,u=null),G&&(g[z]=G,G=null),H&&(g[A]=H,H=null),I&&(g[B]=I,I=null),J&&(g[C]=J,J=null),L&&(E(g,p,{[K]:L}),L=null));(b||d)&&y([1229212979,b?!!m:null,d?!!n:null,d&&!n?!!u:null],"/");break;case 1229212981:let [Ya,Ha,Za]=a,ha;try{if(Ha?ha=document.querySelector(`[${Ca}="${Ha}"]`):ha=window,ha)a:if(c=
ha,a=Za,b=a.split(Xa),b.length>1){for(b.shift();c&&(h=b.shift());){var f=b.shift().trim();for(e=1;f[f.length-e]=="<";e++);--e&&(f=f.slice(0,-e).trim());switch(h){case "<":c=Ba(f?c.closest(f):c,e);break;case ">":c=Ba(c.querySelector(f),e);break;case "=":if(f=sa(c,f),f!==void 0){d=f;break a}}}d=void 0}else d=sa(c,a)}catch($a){}y([1229212982,Ya,d],"/");break;case 1229212983:if(d=a[0]){var [F,da,Ia]=d.split("|");if(n){if(T=sa(q[F],da))T[Ia]=la}else T&&(T[Ia]=void 0,T=null)}}},!1);y([1229212977],"/")})();
