var n;typeof browser=="undefined"&&(browser=chrome);
const aa=Boolean,v=Object.values,B=RegExp.prototype.test,ba=RegExp.prototype.exec,ca=Array.isArray,da=Array.from,ea=Array.prototype.includes,C=Math.floor,D=Math.random,E=Object.isExtensible,fa=Function.apply.bind(Array.prototype.push),ha=Function.apply.bind(String.fromCharCode,null),ia=Function.call.bind(String.prototype.charCodeAt),ja=String.fromCharCode,la=Function.bind.bind(function(a){return this[a]}),ma=Function.bind.bind(function(a){return a&&a[this]});
Array.prototype.at||(Array.prototype.at=function(a){a<0&&(a+=this.length);return this[a]});AbortSignal.timeout||(AbortSignal.timeout=function(a){let b=new AbortController;globalThis.setTimeout(b.abort.bind(b),a);return b.signal});const na=B.bind(/^(?:Host|Origin|Referer|Cookie|User-Agent|Connection|DNT|Accept-Encoding|Sec-.+)$/i),oa=["date","content-type","content-length"];function pa(a,b){return fetch(a,b).catch(()=>null)}function qa(a){return ha(a instanceof ArrayBuffer?new Uint8Array(a):a)}
function ra(a){return E(a)?a.source.replaceAll("\\/","/"):a}function sa(a){return a.replace(/[a-z]/gi,function(b){return ja((b=ia(b))+((b&31)>13?-13:13))})}function F(){if(this.constructor!==F)return ta.promise;this.promise=new Promise((a,b)=>(this.resolve=a,this.reject=b));ta=this}var ta;F.prototype.g=function(...a){let b=browser.runtime.lastError;b?this.reject(b):this.resolve(...a)};function G(){return F.prototype.g.bind(new F)}const I={};I[-1]=[2,[111,112],[111]];
I[1]=[2,[115,116,117,124,118,119,120,121,127,131,132,123,125,133,126,129,130,134,135],[115,111,112,113,114]];I[2]=[2,[114,113,113,115,116,117,118,122,119,125,126,124,121,120,123,112],[111,112,114]];I[3]=[null,[113,114,115,116,117],[112]];I[4]=[2,[111,101,113,112,114,118,119,124,115,116,117,120,121,122,123],[111]];I[5]=[null,[111,112,113],[111]];I[6]=[null,[],[111]];
const ua={16:1,17:2,18:4,45:8,46:16},va={http:1,https:9,ftp:2,ftps:10,idmreg:12,idmdwnlmfv3:33,idmdwnlmfv4:33,idmdwnlmfv5:33},wa=B.bind(/^(?:https?|socks[45])$/),ya={direct:2,auto_detect:3,system:4,pac_script:5,fixed_servers:7},za={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|VTT|SRT|M3U|PLS|M3U8|MPD|F4M|TORRENT|BTT","text/srt":"SRT","text/vtt":"VTT|SRT","text/xml":"XML|MPD|F4M|TTML|TTML2","text/x-javascript":"JS|JSON","text/x-json":"JSON",
"application/dash+xml":"MPD","application/f4m+xml":"F4M|MPD","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/json+protobuf":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/ocsp-response":"OCSP","application/octet-stream-m3u8":"M3U8","application/pdf":"PDF","application/pkix-crl":"CRL","application/torrent":"TORRENT|BTT","application/ttaf+xml":"DFXP","application/ttml+xml":"TTML|TTML2","application/vnd.apple.mpegurl":"M3U8","application/vnd.yt-ump":"UMP",
"application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-bittorrent":"TORRENT|BTT","application/x-chrome-extension":"CRX","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-dosexec":"EXE","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI",
"application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|TSV|M3U8",
"video/mp4":"MP4|M4V|M4S","video/mpeg":"MPG|MPEG","video/mpegurl":"M3U|M3U8","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/vnd.mpeg.dash.mpd":"MPD","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U|M3U8","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp2t":"TS|TSA|M3U8","audio/mp3":"MP3","audio/mp4":"M4A|MP4|M4S",
"audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U|M3U8","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/avif":"AVIF","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};
var Aa,Ba,Ca;const J=globalThis,Da=browser.runtime.id,Ea=browser.runtime.getManifest();var Fa=Ea.permissions.includes("notifications")||null;const Ga={16:"images/logo16.png",32:"images/logo32.png"},Ha={16:"images/logo16x.png",32:"images/logo32x.png"},Ia=["127.0.0.1:1001","0.1.0.1:1001"],Ja=RegExp("(?!)"),Ka=["main_frame","sub_frame"],La=["object","image"];var Ma=La.concat("xmlhttprequest","media"),Na=Ka.concat(La,"xmlhttprequest","media","other");
const K=["*://*/*"],Oa=["ftp://*/*"],Pa=K.concat(Oa,"file:///*","about:blank"),Qa=K.concat("about:blank"),Ra=btoa(D().toString().substr(2,9)),Sa=browser.runtime.getURL("captured.html?"+(Ra?`auth=${Ra}&`:"")),Ta=browser.runtime.getURL("welcome.html?"+(Ra?`auth=${Ra}&`:"")),Ua=browser.runtime.getURL("").slice(0,-1),Va=sa("KZYUggcErdhrfg|bcra|fraq|frgErdhrfgUrnqre|hcybnq|ybnqraq|erfcbafrGrkg|srgpu|urnqref|obql|grkg|wfba|trgErnqre|cvcrGuebhtu|Urnqref|npprcg|*/*|nccyvpngvba/iaq.g1p|Erfcbafr|hey|trg"),
Wa=sa("|Erfcbafr|hey|trg"),Xa=sa("|grr|ernq|oybo|neenlOhssre|olgrf|trgBjaCebcreglQrfpevcgbe|qrsvarCebcregl"),Ya=B.bind(/^(?:chrome|about|chrome-extension|chrome-search|ms-browser-extension|ms-appx-web|moz-extension):/),Za=B.bind(/^(?:application\/(?:json|x-javascript)|text\/(?:javascript|plain))$/),$a=B.bind(/^(HTM|HTML|CGI|PHP|ASP|ASPX|JSP|JSPX)$/i),ab=B.bind(/^(MPD|M3U8|F4M)$/i),bb=B.bind(/^ftp:|^idmreg:|\bidman|\binternetdownloadmanager\b/i),cb=B.bind(/^[GPTSDVACRHX]*$/),db=ba.bind(/^(.*?)(,\s*)?\bapplication\/vnd\.t1c\.(\w+)-([^\s,]+)(?:,\s*)?(.*)$/),
eb=ba.bind(/\.([^.\\/]*?)(?:\.[0-9.]+)?$/),fb=ba.bind(/^v(\d+)\.(\d+)(?:b(\d+))?\b/),gb=ea.bind([301,302,303,307,308]),hb=/[:,;]/,ib=/[,;]/,jb=[],kb=B.bind(RegExp("messaging host not found","i"));
function lb(a,b,c,e,d,f,g,h){if(a){var k=["MSG#",a,"#",b,"#",c,"#",e];this.l=a;this.type=b;this.A=c;this.j=e;this.g=d||[];this.o=k;this.G=g;this.D=h;if(d)for(let l of d)k.push(":",l||0);if(f)for(let l in f)if(parseInt(l)&&(g=l,a=f[l],a!=null&&!this.m))switch(b=this.o,c=this.G,d=this.D,e=c&&d,d=d?"/":":",h=a instanceof String?"string":typeof a,b.push(",",g,"="),h){case "string":b.push(mb(a),":",a);break;case "number":b.push(a);break;case "boolean":b.push(a?1:0);break;case "object":if(a instanceof Array){g=
b.length;k=h=0;for(let m of a)m instanceof ArrayBuffer||m instanceof Uint8Array?(c?(m=qa(m),h+=m.length):h+=m.byteLength,++k):(m=m.toString(),h+=mb(m)),b.push(m);k&&e?(a=btoa(b.splice(g).join("")),b.push(a.length,"%",a)):b.splice(g,0,h,k?d:":")}else a instanceof ArrayBuffer||a instanceof Uint8Array?e?(a=btoa(qa(a)),b.push(a.length,"%",a)):c?(a=qa(a),b.push(a.length,":",a)):b.push(a.byteLength,d,a):a instanceof Blob&&b.push(a.size,d,a)}}else this.v=new FileReader}
function nb(){this.g=nb.prototype.B++}nb.prototype.B=1;function ob(a,b,c,e){this.id=a;this.port=b;c&&(this.h=c=c.toLowerCase(),this.i=c=="iframe");e&&(this.j=e)}ob.prototype.g=0;function L(a,b){return`${a},${b}`}function pb(a,b,c){this.id=L(b,a);this.i=c==null||c<0?null:L(b,c)}function qb(){}function rb(a){a.m||(a.o.push(";"),a.m=!0);return new Blob(a.o)}function sb(a,b,c){a.m?a.h(a):(b.g=c||0,b.h=0,a.v.onload=a.B.bind(a,b),tb(a,b,0,50))}
lb.prototype.B=function(a){for(var b=this.v.result;;)switch(a.h){case 0:var c=b.search(hb);if(c<=0)return this.h(this);var e=b[c],d=b.slice(0,c++).split("#",6);if(d.length!=5||d[0]!="MSG")return this.h(this);this.l=parseInt(d[1]);this.type=parseInt(d[2]);this.A=parseInt(d[3]);this.j=parseInt(d[4]);b=b.slice(c);a.g+=c;a.h=e==":"?1:e==","?2:5;break;case 1:c=b.search(ib);if(c<=0)return c?tb(this,a,b.length,100):this.h(this);e=b[c];d=this.g=b.slice(0,c++).split(":");for(var f=0;f<d.length;f++){let g=
d[f];d[f]=g.includes(".")?parseFloat(g):parseInt(g)}b=b.slice(c);a.g+=c;a.h=e==","?2:5;break;case 2:c=b.search(hb);if(c<=0)return c?tb(this,a,b.length,25):this.h(this);e=b[c];f=b.slice(0,c++).split("=",3);if(f.length!=2)return this.h(this);d=parseInt(f[0]);f=parseInt(f[1]);a.g+=c;if(e==":"){a.j=d;a.i=f;a.h=3;b=a;a=a.i;c=b.g;b=b.slice(c,c+a);b.size==a?this.v.readAsText(b):this.h(this);return}this[d]=f;b=b.slice(c);a.h=e==","?2:5;break;case 3:return this[a.j]=b,a.g+=a.i,a.h=4,tb(this,a,0,21);case 4:switch(b[0]){case ",":a.h=
2;b=b.slice(1);break;case ";":a.h=5;break;default:return this.h(this)}a.g++;break;case 5:this.m=!0;this.u(this);a.size>a.g&&(b=new lb,b.u=this.u,b.h=this.h,sb(b,a,a.g));return}};function tb(a,b,c,e){let d=b.g;c=d+c;b.size>c?a.v.readAsBinaryString(b.slice(d,c+e)):a.h(a)}
function N(){let a=this.constructor.prototype;for(let b in a)b.startsWith("_")||b=="constructor"||(this[b]=a[b].bind(this));this.u=0;this.H=null;this.R=this.na=0;this.Qa=1;this.D=null;this.Sb=Ea.version||"";this.Sa="";this.sa=0;this.la=!1;this.N=null;this.U=!1;this.J=this.I=null;this.ya=this.A=!1;this.Ta=!0;this.Na=this.P=null;this.Ra=this.ha=this.pa=!1;this.Qb=1;this.Ca=this.v=this.X=null;this.Da=1;this.Ua=0;this.O=this.M=null;this.Oa=Ja;this.aa=[];this.Aa=0;this.Pa=null;this.Ea=this.oa=!1;this.B=
null;this.ta=Array(16);this.i={};this.m={};this.g={};this.G={};this.h={};this.Y={};this.l={};this.j={};this.ra={};this.fa={};this.o={};this.qa={};this.ga={};this.ga.Rb=[];this.Ja=[];ub(this,!1);browser.browserAction.onClicked.addListener(this.gb);browser.runtime.onMessage.addListener(this.kb);browser.windows.onCreated.addListener(this.ab);browser.windows.onRemoved.addListener(this.bb);browser.windows.onFocusChanged.addListener(this.Mb);browser.windows.onBoundsChanged&&browser.windows.onBoundsChanged.addListener(this.Lb);
browser.tabs.onActivated.addListener(this.Cb);browser.tabs.onUpdated.addListener(this.Fb);browser.tabs.onAttached.addListener(this.Db);browser.tabs.onRemoved.addListener(this.Eb);browser.webRequest.onBeforeRequest.addListener(this.hb,{urls:[browser.runtime.getURL("*")]},["blocking"]);vb(this);wb(this)}n=N.prototype;n.kb=function(a,b){switch(a[0]){case 38:a[1]&&this.la&&browser.storage.local.set({silent:!0});browser.tabs.remove(b.tab.id);break;case 43:browser.management.uninstallSelf({showConfirmDialog:!0})}};
n.gb=function(a){if(this.Ra){if(this.Ob)return browser.windows.update(this.Ob,{focused:!0});var b=a.id,c=this.o[b];ub(this,c,b,!0);this.ha&&(c?(this.ea(a.windowId),xb(this,b)):yb(this,b))}};function ub(a,b,c,e){c?a.o[c]=!b:a.Ra=b||e;zb(b,c,e)}
function zb(a,b,c){if(c||!b||!a){var e=a?Ga:Ha;browser.browserAction.setTitle({title:a?Ab+Bb:b?Cb+Bb:c?Cb:Db,tabId:b});browser.browserAction.setIcon({path:e,tabId:b});a||browser.browserAction.setBadgeBackgroundColor({color:"#606060"});browser.browserAction.setBadgeText({text:a?"":"X",tabId:b})}}
function Eb(a,b){a.A&&(browser.downloads.setUiOptions||browser.downloads.setShelfEnabled(!b));if(b){a.A&&a.L(3,browser.downloads.onCreated,a.ib);a.A&&a.L(3,browser.downloads.onDeterminingFilename,a.jb);b=["blocking"];const c=Ca?[]:["extraHeaders"];a.L(4,browser.webRequest.onBeforeRequest,a.$a,{urls:Oa,types:Ka},b);a.L(4,browser.webRequest.onBeforeRequest,a.$a,{urls:K,types:Na},["requestBody"]);a.L(4,browser.webRequest.onBeforeSendHeaders,a.Hb,{urls:K,types:Na},["requestHeaders"].concat(b,c));a.L(4,
browser.webRequest.onHeadersReceived,a.Jb,{urls:K,types:Na},["responseHeaders"].concat(b));a.L(4,browser.webRequest.onResponseStarted,a.Kb,{urls:K,types:Na});a.L(4,browser.webRequest.onErrorOccurred,a.Ib,{urls:K,types:Na})}else a.Ka(3,4)}
n.Za=function(a){browser.runtime.lastError;if(a){var b=a.value;a=ya[b.mode];var c,e;this.ta.fill(void 0);if(a==5&&(e=b.pacScript))e.data&&e.data.length>5E4?a=4:(c=e.data)?(a=6,c=c.replace(/\blet\b/g,"var").replace(/,(?=(?:\s*\/\/.*?\n)*\s*[\]}])/g,"")):c=e.url,this.ta.fill(!0);else if(a==7){b=b.rules;e=b.bypassList;c=Hb(this,b.singleProxy);if(!c){c=Hb(this,b.fallbackProxy);let d=Hb(this,b.proxyForHttp,1),f=Hb(this,b.proxyForHttps,9);b=Hb(this,b.proxyForFtp,2);d!=f||d!=b||d!=c&&c?(c=`${d??""};${f??
""};${b??""};${c??""}`,++a):c=d}e&&e.length&&(c+=";"+e.join(","))}b=a<5?a.toString():c?`${a}:${c}`:null;b!=this.B&&(this.B&&Ib(this),this.B=b)}};function Hb(a,b,c){if(b){let e=b.scheme||"http",d=e=="https";a=a.ta;c?a[c]=d:a.fill(d);if(wa(e))return`${e}://${b.host}${b.port?":":""}${b.port||""}`}}
async function Ib(a){if(a.u){var b=a.M;if(!b){var c=a.u==1?(new URL(a.H.url)).host:Ia[0];c="http://"+c;b=c+"/status/204+IDM"}var e=AbortSignal.timeout(1E3);(e=await pa(b,{cache:"no-cache",signal:e}))&&e.status==204?c&&(a.O=a.N?c+"/client/"+a.N:null,a.M=b):a.M=a.O=null}}n.xa=function(a,b,c,e){let d=this.l;return b in d?d[b]:d[b]=new ob(b,a,c,e)};
function Jb(a,b,c,e,d){let f,g,h;E(b)?(f=b.frameId??0,g=b.parentFrameId,h=b.method&&b.id,c||=b.tabId,d||=b.url):f=b;let k=a.G[L(c,f)];k||(k=new pb(f,c,g),a.G[k.id]=k);h?(k.l!=h&&(k.l=h,k.A=d,k.j=!1,k.h&&(k.h=d.startsWith(b.initiator||b.originUrl))),k.u=b.method=="POST"):d&&(d.startsWith("about:blank")?f&&(k.h=!0):k.C=d);e!=null&&(k.o=e);return k}function Kb(a,b){return a.G[L(b.tabId,b.frameId)]}function Lb(a){let b=new nb;return a.Y[b.g]=b}
function Mb(a,b){let c;b instanceof nb?c=b.g:b=a.Y[c=b];delete a.Y[c];return b}function Nb(a,b){for(let c of a.aa)if(c&&c[101].test(b))return c.W;return 0}
n.za=function(){var a=this.na%(Ia.length+1);a<Ia.length?(a=this.H=new WebSocket(`ws://${Ia[a]}/?cid=${this.N||0}&rnd=${D().toString().substr(2,9)}`,"plugin.v3.internetdownloadmanager.com"),a.onerror=O,a.onopen=this.Ha,a.onclose=this.ja,a.onmessage=this.Bb,a.readyState==1?this.Ha(1):a.readyState==3?this.ja():this.D=J.setTimeout(this.ja,1500,a)):(a=this.H=browser.runtime.connectNative("com.tonec.idm"),a.onDisconnect.addListener(this.ja),a.onMessage.addListener(this.ob),this.D=J.setTimeout(this.Ha,0,
2))};n.Ha=function(a){this.D&&(J.clearTimeout(this.D),this.D=null);this.u=E(a)?1:a;this.Qa=1;this.la=!1;a=browser.i18n.getUILanguage().replace("_","-");a=="sr"&&(a+="-Cyrl-CS");P(this,2,5,1024,[112,90,1031,0,16845059,this.N,0,Ea.manifest_version],{[112]:Ba,[113]:Aa,[116]:a})};
n.ja=function(a){this.D&&(J.clearTimeout(this.D),this.D=null);var b=browser.runtime.lastError||a&&a.error,c=this.H;if(c instanceof WebSocket){if(a===c)return c.close()}else c&&kb(b&&b.message)&&(this.la=!0);this.H=null;this.u&&(this.u=0,this.ra={},Eb(this,!1),this.Ka(1,2),this.ha=!1,this.B=this.O=this.M=null,ub(this,!1));a=++this.na;b=Ia.length+1;c=a/b;c<120&&(c==1&&Ob(this),!a||a%b?this.za():J.setTimeout(this.za,5E3*c))};
n.Wa=function(){let a=this.H;a instanceof WebSocket?a.close():a&&(a.disconnect(),this.ja())};n.Bb=function(a){let b=new lb;b.u=this.Xa;b.h=this.Wa;sb(b,a.data)};n.ob=function(a){let b=new lb;b.u=this.Xa;b.h=this.Wa;sb(b,new Blob([a]))};
function P(a,b,c,e,d,f,g){let h=a.R,k=a.u;if(!k)return 0;let l=a.Qa++;b=new lb(l,b,c,e,d,f,k==2,h>=99);if(g)return g.open("POST",`${a.O}?seq=${l}`,!1),g.send(rb(b)),g.status==200?l:0;if(k==1)a.H.send(rb(b));else try{var m=a.H,p=m.postMessage;b.m||(b.o.push(";"),b.m=!0);p.call(m,b.o.join(""))}catch(q){return a.ja(),0}e&1&&(a.ra[l]=b);return l}
function Pb(a,b){if(b.g){var c=b.g[1],e=a.j[c];if(e)return e.h?b.i=e.port.id:null;e=a.m;for(var d in e)if(e[d].l==c)return b.i=d}c=b[6];d=b[17];e=b[50];let f=b[7];var g=a.ga;let h=a.l;a=a.g;let k,l,m;if((k=g[c])||(k=g[d]))return b.i=k.id;if(k=g[e])m=k.id;for(let p in h){g=h[p];let q=g.j;if(q){if(q==c||q==d||q==e){k=g.port;if(f){let r=a[k.tabId];r&&r.C!=f&&(k=null)}if(k)return b.i=k.id}q==f&&(l=g.port.id)}}return m?b.i=m:l?b.i=l:null}
function Qb(a,b){let c=b.i;if(c)return c;if(b.g){var e=a.g[L(b.g[6],b.g[7])];e?c=e.id:(e=b.g[7])&&a.m[e]&&(c=e)}if(c||=Pb(a,b))return b.i=c;e=a.m;let d=b[50],f=b[7];for(let g in e){let h=e[g];if(h.C==d)return b.i=h.id;h.C==f&&(c=h.id)}return c?b.i=c:f?F(browser.tabs.query({url:f},G())).then(g=>g?.length&&(g=a.g[g[0].id])?b.i=g.id:null,()=>null):null}
async function Rb(a,b){var c=b.tabId;let e=b.ba;if(e>0&&!b.i){var d=await F(browser.webNavigation.getFrame({frameId:e,tabId:c},G()));d&&(d=d.parentFrameId,d>=0&&(b.i=L(c,d)))}if(e!=null&&b.u){if(d=a.G[L(c,e)]){b.l=d.l;b.m|=d.j;b.j|=d.o;b.B=d.h;let f=d.ca;f&&b.C!=f&&(b.ca=f);b.i||(b.i=d.i);(d=a.j[b.l])&&!d.port&&(d.port=b)}a.g[L(c,e)]=b;d=b.W;c=[11,a.R,b.id,c,e,d,b.j,b.m,a.i[22],a.i[23],jb[a.ya?1:null]];d&&b.m&&(a=a.aa[d],c.push(a.Tb,jb[a.fb]),fa(c,a.cb.map(la(a)).map(ra)));b.postMessage(c)}}
n.ka=async function(a,b,c,e,d,f){var g=Q(a);if(g){var h=(g&32)>0,k=(g&=7)==1,l;k&&!h&&(l=await R(a));g=[g];a={[6]:Sb(a,k&&this.U),[50]:b,[7]:c,[8]:e,[100]:d,[102]:f,[51]:T(l),[54]:navigator.userAgent,[121]:this.B};P(this,14,1,0,g,a)}};
async function Tb(a,b,c){if(b&&b.length){var e=b.map(k=>R(k[0]));if(c){var d=c.i;var f=c.O;var g=c.u;d&&!f&&e.push(R(d))}e.length&&(e=await Promise.all(e),b.forEach(k=>k[5]=T(e.shift())),e.length&&(f=T(e.shift())));c=0;var h=[0,0,0];d={[8]:4,[54]:navigator.userAgent,[7]:d,[110]:g,[111]:f,[121]:a.B};b.length>1&&(h[1]=P(a,15,1,0,[b.length],d),c=16,d={});for(let k of b)h[2]++,d[6]=k[0],d[100]=k[2],d[102]=k[3],d[50]=k[4],d[51]=k[5],P(a,14,2,c,h,d)}}
n.Ba=function(a,b){if(!this.u)return Ub("cannot_contact_idm");let c=a.linkUrl,e=a.pageUrl,d=e,f=this.g[L(b.id,a.frameId)];if(a.menuItemId==this.qa[5])return browser.downloads.search({query:[c]},this.eb.bind(this,c));if(a.menuItemId==this.qa[2]){if(c=a.frameUrl,c&&c!="about:blank"||(c=e,d=null),this.I&&f?.W)return Vb(this,!0)}else if(!c){c=a.srcUrl;if(!Q(c)){if(this.I&&f?.W&&a.mediaType=="video")return Vb(this,!0);return}if(f&&c)return a=Lb(this),a.tabId=b.id,a.port=f,a.o=c,a.v=d,a.i=e,a.m=4,f.postMessage([18,
a.g,c])}this.ka(c,d,e,4)};n.Ma=function(a,b){if(!this.u)return Ub("cannot_contact_idm");Wb(this,b.id,a.menuItemId==this.qa[3])};n.eb=function(a,b){let c,e,d;for(;c=b.pop();)c.exists&&c.state=="complete"?e||(d||=c.referrer):(e||=c.referrer,browser.downloads.erase({id:c.id}));this.ka(a,e||d,null,4)};
function Wb(a,b,c,e,d,f,g,h,k){if(!e||a.i[-5]){var l=a.g[b];if(l){var m=Lb(a);m.tabId=b;m.port=l;m.N=c;m.R=d;m.h=0;m.j=[];if(l=e&&!!f)m.J=!0,m.M=f,m.D=g,m.G=h,m.A=k,f.h||Xb(a,f);f=m.g;(e=e&&a.i[12])?(e=e.replace(/\./g,"\\.").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"),e=`${"^(?:http|https|ftp|ftps)://"}(?:[^\\/]*@)?(?:${e})(?::\\d+)?(?:\\W|$)`):e="^(?:http|https|ftp|ftps)://";m.l=Yb(a,b,[12,f,c,l||d,e]);m.H=0;m.l||Mb(a,m)}}}
n.Pb=function(a,b,c,e,d,f,g,h){if(a=this.Y[b]){e&&(a.h+=e);g&&(a.i=g);h&&(a.u=h);if(d&&(typeof d=="string"&&(d=JSON.parse(d)),d instanceof Array)){if(f)for(let k of d)k[4]=f;fa(a.j,d)}++a.H<a.l||(a.J?(e=a.tabId,(d=this.h[a.port.g])&&d.K==e&&a.h&&(f=a.A,g=d.h,h=d.i,P(this,10,1,0,[4294967295,d.A,Math.round(a.D*f+(d.l+g)*h),Math.round(a.G*f+(d.H+g)*h),0,a.h]),this.v=e,Yb(this,e,[13,!0]))):(e=a.j,e.length?Tb(this,e,a):Ub("cannot_find_links")),Mb(this,a))}};
n.sb=function(a,b,c,e){(a=Mb(this,b))&&this.ka(a.o,a.v,a.i,a.m,c,e)};n.ib=function(a){if((this.A||a.byExtensionId)&&!this.Ea&&this.i[-6]){var b=a.finalUrl||a.url;if(Q(b,!0)){var c=a.id,e=Date.parse(a.startTime),d;for(d of v(this.j))if(b==d.url&&e>=d.Y&&e-d.Y<50)break;if(d&&(d.La=c,a.request=d,this.o[d.tabId]))return;this.fa[c]=a;browser.downloads.pause(c,O)}}};
n.jb=function(a,b){var c=a.id;let e=this.fa;var d=e[c];if(d){var f=this.i,g=d.request;d=a.finalUrl||(a.finalUrl=a.url);var h=g?g.wa:new URL(d),k=g?g.V:a.V=Q(d,!0),l=g?g.ia:a.ia=U(a.filename||h.pathname);if(!((g?g.oa:a.l=this.oa)||this.A||f[1].test(l)&&!f[9].test(h.hostname)&&!f[19].test(h.href)))return Zb(this,c);a.request=g;a.Ub=b;e[c]=a;if(g)return V(this,2,g,null,a)?a.Fa=!0:Zb(this,c);if(k==1){if(!a.referrer){b=this.h;for(var m of v(this.m))if(m.C==d&&(a.referrer=m.G,(c=b[m.g])&&c.K==m.tabId))break}m=
R(d);d=d==a.url?null:R(a.url);Promise.all([m,d]).then(p=>$b(this,a,...p));return a.Fa=!0}return $b(this,a)}};function $b(a,b,c,e){var d=Date.parse(b.startTime)||Date.now();d=[b.id,0,C(d),0,b.V,2];c={[6]:Sb(b.finalUrl,a.U),[4]:b.ia,[103]:b.totalBytes||null,[100]:b.filename||null,[127]:b.mime||null,[8]:b.l?2048:0,[50]:b.referrer||null,[51]:T(c),[54]:navigator.userAgent,[122]:a.B};b.finalUrl!=b.url&&(c[17]=Sb(b.url),c[56]=T(e));return!!P(a,13,1,129,d,c)||Zb(a,b.id)}
function Zb(a,b,c){let e=a.fa[b];if(e){delete a.fa[b];let d=e.request;d&&(d.La=null,d.Ga&&W(a,d));if(c)return browser.downloads.cancel(b,O),!0;e.Fa&&(e.Fa=!1,e.Ub());browser.downloads.resume(b,O)}}n.wb=function(a,b,c,e,d,f){this.xa(a,b,c,e);P(this,23,2,0,[b,a.tabId,a.l,a.W,a.ba],{[132]:e,[133]:d,[134]:f})};
n.Z=function(a,b,c){if(a==4294967295)this.v=null,c=!0;else{let e=this.l[a];if(e){c=e.g;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:e.g=3;J.setTimeout(this.Z,1E3,a,!1,!0);return}e.g=0;c=!0}}c&&P(this,8,1,32,[a])};
n.Yb=async function(a,b,c,e,d,f,g,h,k,l){let m=a.tabId,p=a.g;var q=this.h[p];let r=this.o[m];if(b){var t=Mb(this,b);if(t=t&&t.I){if(!c&&a.B){let H=this.g[a.i];if(H)return H.postMessage([15,b,null,t[6],t[17],t[50],t[31],t[133],t[134]])}var u;b={};if(!e){if(!c||d==null){if(!a.h){c=a.ma;f="iframe";g=a.C;var z=!!c}if(!z){c=m;f=g=null;var x=!0}}a=this.xa(a,c,f,g);q=m==q.K&&!q.S&&(x||z||d)&&!r;!q||x||a.g||J.setTimeout(this.ea,3E3,p);var y=2;a.g=q?1:2;var S=(q?128:64)|(x?512:0);!h&&(u=this.g[m])&&(h=u.D)}h&&
(b[101]=h,b[128]=k);l&&(b[137]=l);await X(this,t,y||1,S||0,p,m,c,b);!y||x||r||ac(this,c,d)}}else e?(this.Z(c,!0),delete this.l[c]):m!=q.K||q.S||r||(d?ac(this,c,d,!0):bc(this,c))};function cc(a,b){let c=a.h[b];if(c&&c.g){var e=c.h,d=c.i;P(a,7,2,c.S?128:c.B?256:c.j?512:0,[b,Math.round((c.l+e)*d),Math.round((c.H+e)*d),Math.round((c.width-e-c.I)*d),Math.round((c.height-e)*d)])}}
function ac(a,b,c,e){let d=a.l[b];if(d&&d.g){var f=d.port;let g,h=256;d.g==2&&(e==null&&(g=a.h[f.g])&&(e=f.tabId==g.K&&!g.S),e?(h|=128,d.g=1):h|=64);(e=d.i)&&!c&&(c=f.o);let k,l,m,p,q,r;if(c){k=c[0];l=c[1];m=c[2]||k+1;p=c[3]||l+1;q=c[4];if(c=!e&&f.o)k+=c[0],l+=c[1],m=Math.min(m+c[0],c[2]),p=Math.min(p+c[1],c[3]);if(f=a.g[f.tabId])r=f.M}P(a,9,1,h,[b,k,l,m,p,q,r])}}
n.ea=function(a){var b=this.o;let c=this.g;var e=this.h;let d=a?[e[a]]:v(e);a=[];e={};for(var f of d)!f||f.S||f.da||b[f.K]||a.push(f.K);if(a.length)for(let g of v(this.l))g.g&&(b=g.port,f=b.tabId,a.includes(f)&&((f=b.h?b:c[f])&&f.update&&(f.update=!1,f.postMessage([14,!1])),g.h?b.h?b.postMessage([15,null,g.id]):Xb(this,b,null,e):ac(this,g.id,null,!0)))};function dc(a,b){let c=a.h,e;if(b=b==null?v(c):(e=c[b])?[e]:null)for(e of b)yb(a,e.K)}
function yb(a,b,c,e){e=e!=0;let d=c?0:2;c=c?32:64;for(let f of v(a.l))f.g&&f.port.tabId==b&&f.g!=d&&(e||f.h)&&(f.g=d,P(a,8,1,c,[f.id]))}function bc(a,b){let c=a.l[b];c&&c.g==1&&(c.g=2,P(a,8,1,64,[b]))}function ec(a,b,c,e){var d=a.Aa;let f=(d&b)!=((c?255:128)&b);a.Aa=c?d|=b:d&=~b;f&&(c=a.i[-32],b=a.i[-33],c=a.oa=c!=0&&(d&c)==c,d=a.Ea=b!=0&&(d&b)==b,a.Pa=(c||d)&&e||null)}
n.Ia=function(a,b,c,e,d){let f=this.h[a];if(f)if(f.da?e&&(J.clearTimeout(f.da),f.da=null):e||=-1,e>=0)f.o|=b,f.u|=c,e&&(f.da=J.setTimeout(this.Ia,e,a));else{b|=f.o;c|=f.u;f.o=f.u=f.da=null;if(b){for(let g of v(this.m))g.h&&g.g==a&&(g.update=!0);d?this.$(d):browser.windows.get(a,this.$);browser.tabs.query({windowId:a,active:!0},this.$)}if(c){if((a=this.h[a])&&!a.S&&!a.da&&(a=a.K,!this.o[a])){b=this.l;for(let g in b)c=b[g],c.g&&c.port.tabId==a&&c.g==1&&P(this,8,1,1152,[g])}}else this.ea(a)}};
n.$=function(a,b){browser.runtime.lastError;a instanceof Array&&(a=a.shift());if(a){var c=a.windowId||a.id,e=this.h[c];if(e){var d=!a.windowId;if(d){b&&(e.i=this.Da);var f=e.j=a.state=="minimized",g=e.B=a.state=="maximized";f||(e.width=a.width,e.height=a.height,e.m=a.left,e.v=a.top,f=e.S,a=e.S=a.state=="fullscreen",g=g&&-e.m,g>0&&g<=16&&g==-e.v&&(e.h=g),a==f||b||(a?dc(this,c):this.ea(c)))}else a.active&&(e.K=a.id),a.width&&(e.G=a.width),a.height&&(e.D=a.height);if(!e.j){a=e.width;let h=e.G;g=e.height;
f=e.D;let k=h>a||f>g;if(k||!h||!f){d||k&&browser.windows.get(c,this.$);return}d=a-h;a=d/2;a>=0&&a<=16?(e.h=a,e.l=e.I=0):(a=e.h,e.l=d-a*2);d=g-f-a*2;d>=(e.J?20:40)&&d<=150&&(e.H=d)}b||cc(this,c);return e}}};function xb(a,b){return a.o[b]?!0:(a=a.g[b])&&a.j?(a.j=!1,browser.tabs.reload(b),!0):!1}n.Vb=function(a,b,c,e){a.C=b;a.G=c;a.j&&!e&&(a.j=!1);a.ba==null&&Rb(this,a);this.ea(a.g);this.I>0&&a.h&&a.W==1&&(this.i[11]?.test((new URL(b)).hostname)||Vb(this))};
n.Xb=function(a,b,c,e,d){a.D=b;a.M=d;a=[a.l,a.tabId,a.g,e,d];e={};e[110]=b;e[128]=c;P(this,21,1,0,a,e)};
n.Zb=function(a,b,c,e,d){let f=a.tabId,g=this.g[L(f,c)];if(g){var h=g.o;g.ma=e;if(g.o=d){var k=a.o;k&&(d[0]+=k[0],d[1]+=k[1],d[2]=Math.min(d[2]+k[0],k[2]),d[3]=Math.min(d[3]+k[1],k[3]));if(h&&h.join()!=d.join()){h=this.g;a=L(a.tabId,"");c=a+c;for(let l in h)l.startsWith(a)&&(k=h[l],k.i==c&&g.postMessage([16,b,k.ba,k.ma]))}}if(!this.o[f]){ac(this,e,d);for(let l of v(this.l))l.port==g&&l.g&&l.h&&!l.i&&g.postMessage([15,null,l.id])}}};
function Xb(a,b,c,e){var d=a.g;c=[16,c];a=[b];for(let f;f=d[b.i];b=f){if(e)if(e[b.id])break;else e[b.id]=!0;a.push(f)}for(e=a.pop();b=a.pop();e=b)d=b.ma,c[2]=b.ba,c[3]=d,c[4]=d?null:b.C,c[5]=d?null:b.ca,e.postMessage(c)}function Yb(a,b,c){a=a.g;b=L(b,"");let e=0;for(let d in a)d.startsWith(b)&&(a[d].postMessage(c),e++);return e}
n.ua=function(a,b){let c={file:"content.js",runAt:"document_start",matchAboutBlank:!0};b?c.frameId=b:c.allFrames=!0;if(a instanceof Array)for(;b=a.shift();){if(!b.discarded)try{browser.tabs.executeScript(b.id,c,O)}catch(e){}}else if(b=a)try{browser.tabs.executeScript(b.id||b,c,O)}catch(e){}};function fc(a,b,c,e){c==null&&(c=b.A==a.X);P(a,6,2,17|(c?2048:1024)|(b.B?256:b.j?512:0),[b.A,b.g,b.width,b.height,b.m,b.v,b.i],{[117]:e})}
async function wb(a){var b=F(browser.windows.getAll({windowTypes:["normal","popup","app"]},G())),c=F(browser.tabs.query({active:!0},G()));[b,c]=await Promise.all([b,c]);let e={};if(c)for(let d of c)e[d.windowId]=d;for(let d of b)b=e[d.id],c=a.$(d,!0)||a.ab(d,!0,b),fc(a,c,d.focused,d.title||b&&b.title)}async function hc(a){await ic("system.display")&&(a.Ua=(await F(browser.system.display.getInfo(null,G())))[0].displayZoomFactor)}
n.xb=function(a){let b=a.sender.tab;if(b&&!(b.id<0)){a.name=a.name.split(":").shift();var c=a.id;c==null&&(c=a.id=this.Qb++);var e=b.id,d=a.name=="top";a.tabId=e;a.g=b.index<0?null:b.windowId;a.u=!0;a.A=!1;a.update=d;a.h=d;a.ba=d?0:a.sender.frameId;a.N=0;a.C=a.sender.url||d&&b.url||null;a.ca=null;this.m[c]=a;d&&(this.g[e]=a);a.C&&(a.W=Nb(this,(new URL(a.C)).hostname));a.onMessage.addListener(this.yb.bind(this,a));a.onDisconnect.addListener(this.va);Rb(this,a)}};
n.va=function(a){browser.runtime.lastError;if(a.u){a.u=!1;var b=L(a.tabId,a.ba),c=this.Y,e=this.l,d,f=this.ga,g=this.j,h;for(let k in c)c[k].port===a&&delete c[k];for(let k in e)if(d=e[k],d.port===a)this.Z(k),delete e[k];for(let k in f)f[k]===a&&delete f[k];for(let k in g)(h=g[k],h.port!==a||h.j)||delete g[k];this.Pa===a&&ec(this,255,!1);delete this.m[a.id];delete this.g[b];a.h&&delete this.g[a.tabId];a=this.G;for(let k in a)b==a[k].i&&delete a[k]}};
n.yb=function(a,b){let c=b.shift();b.unshift(a);switch(c){case 21:this.Vb.apply(this,b);break;case 24:this.Xb.apply(this,b);break;case 22:this.Zb.apply(this,b);break;case 23:this.Yb.apply(this,b);break;case 41:this.wb.apply(this,b);break;case 25:this.xa.apply(this,b);break;case 26:Wb(this,a.tabId,!0,!0,!1,a,b[1],b[2],b[3]);break;case 27:this.Pb.apply(this,b);break;case 28:this.Z(4294967295);break;case 29:this.Va.apply(this,b);break;case 30:this.Va.apply(this,b);break;case 31:this.qb.apply(this,b);
break;case 32:this.tb.apply(this,b);break;case 39:this.rb.apply(this,b);break;case 33:this.lb.apply(this,b);break;case 34:this.pb.apply(this,b);break;case 35:this.sb.apply(this,b);break;case 36:this.Nb.apply(this,b);break;case 37:this.Ab.apply(this,b);break;case 46:this.nb.apply(this,b)}};
n.Xa=function(a){let b=a.type,c=a.A;var e=a.j,d=a.g,f;if(b==1){let p=d[0];if(f=this.ra[p])b=f.type,delete this.ra[p]}switch(b){case 3:this.na>=0&&(this.na=-1,Ib(this));var g=d[5],h=d[6],k=d[4],l=d[8];this.R=d[0];jc(this,h);kc(this,g,a);lc(this);if(k||l)l=(k?k/96:1)*(l?l/100:1),this.Da=l<1.245?1:l,wb(this),this.Ua&&hc(this);Ob(this);break;case 4:g=this.i;(h=!!(d[3]&134217728))&&(J.idm=this);this.ya=h;this.A=!!(d[3]&2147483648);kc(this,d[2],a);lc(this);g[-6]=(e&64)>0;g[-10]=(e&1024)>0||!1;g[-5]=(e&
32)>0;g[-1]=(e&2)>0;g[-8]=(e&256)>0||c<2;g[-9]=(e&512)>0||c<2;g[-32]=d[0];g[-33]=d[1];g[12]=a[12];g[17]=a[17];g[23]=a[23];this.R<109&&(g[23]=Va);this.R<110&&(g[23]+=Wa);this.R<112&&(g[23]+=Xa);Y(g,a,1);Y(g,a,2);Y(g,a,3);Y(g,a,4);Y(g,a,10);Y(g,a,9,2);Y(g,a,11,2);Y(g,a,20);Y(g,a,21,1);mc(g,a,19);mc(g,a,18,1,1);a=this.i;g=this.qa={};browser.contextMenus.removeAll();for(d=1;d<nc.length;d++)h=nc[d],h[0]&&a[h[1]]&&(g[d]=browser.contextMenus.create({onclick:h[4].bind(this),title:oc(h[2]),contexts:h[3].split(","),
documentUrlPatterns:h[5]||Pa,enabled:!0}));this.ha||(this.ha=!0,ub(this,!0),this.L(1,browser.runtime.onConnect,this.xb),this.L(1,browser.proxy.settings.onChange,this.Za),browser.proxy.settings.get({},this.Za),this.L(1,browser.webNavigation.onCreatedNavigationTarget,this.ub),this.L(1,browser.webNavigation.onCommitted,this.Ya),this.L(1,browser.webNavigation.onHistoryStateUpdated,this.mb),(a=this.i[17])&&this.L(2,browser.webRequest.onBeforeRequest,this.Gb,{urls:a.split("|"),types:Ka},["blocking"]),Eb(this,
!0),browser.tabs.query({url:K},this.ua));break;case 18:g=d[0];d=d[1];f=I[d?-d:g];if(!f)break;d=this.aa[g]={};e=f[2];d.W=g;d.Tb=g==1?sa("lbhghor"):null;d.fb=f[0];d.cb=f[1];for(h in a)(h=parseInt(h))&&(h==102||h>110&&h<150)&&(d[h]=e.includes(h)?RegExp(a[h]):a[h]);for(k of e){var m=void 0;(l=d)[m=k]||(l[m]=Ja)}g=this.aa.map(ma(102)).filter(aa);this.Oa=RegExp("^https?://(?:"+g.join("|")+")","i");Y(d,a,101,2);break;case 5:pc(this,d[0],e,d[1]);break;case 6:if(e&4)break;pc(this,f.g[0],e,d[2],d[1]);break;
case 8:a=d[0];g=e&32;if(a==4294967295)Yb(this,this.v,[13,!1]),this.v=null;else if(a=this.l[a])a.g=g?0:2;break;case 11:d[0]==4294967295&&(Wb(this,this.v,!0,!0),this.v=null);break;case 12:try{let p=a.g[5];g=p==4?2:3;if(p==1||p==2){if(Pb(this,a)){let q=a[4];if(this.i[3].test(q))p==1?g=6:p=4;else if(this.i[-1]||this.i[4].test(q))g=6;a[8]|=256}if(g==3){let q=this.h[this.X];q&&this.o[q.K]&&(g=1)}}if(p!=4)X(this,a,g);else{switch(a.g[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=
a[31])}qc(this,a)}}catch(p){X(this,a,0)}break;case 13:a=f.g[0];h=f.g[5];d=d[1];k=d==3;if(h<=3)f.j&128?Zb(this,a,k):W(this,a,k);else if(h==5)if(d){if(d=(m=this.j[a])&&m.m){h=m.url;k=m.method;l=m.requestHeaders;if(a=m.i)(a=rc(a,l))?a=new Blob(a):k="GET";d.timeout=1E4;d.onreadystatechange=this.zb.bind(this,d,m.id);d.open(k,h,!0);for(g of l)h=g.name,k=h.toLowerCase(),k.startsWith("x-idm-")||(na(k)&&(h=`x-idm-${h}`),d.setRequestHeader(h,g.value));d.send(a)}}else sc(this,a);break;case 20:g=!a[123];a=[a.l];
d={};d[121]=this.B;P(this,1,2,g?2:4,a,d);break;case 24:tc(this,a);break;case 22:uc(d[0],d[1],a[131],a[130]);break;case 100:e&1&&P(this,100,1,0,[a.l],a);break;default:e&1&&P(this,1,2,0,[a.l])}};async function uc(a,b,c,e){Fa==null&&(Fa=await ic("notifications")||!1);Fa&&(browser.notifications.create(a.toString(),{type:"basic",title:e??"",message:c,iconUrl:"images/logo48.png"},O),b&&J.setTimeout(browser.notifications.clear,b*1E3,a.toString(),O))}
async function tc(a,b){let c=await R(b[6],!!(b.j&16));b=[b.l,c?c.length:0];let e={[51]:T(c)};P(a,1,2,c?2:4,b,e)}
async function qc(a,b){try{let g,h=b.i||b.g[2],k=b.g[8],l=a.l[k];if(l&&l.port)g=l.port;else if(h in a.m)g=a.m[h];else if(h=await Qb(a,b))g=a.m[h];else{let m=await F(browser.windows.getLastFocused(G()));if(m){let p=a.h[m.id];p&&(g=a.g[p.K])}}if(g){b.i=g.id;var c=a.h[g.g];if(c&&c.g){var e=a.g[g.tabId];e&&e.update&&(e.update=!1,e.postMessage([14,!0]));var d=Lb(a),f=[15,d.g,k];d.I=b;k||f.push(b[6],b[17],b[50],b[31],b[133],b[134]);g.h||Xb(a,g,d.g);g.postMessage(f)}else X(a,b,1)}else X(a,b,0)}catch(g){X(a,
b,0)}}async function X(a,b,c,e,d,f,g,h){c!=-1&&(e|=c==0?4:2,h||={},h[8]=b[8],d=[b.l,c,d,g,f,-1],b.j&32&&(c==3||c==2)&&(b=await R(b[6],!!(b.j&16)))&&(d[5]=b.length,h[51]=T(b)),P(a,1,2,e,d,h))}n.ub=function(a){Jb(this,a).g=!0};
n.Ya=function(a,b){var c=a.tabId,e=a.frameId;let d=a.url;var f=a.transitionType,g=a.frameType,h=a.documentId;let k=a.documentLifecycle=="prerender";this.P!=c||Ya(d)||(this.P=null);e&&k&&g=="outermost_frame"&&(e=a.frameId=0);f=f&&f.endsWith("_subframe");var l=!0;if(g=this.G[L(c,e)]){l=g.m;g.m=k?h:null;if(l&&l==h)return;h=g.v;l=!(d&&h&&(new URL(d)).hostname==(new URL(h)).hostname);g.v=d}else k&&(g=Jb(this,a),g.m=h);!f&&this.o[c]&&ub(this,l,c);if(h=this.g[L(c,e)])if(this.v&&(a=this.h[h.g])&&a.K==this.v&&
this.Z(4294967295),b){a:{b=h.C;c=new URL(b);e=new URL(d);if(c.origin==e.origin&&c.pathname==e.pathname)switch(Nb(this,c.hostname)){case 1:if(c.pathname=="/watch"&&c.searchParams.get("v")==e.searchParams.get("v")){b=!0;break a}break;case 4:if((c.pathname.startsWith("/p/")||c.pathname.startsWith("/reel/"))&&c.searchParams.get("img_index")==e.searchParams.get("img_index")){b=!0;break a}}b=d==b}if(!b){b=this.l;var m;for(let p in b)if(m=b[p],m.port===h)h.W==2||h.W==4?bc(this,p):(this.Z(p),delete b[p]);
h.N++;h.C=d;h.h&&(h.update=!0);h.postMessage([17,!0])}}else this.va(h,!0),f&&h.C=="about:blank"&&this.ua(c,e);else f&&d=="about:blank"?(Jb(this,a),this.ua(c,e)):g&&g.g&&(g.C||!b)&&(g.g=!1)};n.mb=function(a){return this.Ya(a,!0)};
n.ab=function(a,b,c){let e=a.id;c={A:e,width:a.width,height:a.height,m:a.left,v:a.top,i:this.Da,h:8,H:66,l:0,I:0,J:a.type=="popup"||a.type=="app",S:a.state=="fullscreen",B:a.state=="maximized",j:a.state=="minimized",K:c&&c.id,D:c&&c.height,G:c&&c.width,g:null,da:null};Object.setPrototypeOf(c,qb.prototype);this.h[e]=c;a.focused&&(this.X=e);b&&(browser.tabs.query({windowId:e,active:!0},this.$),browser.tabs.query({windowId:e,url:K},this.Wb),browser.tabs.query({windowId:e,url:K},this.ua));return c};
n.Wb=function(a){for(let b of a)Jb(this,0,b.id,!0,b.url)};n.bb=function(a){P(this,5,1,32,[a]);delete this.h[a]};n.Mb=function(a){if(a>0){let b=this.h[a];b&&(this.X=a,b.g||fc(this,b,!0),browser.windows.onBoundsChanged||browser.windows.get(a,this.$),xb(this,b.K))}else this.X=null};n.Lb=function(a){this.Ia(a.id,!0,!1,-1,a)};function pc(a,b,c,e,d){let f=a.h[b];f?(e&&(f.i=e),d&&(f.g=d),e=!!(c&128),f.S!=e&&(f.S=e)&&dc(a,b),(d||c&4096)&&cc(a,b)):a.bb(b)}
n.Fb=function(a,b,c){let e=c.active;c=c.windowId;let d=e&&this.h[c];d&&(d.g||fc(this,d));b.status=="complete"&&(a=this.g[a])&&!a.A&&(a.A=!0,e&&this.ea(c))};n.Eb=function(a){let b=this.g,c=this.G,e=L(a,"");this.P==a&&(this.P=null);let d=b[a];d&&this.va(d,!0);for(let f in b)f.startsWith(e)&&this.va(b[f],!0);for(let f in c)f.startsWith(e)&&delete c[f];delete this.o[a]};
n.Cb=function(a){let b=a.tabId;a=a.windowId;this.Aa=0;this.v&&this.Z(4294967295);var c=this.h[a];c&&(yb(this,c.K),c.K=b,(c=this.P)&&b!=c&&this.u&&(this.P=null,J.setTimeout(browser.tabs.remove,250,c)),browser.tabs.get(b,this.$),xb(this,b)||this.ea(a))};n.Db=function(a,b){b=b.newWindowId;for(let c of v(this.m))c.tabId==a&&(c.g=b);yb(this,a,!0)};
n.Va=function(a,b,c){if(a.h){let e=a.tabId;a=a.g;let d=this.h[a];this.v&&this.Z(4294967295);if(d&&d.K==e){let f=!1;b&&(d.G=b,f=!0);c&&(d.D=c,f=!0);yb(this,e,!1,f);this.Ia(a,f,!1,500)}}else a.ma&&(b=this.g[a.i])&&b.postMessage([16,null,a.ba,a.ma])};n.qb=function(a,b,c){(b=ua[b])&&ec(this,b,c,a)};n.tb=function(a,b,c){b==0&&ec(this,128,c,a)};n.rb=function(a,b,c,e){this.Ca=a.id;a.I=b;a.H=c;a.J=e};n.lb=function(){ec(this,255,!1)};
n.pb=function(a,b,c,e){var d=a.l;d&&(a=32,d=[d,c==null?(a|=16,-2):c],P(this,16,1,a,d,{[110]:b,[115]:e}))};n.Nb=function(a,b,c){if(a=this.j[b])P(this,16,1,48,[a.id,0],{[115]:c}),a.B=!1,a.Ga&&W(this,a)};n.nb=function(a,b,c,e){b!=null&&(a.O=b?1:-1);c!=null&&(a.v=c?1:e?2:-1)};n.Ab=function(a,b,c,e){P(this,19,2,0,[b,c,a.tabId,a.l],e)};n.zb=function(a,b){a.readyState==4&&(P(this,16,1,48,[b,0],{[115]:a.status==200?a.response:null}),sc(this,b))};
function sc(a,b){if(b=a.j[b]){var c=b.m;b.m=null;b.B=!1;b.Ga&&W(a,b);c&&c.abort()}}function vc(a,b){let c=a.i;if(b.v||a.o[b.tabId]||!c[-6])return 1;if(b.l)return 6;if(b.h&&c[-1])return 1;let e=b.wa,d=b.O=U(e.pathname);return c[9].test(e.hostname)||c[19].test(e.href)?1:(b.V&7)==2&&(b.J||c[-10])?e.pathname.endsWith("/")||c[21].test(e.pathname)?1:c[1].test(d)||a.A&&!c[20].test(d)?4:1:6}
function wc(a,b){let c=!b.g;if(b.l&&c)return 3;let e=a.i;var d=e[18];let f=e[1];var g=b.wa;let h=b.O,k=b.ia||(g.search?null:h),l=b.h,m=La.includes(b.type),p=!b.J;var q=!m&&d.exec(g.href);if(q){var r=d.$b,t=d.ac;let z=d.bc,x=d.cc;for(d=1;d<q.length;++d)if(q[d]){r=r[--d];if(r===null)break;var u=void 0;q=0;r.includes("G")&&(u=!0,q|=b.method=="GET");r.includes("P")&&(u=!0,q|=b.method=="POST");if(u&&!q)break;u=r.includes("V")|r.includes("A")|r.includes("C");r.includes("H")&&(b.U=!0);if((u?b.U:l?!r.includes("S"):
r.includes("X"))||p&&r.includes("D"))return 1;let y,S,H;if(q=x[d]){q=q.exec(g.href);if(!q)break;g=t[d];if(t=g.F)H=!0,S=q[t];if(t=g.T)H=!0,y=q[t]}y||=U(S)||r.includes("T")&&(H=!0,h)||z[d];if(u)return y&&(b.O=y),l||(b.h=!0),b.g=!0,6;if(c&&(y?f.test(y):!H))return b.N=16777216,4;break}}if(!c)return 6;if(k&&(m&&e[2].test(k)||l&&e[4].test(k)))return 1;if(a.O&&(b.J||e[-10])){if(l&&e[3].test(k))return 6;if((!l||a.A)&&k&&f.test(k))return b.N=8,4}return 6}
function xc(a,b){if(b.ga)return V(a,6,b),6;var c=b.statusCode;if(c!=200&&c!=206&&c!=304)return 1;var e=Z(b.o,"Content-Type"),d=Z(b.o,"Content-Disposition"),f=yc(e).toLowerCase();let g=yc(d).toLowerCase()=="attachment";c=b.h;var h=b.D;if(b.fa=h&&!g&&f=="text/html"){if(b.j){var k=Kb(a,b);k&&(k.j=!0);V(a,5,b)}return 1}if(c?b.v:b.g)return 1;if(a.A&&h&&g)return 4;let l,m,p,q,r,t;var u;let z;let x,y=a.i,S=b.port,H=b.wa;var ka=H.hostname;let xa=H.pathname,w=(d=zc(d,"filename")||zc(e,"name"))&&U(d);if(d){if(!w&&
!c)return 1;if(w&&(!c||w.length<=5)){var A=zc(e,"charset");x=!A||A=="utf-8"||A=="utf8";A=!0}}A||(d=xa.split("/").pop(),(w=b.O||U(d))&&w.toLowerCase()==f.split("/").pop()&&(A=!0));if(!A){e=y[10].test(f);var M=za[f];M&&(M=M.split("|"),w&&M.includes(w)?A=!0:c&&ab(w)?A=!0:(c?e:w)||(A=!0,z=e,w=M[0]));!A&&w&&(g&&h?A=!0:e?A=z=!0:M||$a(w)||(A=z=!0))}if(c){M=Nb(a,ka);h=a.aa[M];e=xa+H.search;switch(M){case 0:break;case 1:if(h[111].test(e))l=A=!0,w=null;else if(h[112].test(e))m=!0;else if(h[115].test(e)&&f==
"application/json")t=!0;else if(h[113].test(e)||h[114].test(e))p=!0;break;case 2:(ka=h[111].exec(e))&&(Za(f)||f=="text/html")?(f=ka[1]&&h[112].exec(S.C))&&ka[1]!=f[1]||(p=!0):h[114].test(e)?r=!0:g&&b.type=="image"&&w=="MP4"&&(u=!0);break;case 3:w=="M4S"&&(A=!0);ka==h[111]&&h[112].test(xa)&&Za(f)&&(p=!0);break;case 4:h[111].test(e)&&Za(f)&&(r=!0);break;case 5:h[111].test(e)&&f=="text/html"&&(r=!0);break;case 6:h[111].test(e)&&(p=!0);break;default:h[111].test(xa)&&(r=!0)}A&&(w=="M3U8"||w=="F4M"||w==
"MPD"?p=!0:w=="F4F"&&(d.endsWith("Seg1-Frag1")||d.endsWith("Seg1-Frag2")||d.includes("Seg1-Frag2_"))&&(q=!0));w=="ASF"&&((f=Z(b.o,"Content-Length"))&&parseInt(f)<=102400&&(u=!0),Z(b.o,"Server")=="DCLK-AdSvr"&&(u=!0))}if(u)return 1;A&&(c&&y[3].test(w)?l=!0:c&&y[4].test(w)?b.g=!0:!b.g&&y[1].test(w)&&(k=!0));if(l){let Fb,Gb;if(b.U)l=!1;else if(u=y[11])u.test(H.hostname)?l=!1:(Fb=a.g[b.tabId])&&(Gb=Fb.C)&&u.test((new URL(Gb)).hostname)&&(l=!1)}if(r||t)r&&S.O<0||t&&S.v<0?p=!0:m=b.B=!0;if(p||q)b.method!=
"POST"||b.i?(a=new XMLHttpRequest,a.responseType=q?"blob":"text",b.m=a,m=!0):m=!1;if(!k&&!l&&!m)return 1;A&&(b.ia=w);x&&(b.R=d);b.j|=m;b.N=l||m?256:16|(c?4096:0)|(z?8388608:0);return k?4:l?2:5}
function V(a,b,c,e,d,f){var g=c.url,h=c.V||Q(g);let k=c.requestHeaders,l=(h&7)==1;if(!d&&!k&&!e&&l)if(f===void 0){if(f=Z(k,"Cookie"),f==null)return R(g).then(y=>V(a,b,c,e,d,y||null))}else f=T(f);let m=d?d.id:c.id,p=c.port&&c.port.id,q=c.timeStamp,r=c.N,t=c.o,u=c.X,z=c.u,x=0;(z?z.length-z.replaceAll(".","").length:0)==3?r|=33554432:(z?z.length-z.replaceAll(":","").length:0)>2&&(r|=4194304);h&16&&(r|=2097152);c.method=="POST"&&(r|=512);d&&(x|=129);b<4&&e&&(x|=1);c.j&&c.m&&(x|=1);c.j&&b!=5&&(x|=32);
c.h&&(x|=16);c.I&&(x|=8192);c.D&&(x|=c.G?2048:4096);h=[m,p,C(q),c.statusCode,h&7,b,c.tabId,c.frameId];g={[6]:Sb(g,l&&a.U),[12]:c.statusLine,[17]:c.ca,[4]:c.ia,[100]:c.R,[127]:c.la,[129]:c.ha,[2]:c.u,[122]:a.B,[8]:r,[11]:Ac(k),[13]:Ac(t),[18]:Ac(u)};c.i&&(g[14]=rc(c.i,k));c.M&&(g[19]=rc(c.M,u));k||(g[50]=Bc(a,c),g[51]=f,g[54]=navigator.userAgent);if(!c.fa||!c.G)if(f=a.g[c.tabId])g[7]=f.C;return!!P(a,13,1,x,h,g,e)}
function Cc(a,b,c,e){var d=a.O?new XMLHttpRequest:null;let f=V(a,b,c,d);d&&((d=f&&parseInt(d.getResponseHeader("x-idm-status")))?f=d==3:f=V(a,b,c));if(f){if(!e){c.H=!0;return}return W(a,c,!0)}c.g=!0}
function W(a,b,c){let e=a.j;if(E(b)||(b=e[b])){var d=b.id,f=b.statusCode>0;if(c){if(b.D||b.I){let h=f||!b.requestHeaders;if((f=Kb(a,b))&&f.g&&b.G)browser.tabs.remove(b.tabId);else if(h&&!b.I)var g={redirectUrl:"javascript:void(0)"};else h&&((g=a.M)||(g=b.port,a=f&&!f.u,g=new URL(g&&g.C||b.url),g=Sa+(a?"back=1":`host=${g.hostname}`)),g={redirectUrl:g})}g||={cancel:!0};b.H=!0}(a=b.resolve)&&c!==void 0&&(b.resolve=b.reject=null,a(g||{}));if(c=b.reject)b.resolve=b.reject=null,c();if(b.La||b.m||b.B)return b.Ga=
!0,g;delete e[d];b.A&&delete e[b.A];return g}}n.Gb=function(a){var b=new URL(a.url);if(b.search.startsWith("?d=")){let c=this.g[a.tabId];this.ka("idmreg:"+b.href.substr(b.protocol.length),null,c&&c.C);W(this,a.requestId);(b=Kb(this,a))&&b.g&&a.type=="main_frame"&&browser.tabs.remove(a.tabId);return{redirectUrl:Sa+"register=1"}}};n.hb=function(a){if(!(a.tabId<0||a.initiator==Ua||this.ya||a.url.startsWith(Sa)&&a.type.endsWith("_frame")||a.url.startsWith(Ta)&&a.type=="main_frame"))return{cancel:!0}};
n.$a=function(a){var b=a.type,c=a.tabId,e=a.frameId;if(!(c<0&&a.initiator==Ua)){var d=a.url,f=a.method,g=Q(d);if(g&&(f=="GET"||f=="POST")&&d!=this.M){e&&a.frameType=="outermost_frame"&&(e=a.frameId=0);var h=a.id=a.requestId;h=this.j[h];var k=this.Ea,l=f=="POST",m=b=="image",p=b=="other",q=!p&&c<0&&e<0,r=c>0&&b.endsWith("_frame");if((f=q?null:this.g[L(c,e)])||r||q||p||h){r&&Jb(this,a,null,!1);if(!k&&l&&a.requestBody){l=a.requestBody;var t=l.raw;if(t)for(let u=0;u<t.length&&(t[u].bytes||(t=null));u++);
if(!(t||l.formData||l.error))return}if((l=this.Ca)&&(t=f?f.id==l&&f:this.m[l])&&d==t.H){p=t.I;if(l=t.J)a.R=l,a.ia=U(l);f||=t;this.Ca=null}l=new URL(d);l.hash="";a.wa=l;a.V=g;a.l=this.oa;a.v=k;a.G=r&&b=="main_frame";a.D=r;a.I=p;a.aa=q;a.h=q||Ma.includes(b);a.g=m;a.j=this.Oa.test(d);a.i=a.requestBody;a.port=f;a.J=g&8||this.ta[g];c<0&&(a.tabId=null);e<0&&(a.frameId=null);h&&(a.id=h.id,a.port=f=h.port,a.l=h.l,a.v=h.v,a.ca=h.ca||h.url,a.X=h.X||h.requestHeaders,a.M=h.M||h.i);if(a.h&&!m){b=this.ga;c=b.Rb;
e=c.indexOf(d);if(e>=0)c.splice(e,1);else for(;c.length>=30;)delete b[c.shift()];b[d]=f;c.push(d)}switch(a.action=vc(this,a)){case 1:a.g=!0;case 6:d=this.j;f=a.id;d[f]!==a&&(d[f]=a);break;case 4:return Cc(this,1,a)}}}}};
n.Hb=function(a){var b=this.j[a.requestId];if(b){var c=b.requestHeaders=a.requestHeaders;b.timeStamp=a.timeStamp;if(!b.H){if(b.aa&&!b.port&&(a=Z(c,"Referer")))for(var e of v(this.m))if(e.C==a){b.port=e;break}if(b.port&&b.port.m&&b.type=="xmlhttprequest"){var d,f;e=0;for(d of c)if(d.name.toLowerCase()=="accept"&&(f=db(d.value)))break;else e++;if(f){a=f[3];let h=f[4];var g=!0;f[1]||f[5]?d.value=f[1]+(f[5]&&f[2]||"")+f[5]:c.splice(e--,1);if(a=="pxr"||a=="pfm")b.A=h,this.j[h]=b}}if(b.method=="POST"&&
(!b.i||b.i.error&&Z(c,"Content-Length")>0))return W(this,b);switch(b.action=wc(this,b)){case 1:b.g=!0;break;case 4:return Cc(this,1,b);case 3:return Cc(this,3,b)}if(g)return{requestHeaders:c}}}else if(a.tabId<0&&a.type=="xmlhttprequest"&&a.initiator==Ua){b=a.requestHeaders;c={};for(d=0;d<b.length;d++)f=b[d],e=f.name.toLowerCase(),e.startsWith("x-idm-")?c[e.substr(6)]=g=!0:e=="origin"&&f.value==Ua&&(c[e]=g=!0);if(g){for(g=0;g<b.length;g++)d=b[g],f=d.name.toLowerCase(),c[f]?b.splice(g--,1):f.startsWith("x-idm-")&&
(d.name=d.name.substr(6));return{requestHeaders:b}}}};
n.Jb=function(a){let b=this.j[a.requestId];if(b){var c=b.port,e=b.type,d=b.statusLine=a.statusLine,f=b.statusCode=a.statusCode||parseInt(d.split(" ",2).pop()),g=a.responseHeaders;if(b.H||f==204&&d.includes(" IDM "))return W(this,b,!0);b.u=a.ip;b.Y=a.timeStamp;b.ha=C(a.timeStamp-b.timeStamp);b.o=g;b.ga=gb(f);if(e=="image"&&(d=Z(g,"Content-Type"))&&d.toLowerCase().startsWith("image"))return W(this,b);Z(g,"Client-Protocol")=="quic"?b.V|=16:(d=Z(g,"Alternate-Protocol"))&&d.endsWith(":quic,p=0")&&Z(g,
"Transfer-Encoding")!="chunked"&&(b.V|=16);if(c&&e=="xmlhttprequest"&&!b.A&&c.v==2){e=oa.map(Z.bind(J,g));e.unshift(b.url);e=e.join("|");d=5381;f=e.length;for(let h=0;h<f;h++)d=d*33+e.charCodeAt(h)>>>0;c=b.A=`${c.id}-${d}`;this.j[c]=b}switch(b.action=xc(this,b)){case 1:return W(this,b);case 4:return Cc(this,2,b,a);case 3:return Cc(this,3,b,a)}if(b.B)return g||=[],g.push({name:"x-idm-request-id",value:b.id.toString()}),{responseHeaders:g}}};
n.Kb=function(a){let b=this.j[a.requestId];if(a.type.endsWith("_frame")&&(a.statusCode==200||a.statusCode==304)){let c=Kb(this,a);c&&(c.C=a.url,c.ca=c.A)}b&&(b.u||(b.u=a.ip),b.action==2?V(this,4,b):b.action==5&&V(this,5,b),W(this,b))};n.Ib=function(a){W(this,a.requestId)};
async function vb(a){var b={url:Ea.homepage_url},c=F(browser.storage.local.get(null,G()));b=F(browser.cookies.getAll(b,G()));let e=F(browser.extension.isAllowedIncognitoAccess(G()));[c,b,e]=await Promise.all([c,b,e]);a.Sa=c.version;a.pa=c.silent;a.J=c.lastupt;a.Na=e;a.J>Date.now()&&(a.J=null);c=c.client;let d;if(b)for(let f of b)switch(f.name){case "idmwebext_cid":d=parseInt(f.value)}jc(a,null,c,d);a.za()}
function jc(a,b,c,e){(b||=c||e)&&b!=a.N&&(a.N=b,c||browser.storage.local.set({client:b}),e||browser.cookies.set({url:Ea.homepage_url,name:"idmwebext_cid",value:String(b),expirationDate:2147483647}))}
function Ob(a){a.P&&(browser.tabs.remove(a.P),a.P=null);if(a.Ta){var b=!a.u,c=!a.Na,e=a.U,d=a.sa,f=a.Sa,g=a.Sb;if(b){if(a.la&&a.pa)return}else a.Ta=!1,g!=f&&g&&browser.storage.local.set({version:g}),a.pa&&(a.pa=!1,browser.storage.local.set({silent:!1}));f!=null&&(g==f||d&&f&&!e)||(g=Ta+"current="+escape(g),f&&(g+="&previous="+escape(f)),d&&(g+="&manager="+(d?[d>>24&255,d>>16&255,d>>8&255,d&255].join("."):"")),b&&(g+="&error=1"),c&&(g+="&incognito=1"),e&&(g+="&update=1"),browser.tabs.create({url:g+
"&msedge=1"},function(h){h&&(this.P=h.id)}.bind(a)))}}function kc(a,b,c){b==null&&(b=fb(c[13]))&&(b=b[1]<<24|b[2]<<16|b[3]<<8);a.sa=b>>>0}function lc(a){a.U=a.sa<103417600;a.sa<103424E3?a.I=a.J?a.J+C(D()*240+480)*6E4:Date.now():(a.I=a.J=null,browser.storage.local.remove("lastupt"))}
function Vb(a,b){var c=Date.now();if(c>a.I||b&&!a.U)browser.storage.local.set({lastupt:a.J=c}),a.I>0&&(a.I=c+C(D()*240+480)*6E4),c="idmdwnlmfv4://idmreg://"+D().toString(36).substr(2),b?a.ka(c):J.setTimeout(a.ka,C(D()*5E3+5E3),c)}function Bc(a,b){a=a.G;b=L(b.tabId,b.frameId);var c;do b=(c=a[b])&&c.i,c=c&&c.C,c=="about:blank"&&(c=null);while(!c&&b);return c}function Ub(a){a=browser.i18n.getMessage(a);window.alert(a)}
n.L=function(a,b,c){if(b!=null){var e=da(arguments);this.Ja.push(e);b.addListener.apply(b,e.slice(2))}};n.Ka=function(){let a=arguments.length?da(arguments):null,b=this.Ja;for(let c=0;c<b.length;c++){if(a&&!a.includes(b[c][0]))continue;let e=b.splice(c--,1).pop(),d=e.splice(0,2).pop();d.removeListener.apply(d,e)}};function oc(a){return browser.i18n.getMessage(a)||a}
function Sb(a,b){let c=a.lastIndexOf("#");c>a.indexOf("?")&&a[c+1]!="!"&&(a=a.substr(0,c));!b||a.startsWith("idmdwnlmfv")||bb(a)||(a=`${"idmdwnlmfv"}4://${a}`);return a}function Q(a,b){a=a.split(":",1).shift().toLowerCase();a=va[a]||0;return b?a&7:a}function U(a){return(a=eb(a))?a[1].toUpperCase():""}function R(a,b){a={url:a};b&&(a.session=!1);return F(browser.cookies.getAll(a,G())).catch(()=>null)}
function T(a){if(!E(a))return a;let b=[];for(let c of a)b.length&&b.push("; "),b.push(c.name,"=",c.value);return b.join("")}function Ac(a){if(!a||!a.length)return null;let b=[];for(let c of a)b.push(c.name,": "),c.value!=null?b.push(c.value):c.binaryValue&&b.push(new Uint8Array(c.binaryValue)),b.push("\r\n");return b}function Z(a,b){if(!a)return null;b=b.toLowerCase();for(let c of a)if(c.name.toLowerCase()==b){if(c.value!=null)return c.value;if(c.binaryValue)return ha(c.binaryValue)}return null}
function zc(a,b){if(!a)return null;let c,e;a=a.split(";");for(b=b.toLowerCase();a.length;){var d=a.shift();let g=d.indexOf("=");if(g>0){var f=d.slice(0,g).trim().toLowerCase();let h=f.endsWith("*");if(h)f=f.slice(0,-1).trimRight();else if(e)continue;if(f==b){f=d.substr(g+1).trim();d=f.length-1;if(f[0]=='"'?f[d]=='"':f[0]=="'"&&f[d]=="'")f=f.slice(1,d);if(h&&f.includes("'")){if(f=f.split("'",3),h=f.shift().toLowerCase(),f=f.pop(),((d=h=="utf-8"||h=="utf8")||!e)&&(c=Dc(f))&&(e=h,d))break}else c=Dc(f)}}else g<
0&&c==null&&d.trim().toLowerCase()==b&&(c="")}return c}function yc(a){const b=/[;,]/;return(a&&=a.split(b,1).shift().trim())&&!a.includes("=")&&Dc(a)||""}function Dc(a){try{return a&&decodeURIComponent(a)}catch(b){return unescape(a)}}
function rc(a,b){let c;var e;let d=[];if(c=a.raw)for(e of c){var f=e.bytes;if(f)d.push(f);else return null}else if(e=a.formData)if(b=ca(b)?Z(b,"Content-Type"):b,(a=yc(b).toLowerCase())&&a!="application/x-www-form-urlencoded")if(a=="multipart/form-data"){var g=zc(b,"boundary");g||="----WebKitFormBoundary"+D().toString(36).substr(2);for(f in e)for(let h of e[f])d.push("--",g,'\r\nContent-Disposition: form-data; name="',f,'"\r\n\r\n',h??"","\r\n");d.push("--",g,"--\r\n")}else return null;else for(g in e){f=
encodeURIComponent(g).replaceAll("%20","+");for(let h of e[g])h=h instanceof ArrayBuffer?escape(ha(new Uint8Array(h))):h==null?"":encodeURIComponent(h),d.length&&d.push("&"),d.push(f,"=",h&&h.replaceAll("%20","+"))}else return null;return d.length?d:null}function mb(a){let b=a.length,c=b,e=0;for(;e<c;){let d=a.charCodeAt(e++);d>=128&&(d>=2048?(b+=2,d-55296&64512||e++):b++)}return b}
function Ec(){let a=Da=="llbjbkhnmlidjebalopleeepgdfgcpec"&&"ngpampappnmepgilojfohadhhmbhlaek";browser.management.get(a||"llbjbkhnmlidjebalopleeepgdfgcpec",function(b){browser.runtime.lastError;b&&b.enabled&&browser.management.setEnabled(a||Da,!1)})}function Fc(a,b,c){c?c.readyState==4&&(jb[a]=btoa(c.responseText)):(c=new XMLHttpRequest,c.responseType="text",c.onreadystatechange=Fc.bind(null,a,b,c),c.open("GET",browser.runtime.getURL(b)),c.send())}
function Y(a,b,c,e){if(b=b[c]||void 0){b=b.replace(/^\|+|\|+(?=\||$)/g,"").replace(/\./g,"\\.");b=e==1?b.replace(/\?/g,"[^/\\\\]").replace(/(^|[^*])\*(?!\*)/g,"$1[^/\\\\]*").replace(/\*\*/g,".*?"):e==3?b.replace(/(?<![*?])\*(?!\*)/g,"[^/]*").replace(/\?\*/g,"\\?.*").replace(/\*\*/g,".*?"):b.replace(/\?/g,".").replace(/\*/g,".*?");e==2&&(b=b.replace(/(^|\|)([^|]+?)~/g,"$1(?:$2\\.)?").replace(/(^|\|)~/g,"$1(?:.*?\\.)?"));b="^(?:"+b+")$";try{b=RegExp(b,e==1?"":"i")}catch(d){b=null}}a[c]=b||Ja}
function mc(a,b,c,e,d){b=b[c];let f=[],g=[],h=[],k=[];if(b)try{b=b.replace(/^\|+|\|+(?=\||$)|\*+(?=\*)/g,"").replace(/[.?+(){}[\]]/g,"\\$&").replace(/\*(?=[^:/|&]*:\/\/)/g,"\\w%%").replace(/(:\/\/[^:/]*?)~/g,"$1(?:\\b[^./]+\\.)?").replace(/\\\?(?=\||$)/g,"(?:$&.%%)?");if(e){for(var l=b.replace(/(^|\|)(?:([A-Z]+)?(?:#(\w+))?!)?[^|]+/g,"$1$2|$3").split("|");l.length;){var m=l.shift();f.push(cb(m)?m:null);g.push(l.shift())}b=b.replace(/(^|\|)[\w#]+!/g,"$1")}if(d){let p=b.replace(/(^|\|)(?:(?=[^|]+?<[A-Z]:.*?>)|[^|]+)/g,
"$1").split("|");l=/<([A-Z]):(.*?)>/g;m={F:"[^/\\?#&;]%%",T:"[^/\\?#&;.]%%"};for(let q,r=0;p.length;++r)if(q=p.shift()){let t={},u=["^"],z="";for(let x,y=1;x=l.exec(q);++y)t[x[1]]=y++,z=RegExp.rightContext,u.push(RegExp.leftContext,"(",x[2].replace(/\*/g,m[x[1]]||".%%?"),")");u.push(z,"$");h[r]=t;k[r]=RegExp(u.join("").replace(/\*/g,".*?").replace(/%%/g,"*"))}b=b.replace(l,"(?:$2)")}b=b.replace(/\*/g,".*?").replace(/%%/g,"*");b=e||d?RegExp("^(?:("+b.replace(/\|/g,")|(")+"))$"):RegExp("^(?:"+b+")$")}catch(p){b=
null}a[c]=b||=RegExp("(?!)");e&&(b.$b=f,b.bc=g);d&&(b.ac=h,b.cc=k)}function ic(a){return browser.runtime.lastError?null:F(browser.permissions.request({permissions:[a]},G()))}function O(a){browser.runtime.lastError;a;!0}
const nc=[null,[!0,-8,"menu_download_link","link,image,video",N.prototype.Ba],[!0,-8,"menu_download_link","page,frame,editable",N.prototype.Ba,Qa],[!0,-8,"menu_download_selected","selection",N.prototype.Ma],[!0,-9,"menu_download_all","page,frame,editable",N.prototype.Ma],[!0,-8,"menu_download_item","link",N.prototype.Ba,["chrome://downloads/*"]]],Ab=oc("tooltip_title"),Cb=oc("tooltip_disabled"),Db=oc("tooltip_error"),Bb="\n"+oc("tooltip_text");
(async function(){var a=F(browser.runtime.getPlatformInfo(G())),b;navigator.userAgentData&&(b=navigator.userAgentData.getHighEntropyValues(["fullVersionList","uaFullVersion"]));var c=F(browser.management.get("clhiejnehegdfknplplojohghjaklbae",G())).catch(()=>null);[a,b,f,c]=await Promise.all([a,b,f,c]);if(a&&a.os!="win")return zb(!1);Ec();a=navigator.userAgent;var e=a.match(/\s(?!(?:Chrome|Firefox|Gecko|Safari)\/)([A-Z]\w+)(?:\/(\d+(?:\.\d+){0,3}))?\b(?!.*\)\s+\S)/),d=a.match(/\s(Chrome|Firefox)\/(\d+(?:\.\d+){0,3})\b/);
a=d?d[1]:"UNKNOWN";var f=e?e[1]:a;d=d&&d[2]||"0.0";e=e&&e[2]||d;navigator.brave&&(f="Brave");c&&(f="Epic",Ca=!0);if(E(b)){if(c=b.uaFullVersion)e=c;if(b=b.fullVersionList)for(let g of b)if(c=g.version)switch(g.brand){case "Chromium":a="Chrome";parseInt(c)==parseInt(d)?d=c:(f="UNKNOWN",e=c);break;case f:e=c}}c=d.split(/\D+/);Aa=`${a}/${d}`;Ba=`${f}/${e}`;new N;Fc(1,"debug.js");Fc(2,"document.js")})();
