this.pagejs=e=>{(()=>{"use strict";function t(e,t,n,o,r,s,i){try{var a=s(e,i),l=jt(a,"value")}catch(e){return void n(e)}jt(a,"done")?t(l):gn(new pn((e=>e(l))),o,r)}function n(e){const n=function(){var n=this,o=arguments;return new pn((function(r,s){function i(e){t(l,r,s,i,a,fn,e)}function a(e){t(l,r,s,i,a,mn,e)}var l=At(e,n,o);i(void 0)}))};return Ut(n,"apply",(function(e,t){return At(n,e,t)})),n}const o=["chrome"],r="vault"in e;if(r&&void 0===e.vault)throw"Invalid vault"
;const s=e.vault=e.vault||(e=>{const t=Object.call,n=t.bind(t),o=Object.assign,r=Object.getOwnPropertyDescriptor,s=Object.getPrototypeOf,i=e=>o({__proto__:null},e),a=s(function*(){}()),l=s(Uint8Array.prototype);return i({sourceWindow:e,cSO:i,F_c:n,F_a:Object.apply,F_b:Object.bind,F_tS:Function.toString,A_fE:[].forEach,A_so:[].some,A_sh:[].shift,A_j:[].join,A_iO:[].indexOf,A_iA:Array.isArray,O_a:o,O_k:Object.keys,O_v:Object.values,O_dP:Object.defineProperties,O_dPy:Object.defineProperty,
O_hOP:Object.hasOwnProperty,O_gOPN:Object.getOwnPropertyNames,O_gOPD:r,O_gOPDs:Object.getOwnPropertyDescriptors,O_gPO:s,O_tS:{}.toString,J_p:JSON.parse,J_s:JSON.stringify,M_f:Math.floor,M_r:Math.random,M_m:Math.max,M_mi:Math.min,N_tS:(0).toString,N_MSI:Number.MAX_SAFE_INTEGER,P_t:Promise.prototype.then,P_c:Promise.prototype.catch,P_co:Promise.prototype.constructor,G_n:a.next,G_t:a.throw,R_rABS:FileReader.prototype.readAsBinaryString,R_rAT:FileReader.prototype.readAsText,
R_r:r(FileReader.prototype,"result").get,R_enq:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.enqueue:null,R_cl:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.close:null,S_fCC:String.fromCharCode,S_sl:"".slice,S_su:"".substr,S_sp_nr:"".split,S_iO:"".indexOf,S_tr:"".trim,S_r_nr:"".replace,S_rA_nr:"".replaceAll,S_cCA:"".charCodeAt,S_tLC:"".toLowerCase,S_tUC:"".toUpperCase,Y_tST:Symbol.toStringTag,Y_unsc:Symbol.unscopables,
USP_tS:URLSearchParams.prototype.toString,D_pFS:DOMParser.prototype.parseFromString,U_cOU:URL.createObjectURL,U_rOU:URL.revokeObjectURL,X_o:XMLHttpRequest.prototype.open,X_pSD:XMLHttpRequest.prototype.DONE,X_pSH:XMLHttpRequest.prototype.HEADERS_RECEIVED,X_pSL:XMLHttpRequest.prototype.LOADING,X_pSO:XMLHttpRequest.prototype.OPENED,X_pSU:XMLHttpRequest.prototype.UNSENT,X_s:XMLHttpRequest.prototype.send,D_n:Date.now,I_tS:e=>""+e,E_r:Element.prototype.remove,E_s:Element.prototype.setAttribute,
E_rA:Element.prototype.removeAttribute,D_cS:r(Document.prototype,"currentScript").get,D_gRS:r(Document.prototype,"readyState").get,D_cE:Document.prototype.createElementNS,D_gEBT:Document.prototype.getElementsByTagName,M_rT:r(MouseEvent.prototype,"relatedTarget").get,C_d:r(CustomEvent.prototype,"detail").get,P_p:r(PageTransitionEvent.prototype,"persisted").get,C_pA:CustomEvent.prototype.AT_TARGET,M_d:MutationObserver.prototype.disconnect,W_aEL:addEventListener,W_rEL:removeEventListener,
FD_e:FormData.prototype.entries,TA_b:r(l,"buffer").get,TA_sa:Uint8Array.prototype.subarray,parseInt,parseFloat,CustomEvent,CompositionEvent,KeyboardEvent,MouseEvent,MutationObserver,console:Object.assign({},console),Error,Uint8Array,Blob,ReadableStream,Number,String,Proxy,Window,FileReader,DOMParser,XMLHttpRequest,Function,RegExp,Promise,encodeURIComponent,decodeURIComponent,encodeURI,decodeURI,escape,unescape,atob,btoa,setTimeout,clearTimeout,setInterval,clearInterval,postMessage,dispatchEvent,
alert,prompt,confirm,close,getElementById:e.Document.prototype.getElementById,createEvent:e.Document.prototype.createEvent,createElement:e.Document.prototype.createElement})
})(e.unsafeWindow),{cSO:i,F_c:a,F_a:l,F_b:c,F_tS:u,A_fE:d,A_so:g,A_sh:p,A_j:f,A_iO:m,A_iA:v,O_a:_,O_k:h,O_v:b,O_dP:y,O_dPy:M,O_hOP:w,O_gOPN:E,O_gOPD:S,O_gOPDs:G,O_gPO:L,O_tS:R,J_p:I,J_s:O,M_f:C,M_r:x,M_m:k,M_mi:T,N_tS:P,N_MSI:A,P_t:D,P_c:U,P_co:$,G_n:j,G_t:F,R_rABS:V,R_rAT:N,R_r:q,R_enq:B,R_cl:X,S_fCC:H,S_sl:W,S_su:K,S_iO:J,S_sp_nr:z,S_tr:Y,S_rA_nr:Q,S_cCA:Z,S_tLC:ee,S_tUC:te,Y_tST:ne,Y_unsc:oe,D_pFS:re,D_cS:se,D_gRS:ie,D_cE:ae,D_gEBT:le,E_r:ce,E_s:ue,E_rA:de,C_pA:ge,M_d:pe,C_d:fe,P_p:me,M_rT:ve,U_cOU:_e,U_rOU:he,USP_tS:be,X_o:ye,X_s:Me,X_pSD:we,X_pSH:Ee,X_pSL:Se,X_pSO:Ge,X_pSU:Le,D_n:Re,I_tS:Ie,W_aEL:Oe,W_rEL:Ce,FD_e:xe,TA_b:ke,TA_sa:Te,parseInt:Pe,parseFloat:Ae,console:De,encodeURIComponent:Ue,decodeURIComponent:$e,encodeURI:je,decodeURI:Fe,escape:Ve,unescape:Ne,atob:qe,btoa:Be,postMessage:Xe,dispatchEvent:He,alert:We,prompt:Ke,confirm:Je,close:ze,getElementById:Ye,createEvent:Qe,createElement:Ze,CustomEvent:et,CompositionEvent:tt,KeyboardEvent:nt,MouseEvent:ot,MutationObserver:rt,Uint8Array:st,FileReader:it,DOMParser:at,XMLHttpRequest:lt,Function:ct,RegExp:ut,Blob:dt,ReadableStream:gt,Number:pt,String:ft,Proxy:mt,Window:vt}=s,_t=e,{unsafeWindow:ht,unsafeThis:bt}=_t,yt=a,Mt=l,wt=h,Et=b,St=_,Gt=y,Lt=M,Rt=E,It=S,Ot=L,Ct=G||(e=>{
const t=Dt({});for(const n in e)t[n]=It(e,n);return t}),xt=v,kt=C,Tt=x,Pt=k,At=(e,t,n)=>yt(Mt,e,t,n),Dt=i,Ut=(e,t,n)=>(Lt(e,t,Dt({value:n,configurable:!0,enumerable:!0,writable:!0})),e),$t=(e,t)=>nn(e,t)?e[t]:void 0,jt=(e,t)=>{const n=It(e,t);return n?Dt(n).value:void 0},Ft=(e,t)=>{const n=(e,t,o)=>{const r=It(e,t),s=r?Dt(r):void 0;let i;return s?s.enumerable?s.value:void 0:--o>=0&&(i=Ot(e))?n(i,t,o):void 0};return n(e,t,5)},Vt=e=>{const t=(t,...n)=>At(e,t,n);return Ut(t,"wrappedJSObject",e),t
},Nt=()=>e=>Vt(e),qt=Vt(c),Bt=e=>{const t=(e,n)=>{let o;if(null===e)o="null";else{const r=typeof e;if("object"===r){if(n){if(-1!=en(n,e))throw"Converting circular structure to JSON";Ut(n,n.length,e)}else n=[e];if(xt(e)){let r="";for(let o=0;o<e.length;o++){let s;s=nn(e,o)?$t(e,o):Ft(e,o);const i=t(s,n);r+=`${o?",":""}${void 0===i?"null":i}`}o=`[${r}]`}else{let r="";tn(wt(e),(o=>{const s=t(e[o],n);void 0!==s&&(r+=`${r?",":""}${O(o)}: ${s}`)})),o=`{${r}}`}n.length-=1}else{
if("bigint"===r)throw"Do not know how to serialize a BigInt";o=O(e)}}return o};return t(e)},Xt=e=>{const t=I(e),n=e=>{const t=[];for(let n=0;n<e.length;n++)Ut(t,n,o(e[n]));return t},o=e=>{if(null===e);else if("object"==typeof e){if(xt(e))return n(e);{const t={};return tn(wt(e),(r=>{const s=e[r];let i;i="object"==typeof s?xt(s)?n(s):o(s):s,Ut(t,r,i)})),t}}return e};return o(t)},Ht=Nt()(g),Wt=(e,t,n,...o)=>{const r=o||[],s=zt(e,0,t),i=zt(e,t,n),a=zt(e,t+n);let l=Qt([],s);return l=Qt(l,r),
l=Qt(l,a),Dt({result:l,removed:i})},Kt=Nt()(p),Jt=(e,t)=>{const n=[];return tn(e,(e=>{t(e)&&Zt(n,e)})),n},zt=(e,t,n)=>{const o=e.length;let r=t||0;if(r>=o)return[];r<0&&(r=Pt(0,o+r));let s=void 0===n?o:n;s<0&&(s=Pt(0,o+s)),s>o&&(s=o);const i=Dt({});for(let t=r;t<s;t++)i[t]=jt(e,t);return Et(i)},Yt=Nt()(f),Qt=(e,...t)=>{let n=e.length;const o=Dt(e);for(let e=0;e<t.length;e++){const r=t[e],s=xt(r)?r:[r];for(let e=0;e<s.length;e++)o[n+e]=jt(s,e);n+=s.length}return Et(o)},Zt=(e,t)=>{
let n=e.length||0;return Ut(e,n,t),n++,e.length=n},en=Nt()(m),tn=Nt()(d),nn=Nt()(w),on=Nt()(z),rn=Nt()(W),sn=Vt(R),an=Ot({}),ln=e=>{const t=Dt(e),n=Rt(t);for(let e=0;e<n.length;e++){const o=n[e],r=t[o];null!==r&&"object"==typeof r&&Ot(r)===an&&(t[o]=ln(r))}return t},cn=e=>{const t=on(sn(e)," ");return rn(Yt(zt(t,1)," "),0,-1)},un=(Nt()(u),Nt()(P)),dn=A,gn=Nt()(D),pn=(Nt()(U),
qt($,Ot((async()=>{})()))),fn=Nt()(j),mn=Nt()(F),vn=Nt()(V),_n=Nt()(N),hn=Nt()(q),bn=B?Nt()(B):B,yn=X?Nt()(X):X,Mn=H,wn=Nt()(K),En=Nt()(J),Sn=Nt()(Y),Gn=(Nt()(Q||function(e,t){return Yt(on(this,e),t)}),Nt()(Z)),Ln=Nt()(ee),Rn=Nt()(te),In=ne,On=oe,Cn=Vt(re),xn=Vt(se),kn=Vt(ie),Tn=(Vt(ae),Vt(le),Vt(ce)),Pn=(Vt(ue),Vt(de)),An=ge,Dn=Vt(ve),Un=Vt(fe),$n=(Vt(me),pe&&Nt()(pe),Vt(be)),jn=Vt(xe),Fn=Vt(ke),Vn=Nt()(Te),Nn=(Nt()(ye),we),qn=Ee,Bn=Se,Xn=Ge,Hn=Le,Wn=(Nt()(Me),
Re),Kn=mt,Jn=pt,zn=et,Yn=nt,Qn=ot,Zn=st,eo=rt,to=dt,no=function(e,t){return jt(e,t)},oo=Dt({addEventListener:!1,Array:!0,Blob:!0,close:!1,CustomEvent:!0,Date:!0,DOMParser:!0,Error:!0,Event:!0,FileReader:!0,KeyboardEvent:!0,location:!0,Math:!0,MouseEvent:!0,Number:!0,Object:!0,ReadableStream:!0,removeEventListener:!1,Uint8Array:!0,XMLHttpRequest:!0}),ro=((()=>{const e=Dt({getElementById:Ye,createEvent:Qe,createElement:Ze,dispatchEvent:He,addEventListener,removeEventListener}),t=Dt({})
;tn(wt(e),(n=>{try{const o=e[n];t[n]=function(...e){return At(o,ht.document,e)}}catch(e){t[n]=((e,t)=>{if(so.error(`Tampermonkey sandbox preparation ${t?"("+t+") ":""}failed. This usually is caused by a third-party extension.`,e),t)return()=>{}})(e,`document.${n}`)}}))})(),Dt({top:!0,location:!0}));e.bridges=e.bridges||Dt({});const so=e.console=e.console||Dt({}),io=Dt({addEventListener:qt(Oe,ht),removeEventListener:qt(Ce,ht)});tn(wt(ro),(async e=>{if(!io[e])try{const t=ht[e];if(null==t)return
;io[e]=t}catch(e){}})),tn(wt(oo),(async e=>{if(!io[e])try{let t=jt(ht,e);if(void 0===t&&(bt===ht||void 0===(t=jt(bt,e))))return;const n=oo[e];io[e]=!1===n&&"function"==typeof t?qt(t,bt):t}catch(e){}}));const ao=e=>{let t,n=[],o=!1;e((e=>{if(!o){if(n.length){const t=n;n=[],tn(t,(t=>t(e)))}else t=e;o=!0}}));const r=Dt({then:e=>(o?e(t):Zt(n,e),r)});return r},lo=({sendPrefix:e,listenPrefix:t,send:o,onMessage:r})=>{if(void 0===o||void 0===r)throw"invalid args";let s,i,a=1
;const l=Dt({}),c=Dt({}),u=e=>{e&&(s=e)},d=e=>{const t=++a;return c[a]=e,t};r(((n,r)=>n==`${t}_${s}`?(t=>{const{m:n,r,a,n:u}=t;if(l[n]&&(tn(l[n],(e=>e(a))),delete l[n]),"message.response"==n){if(null==r)throw"Invalid Message";((e,t,n)=>{let o;e&&(o=c[e])&&(o(t,n),delete c[e])})(r,a,u)}else if(i){const t=r?(t,n)=>{o(`${e}_${s}`,Dt({m:"message.response",a:t,r,n}))}:()=>{};i(Dt({method:n,args:a,node:u}),t)}})(r):null));const g=Dt({init:(p=n((function*(e){s?u():u(e)})),function(e){
return p.apply(this,arguments)}),refresh:()=>null,switchId:e=>{s&&g.cleanup(),u(e)},send:(t,n,r,i)=>ao((a=>{let l,c;"function"!=typeof r&&null!==r?(l=r,c=i):c=r,o(`${e}_${s}`,Dt({m:t,a:n,r:c?d(c):null,n:l})),a()})),sendToId:(t,n,r)=>{o(`${e}_${t}`,Dt({m:n,a:r,r:null}))},once:(e,t)=>{l[e]||(l[e]=[]),Zt(l[e],t)},setMessageListener:e=>{i=e},cleanup:()=>null});var p;return g},co=({sendPrefix:e,listenPrefix:t,cloneInto:o})=>{const s=e=>o?o(e,ht.document):e,i=Dt({});let a,l,c=1;const u=Dt({})
;let d=!1,g=[];const p=()=>{b=ht.document.documentElement,d=!1;const e=g;g=[],tn(e,(e=>{d||M()?Zt(g,e):e()}))};let f;const m=e=>{const t=++c;return u[c]=e,t},v=(e,t)=>{const{m:n,a:o,r,n:i}=t,{m:a,c:l}=((e,t,n)=>{let o,r;return n?(r=new Qn(e,Dt({relatedTarget:n})),o=new zn(e,Dt({detail:s(t)}))):o=new zn(e,Dt({detail:s(t)})),Dt({m:r,c:o})})(e,Dt({m:n,a:o,r}),i);a&&At(He,ht,[a]),At(He,ht,[l])},_=t=>{const n=(e=>{if("MouseEvent"===cn(e)){const t=Dn(e);if(!t)throw"Invalid MouseEvent";return void(f=t)
}const t=ln(Un(e));return f&&(t.n=f,f=void 0),t})(t);if(!n)return;const{m:o,r,a:s,n:c}=n;if(i[o]&&(tn(i[o],(e=>e(s))),delete i[o]),"unlock"==o)v(`${e}_${l}`,Dt({m:"unlocked",a:void 0,r:null})),p();else if("unlocked"==o)p();else if("message.response"==o){if(null==r)throw"Invalid Message";((e,t,n)=>{let o;e&&(o=u[e])&&(o(t,n),delete u[e])})(r,s,c)}else if(a){const t=r?(t,n)=>{v(`${e}_${l}`,Dt({m:"message.response",a:t,r,n}))}:()=>{};a(Dt({method:o,args:s,node:c}),t)}},h=e=>{e&&(l=e),
l&&io.addEventListener(`${t}_${l}`,_,!0)};let b,y;const M=()=>{if((()=>{const e=ht.document.documentElement;return b||(b=e),b!==e})()){if(y){const e=y;y=void 0,e(ht.document)}return!0}},w=e=>(b=ht.document.documentElement,ao(function(){var t=n((function*(t){if(y=t,r&&!e&&(yield null,M()))return;const n=new eo((()=>{M()&&n.disconnect()}));n.observe(ht.document,Dt({childList:!0}))}));return function(e){return t.apply(this,arguments)}}())),E=Dt({init:(S=n((function*(t,n){l?h():h(t),w(n).then((()=>{
d=!0,E.refresh(),v(`${e}_${l}`,Dt({m:"unlock",a:void 0,r:null}))}))})),function(e,t){return S.apply(this,arguments)}),refresh:()=>{const e=l;e&&(E.cleanup(),E.init(e,!0))},switchId:e=>{l&&E.cleanup(),h(e)},send:(t,n,o,r)=>ao((s=>{let i,a;"function"!=typeof o&&null!==o?(i=o,a=r):a=o,M();const c=()=>{v(`${e}_${l}`,Dt({m:t,a:n,r:a?m(a):null,n:i})),s()};d?Zt(g,c):c()})),sendToId:(t,n,o)=>{v(`${e}_${t}`,Dt({m:n,a:o,r:null}))},setMessageListener:e=>{a=e},once:(e,t)=>{i[e]||(i[e]=[]),Zt(i[e],t)},
cleanup:()=>{l&&(io.removeEventListener(`${t}_${l}`,_,!0),l=void 0)}});var S;return E},uo=()=>un(Wn()+19831206*Tt()+1,36),go=function(){var e=n((function*(e){yield null,e()}));return function(t){return e.apply(this,arguments)}}(),po=()=>{const e=xn(ht.document);e&&(Pn(e,"nonce"),Tn(e))},fo=(()=>{const{console:t,bridges:n}=e,o=Dt({});let r;const s=(e,n,r,s)=>{let a,l=[],c=[],u=[],d=[];const g=()=>{c=[],u=[],d=[],v(),M=null,delete o[n]},p=t=>{e.send("port.message",Dt({response_id:n,value:t}))
},f=e=>{s&&"messageId"in e&&Zt(l,e),p(e)},m=(e,t=!0)=>{a=e,t&&p(e)},v=()=>{a=void 0},_=Dt({addListener:e=>{Zt(c,e)}}),h=Dt({addListener:e=>{Zt(u,e)}}),b=Dt({addListener:e=>{Zt(d,e)}}),y=()=>{g(),e.send("port.message",Dt({response_id:n,disconnect:!0}))};let M=Dt(r?{postMessage:f,connectMessage:m,stopReconnecting:v,onMessage:_,onDisconnect:h,onReconnect:b,disconnect:y}:{postMessage:f,onMessage:_,onDisconnect:h,disconnect:y});return o[n]=Dt({message:e=>{if(s&&(e=>"ack"in e)(e)){
const{messageId:n,refreshId:o}=e;((e,n)=>{if(n)return;if(!e)return void t.warn("PortMessaging: no message id in ack message");if(a&&a.messageId===e)return;let o=-1;Ht(l,((t,n)=>t.messageId===e&&(o=n,!0))),-1!==o?(tn(zt(l,0,o),(e=>t.warn(`PortMessaging: message ${e.messageId} was not ack'ed!`,e))),l=zt(l,o+1)):t.warn(`PortMessaging: no one is waiting for ${e}`)})(n,o)}c&&tn(c,(t=>t(e)))},disconnect:()=>{if(a&&r)return i(r,n),m(a),s&&tn(l,(e=>p(e))),void(d.length&&tn(d,(e=>e())))
;u.length&&tn(u,(e=>e())),g()}}),M},i=(e,t)=>{n.first.send("port.message",Dt({response_id:t,connect:!0,destination:e}))};return Dt({message:(e,n)=>{let i;if(e.connect){if(!e.destination||!e.response_id)throw"invalid message";r&&r(e.destination,s(n,e.response_id))}else{if(!e.response_id)throw"invalid message";if(!(i=o[e.response_id]))return void t.warn("ports: unknown id",e.response_id,e);e.disconnect?i.disconnect():i.message(e.value)}},connect:function(e,t,o){const r=uo();return i(e,r),
s(n.first,r,t?e:void 0,o)},onConnect:Dt({addListener:e=>{r=e}})})})(),{bridges:mo}=e,vo=Dt({});let _o=!0,ho=[];go((()=>{_o=!1;const e=mo.first;tn(ho,(({m:t,i:n})=>e.send("console",[t,n]))),ho=[]})),tn(["debug","log","info","warn","error"],(e=>{Ut(vo,e,((...t)=>{const n=(e=>{const t=[];return tn(e,(e=>{Zt(t,(e=>Bt(e))(e))})),t})(t);if(_o)return Zt(ho,Dt({m:e,i:n}));mo.first.send("console",[e,n])}))}))
;const bo=Dt(Ct(ht.console)),yo=Dt({}),Mo=["GM.backgroundControl"],wo=["GM_addElement","GM.addElement","GM_addStyle","GM.addStyle"],Eo=["GM_cookie","GM.cookie"],So=["GM_listValues","GM.listValues","GM_getValue","GM.getValue","GM_getValues","GM.getValues","GM_addValueChangeListener","GM.addValueChangeListener","GM_removeValueChangeListener","GM.removeValueChangeListener","GM_setValue","GM.setValue","GM_setValues","GM.setValues","GM_deleteValue","GM.deleteValue","GM_deleteValues","GM.deleteValues"],Go=["GM_download","GM.download"],Lo=["GM_getResourceText","GM.getResourceText","GM_getResourceURL","GM.getResourceUrl"],Ro=["GM_getTab","GM.getTab","GM_getTabs","GM.getTabs","GM_saveTab","GM.saveTab"],Io=["GM_log","GM.log"],Oo=["GM_notification","GM.notification"],Co=["GM_openInTab","GM.openInTab"],xo=["GM_audio","GM.audio"],ko=["GM_registerMenuCommand","GM.registerMenuCommand","GM_unregisterMenuCommand","GM.unregisterMenuCommand"],To=["GM_setClipboard","GM.setClipboard"],Po=["GM_xmlhttpRequest","GM.xmlHttpRequest"],Ao=["window.close"],Do=["window.focus"],Uo=["window.onurlchange"],$o=["GM_webRequest","GM.webRequest"],jo=Dt({
encode:e=>Ne(Ue(e)),decode:e=>$e(Ve(e))}),Fo=Dt({encode:e=>{let t="";for(let n=0;n<e.length;n++)t+=Mn(255&Gn(e,n));return Be(t)},decode:e=>qe(e)}),Vo=e=>{const t=new Zn(e.length);for(let n=0;n<e.length;n++)t[n]=Gn(e,n);return Fn(t)},No=e=>ao((t=>{const n=new to([e]);qo(n).then(t)})),qo=(e,t)=>ao((n=>{const o=new io.FileReader;o.onload=()=>{n(hn(o))},o.onerror=e=>{so.warn(`unable to decode data ${e}`),n("")},t?_n(o,e,t):vn(o,e)})),{bridges:Bo}=e;let Xo=0,Ho=0
;const Wo=Dt({}),Ko=Dt({}),Jo=function(e,t,n,o){const r=()=>{Wo[n]&&(At(e,this,o),delete Wo[n])};"function"==typeof e&&(Wo[n]=e,0===t?go((()=>r())):Bo.first.send("setTimeout",Dt({t:t||1}),(()=>r())))},zo=function(e,t,n,o){if("function"==typeof e){const r=Ko[n]=fo.connect("setInterval");r.onMessage.addListener((()=>{Ko[n]&&At(e,this,o)})),r.onDisconnect.addListener((()=>Yo(n))),r.postMessage(Dt({method:"setInterval",t:t||1}))}},Yo=e=>{const t=Ko[e];t&&(t.disconnect(),delete Ko[e])
},Qo=(e,t,...n)=>{const o=uo();return Jo(e,t,o,n),o},Zo=e=>{(e=>{delete Wo[e]})(e)},er=e=>Yo(e),tr=(e,t,...n)=>{const o=++Ho;return t=Pt(t,1),Jo(e,t,o,n),o},nr=(e,t,...n)=>{const o=++Xo;return t=Pt(t,1),zo(e,t,o,n),o};let or;const rr=e=>{if(void 0===or){or=!0;const t="keepAlive",n=fo.connect(t,!0),o=io.location.href;n.onMessage.addListener((()=>{})),n.connectMessage(Dt({messageId:uo(),method:t,id:e,url:o})),n.onDisconnect.addListener((()=>{r&&er(r),r=null}));let r=((e,t,...n)=>{const o=uo()
;return zo(e,t,o,n),o})((()=>{or?n.postMessage(Dt({messageId:uo(),method:"keepAlive",url:o})):r&&(n.disconnect(),er(r),r=null)}),2e4)}},sr=t=>{const{contextId:o,bridges:r}=e,s=r.first,i=Dt({}),a=(e,t)=>Ht(t,(t=>-1!=en(e,t))),l=e=>function(){return new pn((t=>t(At(e,this,arguments))))},c=(e,t)=>function(...n){const o=[];if(void 0!==t)for(let e=0;e<t;e++)Zt(o,no(n,e)||void 0);return new pn((t=>{At(e,this,Qt(o,[t]))}))},u=(e,t)=>{let n;const o=new pn(((o,r)=>{
const s=Dt({}),i=t.onload,a=t.ontimeout,l=t.onerror;tn(wt(t),(e=>{s[e]=t[e]})),s.onerror=function(e){l?(o(e),At(l,this,arguments)):r(e)},s.ontimeout=function(e){a?(o(e),At(a,this,arguments)):r(e)},s.onload=function(e){o(e),i&&At(i,this,arguments)};const c=e(s).abort;!0===n?c():n=c}));return Ut(o,"abort",(()=>{"function"==typeof n?n():n=!0})),o};return Dt({of:e=>{const r=e.script,d=(()=>{const e=a(r.grant,To),t=(e,t,n)=>{s.send("setClipboard",Dt({content:e,info:t,id:o,uuid:r.uuid
}),n?()=>n():null)};return Dt({GM_setClipboard:e?Dt({value:t}):void 0,"GM.setClipboard":e?Dt({get:()=>c(t,2)}):void 0})})(),g=(()=>{let t=[];const n=e.storage;let s=0,i=null;const c=a(r.grant,So),u=(e,t)=>{if("string"!=typeof e)return t;{const n=wn(e,0,1);switch(e=wn(e,1),n){case"b":return"true"===e;case"n":return Jn(e);case"x":try{return jo.decode(Fo.decode(e))}catch(t){return e}case"o":try{return Xt(e)}catch(e){so.log(`values: parseValueFromStorage: ${e}`)}return t;case"u":return;default:
return e}}},d=(e,n,o,r)=>{n!=o&&tn(t,(t=>{if(t&&t.key==e&&t.cb)try{t.cb(e,u(n),u(o),r)}catch(t){so.warn(`values: change listener of "${e}" failed with: ${t.message}`)}}))},g=(e,t)=>{i&&i.postMessage(Dt({messageId:uo(),method:"saveStorageKey",uuid:r.uuid,key:e,value:n.data[e],removed:t,id:o,ts:n.ts}))};c&&(rr(o),i=fo.connect("values",!0,!0),i.onDisconnect.addListener((()=>{so.warn("values: port disconnected"),i=null})),i.onMessage.addListener((e=>{if("ack"in e)return;const{storage:t,removed:o}=e
;if(!t)return;const r=t,s=wt(r);o&&Zt(s,o),tn(s,(e=>{const t=n.data[e],o=r[e];void 0===o?delete n.data[e]:n.data[e]=o,d(e,t,o,!0)}))})),i.connectMessage(Dt({messageId:uo(),method:"addStorageListener",uuid:r.uuid,id:o})));const p=(e,t)=>u(n.data[e],t),f=e=>{const t=Dt({});let o=e;if(o||(o=wt(n.data)),xt(o))tn(o,(e=>{e in n.data&&(t[e]=p(e))}));else{const e=o;tn(wt(e),(n=>{t[n]=p(n,e[n])}))}return t},m=()=>wt(n.data),v=(e,n)=>{const o=++s,r=Dt({id:o,key:e,cb:n});return Zt(t,r),o},_=e=>{
t=Jt(t,(t=>t.id!==e))},h=(e,t)=>{const o=n.data[e];n.ts=Wn(),n.data[e]=(e=>{const t=typeof e;let n,o=wn(t,0,1);switch(t){case"object":try{n=o+Bt(e)}catch(e){return void so.log(e)}break;case"function":case"symbol":case"bigint":o="u",n=o+void 0;break;case"string":case"number":case"undefined":case"boolean":n=o+e;break;default:n=t}return n})(t),g(e),d(e,o,n.data[e],!1)},b=e=>{const t=wt(e);tn(t,(t=>{h(t,e[t])}))},y=e=>{const t=n.data[e];n.ts=Wn(),delete n.data[e],g(e,!0),d(e,t,n.data[e],!1)},M=e=>{
xt(e)?tn(e,(e=>{y(e)})):so.warn("values: removes: names is not an array")};return Dt({GM_getValue:c?Dt({value:p}):void 0,"GM.getValue":c?Dt({get:()=>l(p)}):void 0,GM_getValues:c?Dt({value:f}):void 0,"GM.getValues":c?Dt({get:()=>l(f)}):void 0,GM_listValues:c?Dt({value:m}):void 0,"GM.listValues":c?Dt({get:()=>l(m)}):void 0,GM_addValueChangeListener:c?Dt({value:v}):void 0,"GM.addValueChangeListener":c?Dt({get:()=>l(v)}):void 0,GM_removeValueChangeListener:c?Dt({value:_}):void 0,
"GM.removeValueChangeListener":c?Dt({get:()=>l(_)}):void 0,GM_setValue:c?Dt({value:h}):void 0,"GM.setValue":c?Dt({get:()=>l(h)}):void 0,GM_setValues:c?Dt({value:b}):void 0,"GM.setValues":c?Dt({get:()=>l(b)}):void 0,GM_deleteValue:c?Dt({value:y}):void 0,"GM.deleteValue":c?Dt({get:()=>l(y)}):void 0,GM_deleteValues:c?Dt({value:M}):void 0,"GM.deleteValues":c?Dt({get:()=>l(M)}):void 0})})(),p=(()=>{const e=a(r.grant,Uo),t=(()=>{let e=[],t=null;var s;return Dt({register:(n,s)=>ao((i=>{
if(n&&!(en(e,n)>-1))if(Zt(e,n),t)i();else{let n=i;rr(o),t=fo.connect("onurlchange",!0),t.onMessage.addListener((t=>{if(n&&(n(),n=void 0),"ack"in t)return;const{url:o}=t;if(!o)return;const r=Dt({url:o});tn(e,(e=>{At(e,s,[r])}))})),t.connectMessage(Dt({messageId:uo(),method:"observeUrlChanges",uuid:r.uuid,id:o}))}})),unregister:(s=n((function*(n){let o;n&&(o=en(e,n))>-1&&(e=Wt(e,o,1).result),yield null,t&&0===e.length&&(t.disconnect(),t=null)})),function(e){return s.apply(this,arguments)})})})()
;return Dt({"window.onurlchange":e?Dt({value:t}):void 0})})(),f=(()=>{const e=a(r.grant,xo);let t=[],i=null;const l=(e,n)=>{if(Zt(t,e),i)n&&n();else{let e=n;rr(o),i=fo.connect("onaudiostatechange",!0),i.onMessage.addListener((n=>{if(e&&(e(),e=void 0),"ack"in n)return;const o=Dt({});"muted"in n&&(o.muted=n.muted),"audible"in n&&(o.audible=n.audible),tn(t,(e=>{try{At(e,void 0,[o])}catch{}}))})),i.connectMessage(Dt({messageId:uo(),method:"observeAudioStateChanges",uuid:r.uuid,id:o}))}},c=(e,o)=>{
n((function*(){let n;e&&(n=en(t,e))>-1&&(t=Wt(t,n,1).result),yield null,i&&0===t.length&&(i.disconnect(),i=null),o&&o()}))()},u=(e,t)=>Dt({action:e,uuid:r.uuid,details:t}),d=Dt({setMute:(e,t)=>{s.send("audio",u("setMute",e),t?e=>{"error"in e?(so.warn("audio: "+e.error),t(e.error)):"success"in e?t():(so.warn("audio: unexpected response"),t("unexpected response")),t()}:null)},getState:e=>{s.send("audio",u("getState",void 0),e?t=>{"error"in t?(so.warn("audio: "+t.error),e()):"muted"in t?e(Dt({
isMuted:!!t.muted,muteReason:t.muted?t.muted:void 0,isAudible:t.audible})):(so.warn("audio: unexpected response"),e())}:null)},addStateChangeListener:(e,n)=>{if(e&&!(en(t,e)>-1))return l(e,n)},removeStateChangeListener:c});return Dt({GM_audio:e?Dt({get:()=>{const e=(e,...t)=>At(d[e],void 0,t);return tn(wt(d),(t=>{Ut(e,t,d[t])})),e}}):void 0,"GM.audio":e?Dt({get:()=>{const e=Dt({});return tn(wt(d),(n=>{e[n]=e=>{return o=n,r=e,new pn(((e,n)=>{if("setMute"==o){const t=r;d[o](t,(o=>{o?n(o):e(t)}))
}else if("getState"==o)d[o]((t=>{e(t)}));else if("addStateChangeListener"==o){const o=r;if(!o||en(t,o)>-1)return n();l(o,(()=>e()))}else"removeStateChangeListener"==o?c(r,(()=>e())):n("unknown method")}));var o,r}})),e}}):void 0})})(),m=(()=>{const e=a(r.grant,Lo),t=e=>{for(let t=0;t<r.resources.length;t++){const n=r.resources[t];if(n.name==e){if(n.error)so.warn("@resource: "+n.error);else try{if("string"==typeof n.content)return jo.decode(n.content)}catch(e){}return""}}return null},n=e=>{
for(let t=0;t<r.resources.length;t++){const n=r.resources[t];if(n.name==e){if(n.error)so.warn("@resource: "+n.error);else if("string"==typeof n.content){try{return`data:${n.meta||"application/octet-stream"};base64,${Fo.encode(n.content)}`}catch(e){}return n.url}return""}}return null};return Dt({GM_getResourceText:e?Dt({value:t}):void 0,"GM.getResourceText":e?Dt({get:()=>l(t)}):void 0,GM_getResourceURL:e?Dt({value:n}):void 0,"GM.getResourceUrl":e?Dt({get:()=>l(n)}):void 0})})(),v=(()=>{
const e=a(r.grant,Ro),t=(e,t)=>{s.send("tabs",Dt({action:"set",uuid:r.uuid,tab:e}),t?()=>t():null)},n=e=>{s.send("tabs",Dt({action:"get",uuid:r.uuid}),e?t=>{e(t||Dt({}))}:null)},o=e=>{s.send("tabs",Dt({action:"list",uuid:r.uuid}),e?t=>{e(t||Dt({}))}:null)};return Dt({GM_saveTab:e?Dt({value:t}):void 0,"GM.saveTab":e?Dt({get:()=>c(t,1)}):void 0,GM_getTab:e?Dt({value:n}):void 0,"GM.getTab":e?Dt({get:()=>c(n)}):void 0,GM_getTabs:e?Dt({value:o}):void 0,"GM.getTabs":e?Dt({get:()=>c(o)}):void 0})
})(),_=(()=>{const e=a(r.grant,Po),s=e=>{const s=ln(e);let a=!1,l=()=>{a=!0};const c=(e,t)=>{t=t||Dt({}),e&&Qo((()=>{St(t,i),At(e,t,[t])}),1)},u=s.url;"object"==typeof u&&u.href&&(s.url=u.href);const d=(e,t)=>{const o=cn(e);if("Blob"===o||"File"===o){const n=e;qo(n).then((e=>{t(Dt({type:o,value:e,meta:n.type,name:n.name,lastModified:n.lastModified}))}))}else if("ArrayBuffer"===o)No(e).then((e=>{t(Dt({type:"Blob",value:e,meta:"application/octet-stream"}))}));else if("Uint8Array"===o){
const n=Fn(e);No(n).then((e=>{t(Dt({type:"Blob",value:e,meta:"application/octet-stream"}))}))}else if("FormData"===o){const o=jn(e),r=[],s=function(){var e=n((function*(){const e=o.next();if($t(e,"done"))t(Dt({type:"FormData",value:r}));else{const t=$t(e,"value"),n=no(t,0),o=no(t,1);d(o,(e=>{Zt(r,Dt({name:n,value:e})),s()}))}}));return function(){return e.apply(this,arguments)}}();s()}else if("URLSearchParams"===o)t(Dt({type:"URLSearchParams",value:$n(e)}));else if("Array"===o||"Object"===o){
const n=e;let r,s,i=0,a=0;if("Object"===o){const e=wt(n);s=t=>t<e.length?e[t]:null,r=Dt({})}else s=e=>e<n.length?e:null,r=[];const l=()=>{const e=s(i);null===e?t(Dt({type:o,value:r})):d(n[e],(t=>{r[e]=t,i++,a++<1024?l():(a=0,Qo(l,1))}))};l()}else t(Dt({value:e,type:"raw"}))},g=(e,t,n,o,r)=>{let s;if(n)"stream"==o&&(s=n);else if("arraybuffer"==o)s=t||Vo(e||"");else if("blob"==o)s=new io.Blob([t||Vo(e||"")],Dt({type:r}));else if("json"==o)s=Xt(e||"");else if("document"==o){
const t=new io.DOMParser,n=["application/xhtml+xml","application/xml","image/svg+xml","text/html","text/xml"];let o=no(on(r||"text/xml",";"),0);-1==en(n,o)&&(o="text/xml");try{s=Cn(t,e||"",o)}catch(e){s=null}}else s=e||(t?(e=>{let t="";const n=new Zn(e);for(let e=0;e<n.length;e+=32687)t+=At(Mn,null,Vn(n,e,e+32687));return t})(t):"");return s};return(e=>{if(s.url){const t=wn(s.url,0,5);if(-1!=en(["data:","blob:"],t))return e()}if(!s.data)return e();d(s.data,(t=>{s.binary&&(t.type="Blob"),
s.data=t,s.data_type="typified",e()}))})((()=>{if(a)return a=!1,void c(s.onabort);let e,i,u,d=fo.connect("xhr"),p=[],f=!1;const{method:m,url:v,redirect:_,headers:h,cookie:b,binary:y,nocache:M,revalidate:w,proxy:E,timeout:S,context:G,responseType:L,overrideMimeType:R,anonymous:I,cookiePartition:O,fetch:C,user:x,password:k,data:T,data_type:P}=s,A=Dt({method:m,url:v,redirect:_,headers:h,cookie:b,binary:y,nocache:M,revalidate:w,proxy:E,timeout:S,responseType:L,overrideMimeType:R,anonymous:I,
cookiePartition:O,fetch:C,user:x,password:k,data:T,data_type:P});if(A.headers){const e=A.headers;tn(wt(e),(t=>{"cookie"===Ln(t)&&(A.cookie=`${e[t]}`,delete e[t])}))}const D=Dt({messageId:uo(),method:"xhr",details:A,callbacks:Dt({onloadstart:!!s.onloadstart,onload:!!s.onload,ondone:!!s.onloadend,onreadystatechange:!!s.onreadystatechange,onerror:!0,onabort:!!s.onabort,ontimeout:!!s.ontimeout,onprogress:!!s.onprogress,onuploadprogress:!(!s.upload||!s.upload.onprogress),onpartial:!0}),id:o,
location:io.location.href,uuid:r.uuid,no_blob:"js"==t.sandboxMode});let U,$,j,F;d.postMessage(D);const V=L?Ln(L):"";let N,q=0,B=0;const X=function(){var t=n((function*(t){if(t&&(u||void 0!==e||void 0!==i)){if(R?F=R:t&&(F=(e=>{const t=Dt({});return e&&tn(on(e,"\n"),(e=>{const n=on(e,":");if(n.length<2)return;const o=no(n,0);if(!o)return;const r=Yt(zt(n,1),":");t[Ln(Sn(o))]=Sn(r||"")})),t})(t.responseHeaders)["content-type"]),U=e,u)j=u.stream;else if(i){const e=i;if($=e.buffer,
-1==en(["blob","arraybuffer"],V)&&!U){let t;Ht([F,e.type],(e=>t=((e,t,n,o)=>{const r=En(e,"charset=");if(-1==r)return;const s=wn(e,r+8),i=En(s,";");return-1==i?o&&o.optionalEnd?s:void 0:wn(e,r+8,i)})(Ln(e||""),0,0,Dt({optionalEnd:!0}))));const n=new to([$]);N=qo(n,t),U=yield N}N=void 0}else N&&(yield N);e=i=void 0}if(U||j||$){t.responseType=L,tn(["response_data"],(e=>delete t[e]));const e=Dt({response:()=>g(U,$,j,V,F||"binary/octet-stream"),responseText:()=>g(U,$,j,"text",F),
responseXML:()=>g(U,$,j,"document",F||"text/xml")});tn(wt(e),(n=>{Lt(t,n,Dt({get(){try{return e[n]()}catch(e){so.warn(`${m}:`,e)}}}))}))}}));return function(e){return t.apply(this,arguments)}}(),H=[],W=function(){var e=n((function*(e){e&&Zt(H,e);{const e=Kt(H);e&&e()}}));return function(t){return e.apply(this,arguments)}}();"stream"===V&&W(n((function*(){u=yield ao((e=>{const t=new io.ReadableStream(Dt({start:n=>{Qo((()=>e(Dt({stream:t,ctrl:n}))),0)},cancel:()=>{u&&(u.canceled||l(),
u.canceled=!0)}}))}))})));const K=function(){var t=n((function*(t){if(!("ack"in t))if(t.onpartial){const n=t.data,o=n,r=o.partial,s=n.nada;if(u){if(u.canceled)return;const e=bn||((e,t)=>e.enqueue(t));if(void 0!==r){const t=new Zn(Vo(r));e(u.ctrl,t)}else if(void 0!==s){const t=new Zn(s.buffer);e(u.ctrl,t)}else so.error(`${m}:`,"data message without data?!")}else{let t;r&&Zt(p,r),s&&(t=s),void 0!==o.index&&o.index!==o.length-1||(p.length&&(e=Yt(p,""),p=[]),i=t)}}else{const e=t.data
;if(q=e.readyState||q,B=e.status||B,G&&(e.context=G),t.onload)yield X(e),c(s.onreadystatechange,e),c(s.onload,e);else if(t.onreadystatechange)yield X(e),4!=e.readyState&&c(s.onreadystatechange,e);else if(t.onerror)t.exception&&so.error(t.exception),c(s.onerror,e);else if(t.onabort)c(s.onabort,e);else if(t.ondone)f=!0,u&&!u.canceled&&(yn||(e=>e.close()))(u.ctrl),yield X(e),c(s.onloadend,e);else if(t.onloadstart)u&&(yield X(e)),
c(s.onloadstart,e);else if(t.onuploadprogress)s.upload&&c(s.upload.onprogress,e);else{const n=no(Jt(["onprogress","ontimeout"],(e=>!!t[e])),0)||"onerror";c(s[n],e)}}}));return function(e){return t.apply(this,arguments)}}();d.onMessage.addListener((e=>W((()=>K(e))))),d.onDisconnect.addListener((()=>{f||c(s.onerror,Dt({readyState:q,status:B,error:"background shutdown"})),d=null})),l=()=>{d&&d.postMessage(Dt({messageId:uo(),cancel:!0}))}})),Dt({abort:()=>{l()}})},i=(()=>{const e=Dt({
toString:()=>"[object Object]",DONE:Nn,HEADERS_RECEIVED:qn,LOADING:Bn,OPENED:Xn,UNSENT:Hn});return tn(["text","arraybuffer","blob","document","json","stream"],(t=>{e[`RESPONSE_TYPE_${Rn(t)}`]=t})),e})();return tn(wt(i),(e=>Ut(s,e,i[e]))),Dt({GM_xmlhttpRequest:e?Dt({value:s}):void 0,"GM.xmlHttpRequest":e?Dt({get:()=>{const e=e=>u(s,e);return tn(wt(i),(t=>Ut(e,t,i[t]))),e}}):void 0})})(),h=(()=>{let n;const o=()=>{if(!n){
const{script:o}=e,{antifeatures:r,author:s,blockers:i,copyright:a,deleted:l,description_i18n:c,description:u,downloadURL:d,fileURL:g,grant:p,header:f,homepage:m,icon:v,icon64:_,lastModified:h,name_i18n:b,name:y,namespace:M,position:w,resources:E,supportURL:S,system:G,updateURL:L,version:R,webRequest:I,options:{override:{orig_connects:O,orig_excludes:C,orig_includes:x,orig_matches:k},run_at:T,run_in:P,unwrap:A}}=o,{downloadMode:D,inIncognitoContext:U,relaxedCsp:$,isFirstPartyIsolation:j,container:F,sandboxMode:V,userAgent:N,version:q}=t,B=L||g,X=Dt({
antifeatures:r,author:s,blockers:i,connects:O,copyright:a,deleted:l,description_i18n:c,description:u,downloadURL:d,excludes:C,fileURL:g,grant:p,header:f,homepage:m,icon:v,icon64:_,includes:x,lastModified:h,matches:k,name_i18n:b,name:y,namespace:M,options:o.options,position:w,resources:E,"run-at":T,"run-in":P,supportURL:S,system:G,unwrap:A,updateURL:L,version:R,webRequest:I}),H=Dt({downloadMode:D,isFirstPartyIsolation:j,isIncognito:U,relaxedCsp:$,sandboxMode:V,container:F?Dt({id:F}):void 0,
script:X,scriptHandler:"Tampermonkey",scriptMetaStr:o.header,scriptUpdateURL:B,scriptWillUpdate:!!B,userAgentData:N,version:q});n=H}return Xt(Bt(n))};return Dt({GM_info:Dt({get:o}),"GM.info":Dt({get:o})})})(),b=(()=>{const e=a(r.grant,$o);let t=null;const n=(e,n)=>{const s=()=>{t==i&&(t=null),i=null};t&&t.disconnect(),rr(o);let i=t=fo.connect("webRequest",!0);return n&&i.onMessage.addListener((e=>{"ack"in e||n(e.type,e.message||"ok",e.details)})),i.onDisconnect.addListener(s),
i.connectMessage(Dt({messageId:uo(),rules:e,uuid:r.uuid})),Dt({abort:()=>{i&&i.disconnect(),s()}})};return Dt({GM_webRequest:e?Dt({value:n}):void 0,"GM.webRequest":e?Dt({get:()=>l(n)}):void 0})})(),y=(()=>{const e=a(r.grant,ko);let t=0;const n=Dt({}),o=Dt({}),s=(e,s,a)=>{if("string"!=typeof e)throw"invalid name";const{accessKey:l,autoClose:c,title:u,id:d}="string"==typeof a?Dt({accessKey:a}):a||Dt({}),g=void 0!==d?d:++t,p=n[g],f=p||fo.connect("registerMenuCommand",!0);return o[g]=s,
p||(f.onMessage.addListener((e=>{if(!("ack"in e)&&"run"===e.method){const t=o[g];if(!t)return;const n=e.event,r=n?n.keyCode?new Yn("keypress",n):new Qn("click",e.event):void 0;Qo((()=>t(r)),1)}})),f.onDisconnect.addListener((()=>{i(g)})),n[g]=f),f.connectMessage(Dt({messageId:uo(),name:e,uuid:r.uuid,accessKey:l,autoClose:c,title:u,id:`${g}`})),g},i=e=>{delete o[e];const t=n[e];t&&(t.disconnect(),delete n[e])};return Dt({GM_registerMenuCommand:e?Dt({value:s}):void 0,
"GM.registerMenuCommand":e?Dt({get:()=>l(s)}):void 0,GM_unregisterMenuCommand:e?Dt({value:i}):void 0,"GM.unregisterMenuCommand":e?Dt({get:()=>l(i)}):void 0})})(),M=(()=>{const e=a(r.grant,Oo),t=Dt({}),n=Dt({}),o=(e,o,s,i)=>{let a,l,c=null,u=i||null;const d=e=>Yt([e?`tag-${e}`:uo(),r.uuid],"#");if("object"==typeof e){const t=ln(e),{timeout:n,text:s,image:i,title:g,highlight:p,silent:f,url:m,tag:v,ondone:_,onclick:h}=t;l=d(v),a=Dt({id:l,timeout:n,text:s,image:i||r.icon64||r.icon||void 0,
title:g||r.name,highlight:p,silent:f,url:m,tag:v}),"ondone"in t&&(c=_),"onclick"in t&&(u=h),"function"==typeof o&&(c=o)}else l=d(),a=Dt({id:l,text:e,title:"string"==typeof o?o:r.name,image:s||r.icon64||r.icon||void 0});null!==u&&(a.onclick=u),null!==c&&(a.ondone=c),((e,o)=>{const s=ln(o),{text:i,title:a,tag:l,url:c,image:u,highlight:d,silent:g,timeout:p,onclick:f,ondone:m}=s;if("onclick"in s&&(t[e]=f),"ondone"in s&&(n[e]=m),i||d){const o="notification",s=fo.connect(o,!0)
;s.onMessage.addListener((o=>{if("ack"in o)return;const{clicked:r}=o;let f=!1;const m=Dt({text:i,title:a,tag:l,url:c,image:u,highlight:d,silent:g,timeout:p,preventDefault:()=>{f=!0}}),v=t[e],_=n[e];r&&(v&&v(m),s.postMessage(Dt({messageId:uo(),canceled:f}))),_&&_(!0===r,m),s.disconnect(),delete t[e],delete n[e]})),s.connectMessage(Dt({messageId:uo(),method:"notification",id:e,uuid:r.uuid,text:i,title:a,tag:l,url:c,image:u,highlight:d,silent:g,timeout:p}))
}else so.warn("GM_notification: neither a message text nor highlight options were given!")})(l,a)};return Dt({GM_notification:e?Dt({value:o}):void 0,"GM.notification":e?Dt({get:()=>(e,t,n,r)=>{let s;return s="object"==typeof e?e:Dt({text:e,title:t,image:n,onclick:r}),new pn((e=>{const t=Dt({});tn(wt(s),(e=>{t[e]=s[e]}));const n=t.ondone;t.ondone=function(t,o){n&&At(n,this,[t,o]),At(e,this,[t])},o(t)}))}}):void 0})})(),w=(()=>{const e=a(r.grant,Eo),t=(e,t)=>Dt({action:e,uuid:r.uuid,
location:io.location.href,details:t}),n=Dt({set:(e,n)=>{s.send("cookie",t("set",e),n?e=>{n(e.error)}:null)},delete:(e,n)=>{s.send("cookie",t("delete",e),n?e=>{n(e.error)}:null)},list:(e,n)=>{s.send("cookie",t("list",e),n?e=>{n(e.cookies,e.error)}:null)}});return Dt({GM_cookie:e?Dt({get:()=>{const e=(e,t,o)=>(n[e]||(()=>{}))(t,o);return tn(wt(n),(t=>{Ut(e,t,n[t])})),e}}):void 0,"GM.cookie":e?Dt({get:()=>{const e=Dt({});return tn(wt(n),(t=>{e[t]=e=>((e,t)=>new pn(((o,r)=>{if("list"==e){
const s=t||Dt({});n[e](s,((e,t)=>{t?r(t):o(e)}))}else if("set"==e){const s=t;n[e](s,(e=>{e?r(e):o(void 0)}))}else{const s=t;n[e](s,(e=>{e?r(e):o(void 0)}))}})))(t,e)})),e}}):void 0})})(),E=(()=>{const e=a(r.grant,Go),t=(e,t)=>{const n=cn(e);return-1==en(["String","Blob","File"],n)?e:Dt({url:e,name:t,mode:void 0,headers:void 0,saveAs:void 0,anonymous:void 0,conflictAction:void 0,onprogress:void 0,onload:void 0,ondone:void 0,ontimeout:void 0,onerror:void 0})},n=(e,n)=>{const s=t(e,n),i=(e,t)=>{
t=t||Dt({}),e&&Qo((()=>{At(e,t,[t])}),1)},{url:a,name:l,mode:c,headers:u,saveAs:d,anonymous:g,conflictAction:p}=s;let f;rr(o);let m=fo.connect("download",!0);const v=()=>{m&&m.stopReconnecting()};m.onMessage.addListener((e=>{if(!("ack"in e)){m&&void 0===f&&(f=e.id,m.connectMessage(Dt({messageId:uo(),method:"download",uuid:r.uuid,id:f}),!1));try{e.load?(s.onload&&i(s.onload,e.data),v()):e.progress?s.onprogress&&i(s.onprogress,e.data):e.timeout?(s.ontimeout&&i(s.ontimeout,e.data),
v()):(s.onerror&&i(s.onerror,e.data),v())}catch(e){so.log("env: Error: TM_download - ",e,s)}}})),m.onDisconnect.addListener((()=>m=null));const _=Dt({messageId:uo(),details:Dt({url:a,name:l,mode:c,headers:u,conflictAction:p,anonymous:g,saveAs:d}),uuid:r.uuid});return m.postMessage(_),Dt({abort:()=>{m&&m.postMessage(Dt({uuid:r.uuid,cancel:!0}))}})};return Dt({GM_download:e?Dt({value:n}):void 0,"GM.download":e?Dt({get:()=>(e,o)=>u(n,t(e,o))}):void 0})})(),S=(()=>{const e=a(r.grant,Co),t=(e,t)=>{
const n="openInTab";let s,i,a=!1,l=null;const c=(()=>{const e=[];return Dt({run:t=>{if(t&&Zt(e,t),s)for(;e.length;)Kt(e)()}})})();rr(o);let u=fo.connect(n,!0);const d=()=>{u&&u.postMessage(Dt({messageId:uo(),close:!0}))};u.onMessage.addListener((e=>{"ack"in e||(e.tabId?a?d():(u&&void 0===s&&u.connectMessage(Dt({messageId:uo(),method:n,uuid:r.uuid,tabId:e.tabId}),!1),s=e.tabId,c.run()):e.name?i=e.name:e.closed&&(a=!0,l&&(l(),l=null),u&&u.stopReconnecting()))})),
u.onDisconnect.addListener((()=>u=null)),u.postMessage(Dt({messageId:uo(),method:n,url:e,location:io.location.href,options:t,uuid:r.uuid}));const g=Dt({});return Gt(g,Dt({close:Dt({value:()=>{a?so.warn("env: attempt to close already closed tab!"):d()}}),focus:Dt({value:()=>{u&&u.postMessage(Dt({messageId:uo(),focus:!0}))}}),closed:Dt({get:()=>a}),onclose:Dt({get:()=>l,set:e=>{l=e}}),name:Dt({get:()=>i,set:e=>{c.run((()=>{u&&u.postMessage(Dt({messageId:uo(),name:e}))}))}})})),g};return Dt({
GM_openInTab:e?Dt({value:t}):void 0,"GM.openInTab":e?Dt({get:()=>l(t)}):void 0})})(),G=(()=>{const e=a(r.grant,Ao);return Dt({"window.close":e?Dt({value:e=>{s.send("closeTab",Dt({uuid:r.uuid}),e?()=>e():null)}}):void 0})})(),L=Dt({navigate:Dt({value:(e,t)=>{const n=Dt({uuid:r.uuid,url:e,location:io.location.href});s.send("navigateTab",n,t?()=>t():null)}})}),R=(()=>{const e=a(r.grant,Do);return Dt({"window.focus":e?Dt({value:e=>{s.send("focusTab",Dt({uuid:r.uuid}),e?()=>e():null)}}):void 0})
})(),I=(()=>{const e=a(r.grant,Io),t=function(...e){At(so.log,this,e)};return Dt({GM_log:e?Dt({value:t}):void 0,"GM.log":e?Dt({get:()=>l(t)}):void 0})})(),O=({root:e,tag:t,properties:n,cb:o})=>{let i;n&&tn(wt(n),(e=>{const t=n[e];"function"==typeof t&&(i||(i=Dt({})),i[e]=t,delete n[e])}));const a=Dt({tag:t,properties:n,uuid:r.uuid});let l=null;if(s.send("addElement",a,e,((e,t)=>{o&&o(),l=t||null})),l){if(i){const e=i;tn(wt(e),(t=>{try{const n=e[t];l[t]=n}catch(e){
so.warn(`addElement: failed to set property ${t} on element`,e)}}))}}else so.error("addElement: failed to find created element");return l},C=(()=>{const e=a(r.grant,wo),t=(e,t)=>O(Dt({root:void 0,tag:"style",properties:Dt({textContent:e}),cb:t?()=>t():void 0}));return Dt({GM_addStyle:e?Dt({value:t}):void 0,"GM.addStyle":e?Dt({get:()=>l(t)}):void 0})})(),x=(()=>{const e=a(r.grant,wo),t=(e,t,n,o)=>{let r,s,i,a;if("string"==typeof e)s=e,i=t,a=n;else if(r=e,s=t,i=n,a=o,
!r)return so.warn("addElement: parent is not a Node"),null;return i&&(i=Dt(i)),O(Dt({root:r,tag:s,properties:i,cb:a}))||null};return Dt({GM_addElement:e?Dt({value:t}):void 0,"GM.addElement":e?Dt({get:()=>l(t)}):void 0})})(),k=(()=>{const e=a(r.grant,Mo),t=(e,t)=>{const n="backgroundControl",s=fo.connect(n);let i=!1;const a="restart"===e.action||void 0;s.onMessage.addListener((e=>{if("ack"in e)return;i=!0;const n=e?e.error:void 0;n&&so.warn(n),t&&t(n),s.disconnect()})),s.postMessage(Dt({
messageId:uo(),method:n,id:o,uuid:r.uuid,restart:a})),a&&(or=!1),s.onDisconnect.addListener((()=>{!i&&t&&t(a?void 0:"port disconnected for unknown reason"),i=!0}))};return Dt({"GM.backgroundControl":e?Dt({get:()=>l(t)}):void 0})})(),T=Dt({...x,...C,...G,...L,...w,...E,...R,...h,...I,...y,...M,...S,...m,...d,...v,...p,...f,...g,...b,..._,...k});return i[e.script.uuid]=i[e.script.uuid]||T,i[e.script.uuid]}})},ir=(e,t,o,r,s,i)=>{const a=(e,t,n,o,r)=>{const s=t[n],a=typeof s
;return o&&"string"===a?t[n]=()=>i(s,r):r&&"function"===a&&(t[n]=function(){return At(s,r,arguments)}),At(e,ht,t)},l=function(){var e=n((function*(e,t,n,o){const r=Dt({attrName:"null",newValue:"null",prevValue:"null",eventPhase:An,target:ht.document,relatedNode:ht.document,srcElement:ht.document});yield null,n||(yield null),"load"===e&&(yield null),((e,t,n,o)=>{const r=Dt({bubbles:!0,cancelBubble:!1,cancelable:!1,clipboardData:void 0,currentTarget:null,defaultPrevented:!1,eventPhase:0,
newValue:null,prevValue:null,relatedNode:null,returnValue:!0,srcElement:null,target:null,timeStamp:Wn()}),s="string"==typeof n?()=>i(n,o):n,a=new Event(e);tn(wt(r),(e=>{Ut(a,e,r[e])})),tn(wt(t),(e=>{Ut(a,e,t[e])})),At(s,o,[a])})(e,r,t,o)}));return function(t,n,o,r){return e.apply(this,arguments)}}();let c=!0;go((()=>c=!1));const u=Dt({}),d=e=>!!("object"==typeof e&&null!==e?e.capture:e),g=(e,r,s)=>{let i,g;null===r||("object"==typeof r?(i=function(){var e=n((function*(e){const t=r.handleEvent
;"function"==typeof t&&At(t,r,[e])}));return function(t){return e.apply(this,arguments)}}(),g=r):(i=r,g=void 0));const f=d(s);let v,_;if(void 0!==i&&c&&((v="DOMContentLoaded"==e)||"load"==e)){const n=kn(ht.document);if(v&&("complete"==n||"interactive"===n)&&"document-idle"!=t||!v&&"complete"==n)return void l(e,i,f,m)}const h="urlchange"==e?o["window.onurlchange"]:void 0;if(void 0===i);else if("string"!=typeof i){const t=`${e}-${f}`;u[t]=u[t]||[];const n=function(...t){
return"object"==typeof s&&s.once&&p(e,r,s),At(i,this===ht||this===bt?m:this,t)},o=Dt({listener:i,filter:n,object:g});if(Zt(u[t],o),_=n,h)return void h.value.register(n)}else{if(h)return void so.warn("env: urlchange listener must be a function!");_=i}return a(io.addEventListener,[e,_,s],1,!0)},p=(e,t,n)=>{let r,s;null===t||("object"==typeof t?s=t:r=t);const i="urlchange"==e?o["window.onurlchange"]:void 0,l=d(n),c=`${e}-${l}`,g=u[c]&&Jt(u[c],(e=>e.object?e.object===s:e.listener===r))
;if(g&&g.length){let t;if(tn(g,(o=>{if(i)i.value.unregister(o.filter);else try{a(io.removeEventListener,[e,o.filter,n],1,!0)}catch(o){t=o}const r=en(u[c],o);u[c]=Wt(u[c],r,1).result})),u[c].length||delete u[c],t)throw t}else if(void 0!==r)return a(io.removeEventListener,[e,r,n],1,!0)},f=Dt({CDATA:Dt({value:function(e){this.src=e,this.toString=function(){return this.src},this.toXMLString=this.toString}}),uneval:Dt({value:e=>{try{return`\\$1 = ${Bt(e)};`}catch(e){so.log(e)}}}),define:Dt({
value:void 0}),module:Dt({value:void 0}),exports:Dt({value:void 0}),setTimeout:Dt({value:(...e)=>a(tr,e,0,!0,m)}),setInterval:Dt({value:(...e)=>a(nr,e,0,!0,m)}),close:(()=>{const e=o["window.close"];return e?Dt({get:()=>ht==ht.top?t=>e.value(t):io.close}):void 0})(),focus:(()=>{const e=o["window.focus"];return e?Dt({get:()=>t=>e.value(t)}):void 0})(),onurlchange:o["window.onurlchange"]?(()=>{let e=null;return Dt({get:()=>e,set:t=>{e&&p("urlchange",e),e=t,g("urlchange",e)}})})():void 0,
location:Dt({set:e=>{const t=o.navigate;t?t.value(e):io.location.href=e}}),name:Dt({get:()=>ht.name,set:e=>{ht.name=e}}),clearInterval:Dt({get:()=>er}),clearTimeout:Dt({get:()=>Zo}),addEventListener:Dt({value:g}),removeEventListener:Dt({value:p}),console:(()=>{let e;return Dt({get:()=>(e||(e=(()=>{const e=Dt({});return tn(Rt(De),(t=>{const n=t,o=Dt(bo[t]),r="value"in o?()=>o.value:o.get;yo[n]=Dt({get:r,set:t=>{delete e[n],e[n]=t},enumerable:!0,configurable:!0})})),Gt(e,yo),e})()),e)})})()})
;if(!e){const e=Dt({window:Dt({get:()=>m}),globalThis:Dt({get:()=>m}),cloneInto:Dt({value:e=>e}),exportFunction:Dt({value:(e,t,n)=>{const o=n&&$t(n,"defineAs");return o&&(t[o]=e),e}}),createObjectIn:Dt({value:(e,t)=>{const n=Dt({}),o=t&&$t(t,"defineAs");return o&&(e[o]=n),n}}),undefined:Dt({get:()=>{}})});St(f,e)}r&&St(f,r);const m=s(f);return m};let ar;n((function*(){const t=e.contextId;let r;const{fSend:s,fOnMessage:i,cloneInto:a,pageWindow:l}=e;r=s&&i?lo(Dt({sendPrefix:"2U",listenPrefix:"2S",
send:s,onMessage:i})):co(Dt({sendPrefix:"2C",listenPrefix:"2P"})),e.bridges.first=r;const c=St(e.console,vo);r.init(t);const u=Dt({});r.setMessageListener((({method:t,args:n})=>{if("commid"==t)r.switchId(n.id),r.send("ack",Dt({id:n.id}));else if("injectable"==t)p(n.id,(()=>{r.send("ack",Dt({id:n.id}))})),r.send("injectableack",Dt({id:n.id}));else if("setForeignAttr"==t)ht[n.attr]=n.value;else if("script"==t){const{id:t,unwrap:o,bundle:s}=n,{script:i}=s,{name:a,uuid:l,options:{run_at:c}}=i
;p(t,(t=>{const r=o?()=>t():()=>At(t,((t,n,o,r)=>{const{pageWindow:s,cloneInto:i,exportFunction:a}=e,l=s||ht,{script:c}=t,u=c.options.compat_powerful_this,d=-1!==en(c.grant,"none");ar=ar||sr(n);const g=ar.of(t),p=e=>Dt({p:v,r:At,s:e}),f=Dt({seed:Dt({get:()=>p(h),once:!0})}),m=Dt({}),v=Dt({GM:m}),_=l&&l;u&&(Ut(f,"GM",Dt({value:m})),Ut(f,"unsafeWindow",Dt({value:_}))),d||(v.unsafeWindow=_),tn(wt(g),(e=>{const t=wn(e,0,3),n=g[e];if(void 0!==n)if("GM_"===t)v[e]=void 0!==n.get?n.get():n.value,
u&&Ut(f,e,n);else if("GM."===t){const t=rn(e,3);n.configurable=n.enumerable=!0,"value"in n?n.writable=!0:"set"in n||(n.set=e=>{delete m[t],m[t]=e}),Lt(m,t,n)}}));const h=d?p(u?v:Dt({})):ir(d,c.options.run_at,g,f,o,r);return h})(s,n.flags,d,m),[]);"document-start"==c||"context-menu"==c?r():u[l]=r}));const g=`scriptack-${t}`;r.send(g,Dt({id:t}))}else if("port.message"==t)fo.message(n,r);else if("external.connect"==t)(t=>{const{bridges:n}=e,o=ht,r=$t(o,"external");if(!r)return
;const s=t?e=>t(e,o,Dt({cloneFunctions:!0})):e=>e,i=(e,t)=>{n.first.send("external.message",e,t)};try{const e=()=>{const e=Dt({getVersion:e=>{i(Dt({method:"getVersion"}),(t=>e(s(t))))},openOptions:(e,t)=>{i(Dt({method:"openOptions",params:e}),t)},isInstalled:(e,t,n)=>{"function"==typeof t&&(n=t,t=null),n&&i(Dt({method:"isInstalled",script:Dt({name:e,namespace:t})}),(e=>n(s(e))))}});return s(e)};Gt(r,Dt({Tampermonkey:Dt({value:e(),configurable:!0})}))}catch(e){}})(a);else if("run"==t){
const{uuid:e}=n,t=$t(u,e);t?"function"==typeof t&&(t(),delete u[e]):c.warn(`env: missing script "${e}"!`)}}));const{createProxy:d}=((e,t)=>{const n=(e=>{let t=Dt({});const n=(e,o,r)=>{const s=Ot(e);s&&s===o||(null!=s&&--r>=0&&n(s,e,r),t=St(t,Ct(e)))};return n(e,null,5),t})(ht);tn(o,(e=>delete n[e]));const r=n;return Dt({createProxy:n=>{let o=r;const s=e=>{let t,n;const r=(t=It(p,e))||(n=o[e]);return Dt({d:r?Dt(r):r,l:!!t,w:!!n})},i=e=>{if(!l(e))return!1;if("length"===e)return!0;const t=kt(Jn(e))
;return t>=0&&t<=dn&&e===`${t}`},a=e=>"on"===wn(e,0,2),l=e=>"string"==typeof e,c=(e,n)=>{const o=wn(e,2),r=g[o];if(r&&(t.removeEventListener(o,r),delete g[o]),n&&(e=>"function"==typeof e)(n)){const e=(...e)=>At(n,t,e);t.addEventListener(o,e),g[o]=e}},u=t=>void 0!==t&&(t===e||t===ht||t===bt),d=Dt({addEventListener:!0,alert:!0,atob:!0,blur:!0,btoa:!0,cancelAnimationFrame:!0,cancelIdleCallback:!0,captureEvents:!0,clearInterval:!0,clearTimeout:!0,close:!0,confirm:!0,createImageBitmap:!0,
dispatchEvent:!0,dump:!0,fetch:!0,find:!0,focus:!0,getComputedStyle:!0,getDefaultComputedStyle:!0,getSelection:!0,matchMedia:!0,moveBy:!0,moveTo:!0,open:!0,openDatabase:!0,postMessage:!0,print:!0,prompt:!0,queueMicrotask:!0,releaseEvents:!0,removeEventListener:!0,reportError:!0,requestAnimationFrame:!0,requestIdleCallback:!0,resizeBy:!0,resizeTo:!0,scroll:!0,scrollBy:!0,scrollByLines:!0,scrollByPages:!0,scrollTo:!0,setInterval:!0,setResizable:!0,setTimeout:!0,showDirectoryPicker:!0,
sizeToContent:!0,stop:!0,structuredClone:!0,updateCommands:!0,webkitCancelAnimationFrame:!0,webkitRequestAnimationFrame:!0,webkitRequestFileSystem:!0,webkitResolveLocalFileSystemURL:!0});tn(wt(d),(e=>{n[e]=n[e]||Dt({bind:!0})}));const g=Dt({}),p=Dt({});Ut(p,In,"Window");const f=new Kn(p,Dt({defineProperty:(e,t,o)=>{const{d:r,l:u}=s(t),d=Dt(o);return r&&!r.configurable&&(!!r.configurable!=!!d.configurable||!!r.enumerable!=!!r.enumerable)||i(t)?(Lt(u?p:ht,t,d),!1):(Lt(p,t,d),l(t)&&a(t)&&c(t),
delete n[t],!0)},deleteProperty:(e,t)=>{let{d:i,l:u,w:d}=s(t);return!(!i||!i.configurable)&&(u&&(u=delete p[t],l(t)&&a(t)&&c(t)),(d||(i=o[t])&&i.configurable)&&(r===o&&(o=St(Dt({}),r)),d=delete o[t]),delete n[t],u||d)},get:(e,t)=>{if("undefined"===t||t===On)return;const o=n[t];if(o){if(o.once&&delete n[t],"value"in o)return o.value;if(o.get)return o.get()}const{d:r,l:a}=i(t)?Dt({d:It(ht,t),l:!1}):s(t);if(r){let e
;const n="value"in r?$t(r,"value"):(e=$t(r,"get"))&&"function"==typeof e?a?e():qt(e,ht)():void 0;return n&&o&&o.bind?qt(n,ht):a||"event"==t?n:u(n)||"globalThis"===t?f:n}},getOwnPropertyDescriptor:(e,t)=>{let{d:o,l:r}=s(t);if(!o){const e=n[t];if(e)return Dt({enumerable:!0,configurable:!0,writable:!0,value:e.value,set:e.set,get:e.get});if(!i(t))return;o=It(ht,t),r=!1}const a=St(Dt({}),o);if(u(a.value)&&(a.value=f),!r){const e=a.get;e&&(a.get=()=>{const t=qt(e,ht)();return u(t)?f:t}),
a&&!a.configurable&&Lt(p,t,a)}return a},has:(e,t)=>t in p||t in n||t in o,ownKeys:()=>{const e=e=>!(e in o),t=wt(o),n=Jt(wt(Ct(p)),e),r=Dt({});for(let e=0;"Window"===cn(jt(ht,e));e+=1)r[e]=!0;const s=Jt(wt(r),e);return Qt(t,n,s)},preventExtensions:()=>!0,set:(e,t,o)=>{const r=n[t];if(r&&r.set)return r.set(o),!0;const{d:u}=s(t);return!(u&&!u.writable&&!$t(u,"set")||i(t)||(delete n[t],Ut(p,t,o),l(t)&&a(t)&&c(t,o),0))}}));return f}})})(l,io),g=e=>{r.send("csp",Dt({src:e}))},p=function(){
var e=n((function*(e,t){Lt(bt,e,Dt({set:n=>(delete bt[e],po(),t(n)),configurable:!0,enumerable:!1})),go((()=>delete bt[e]))}));return function(t,n){return e.apply(this,arguments)}}(),f=function(){var e=n((function*(e,t,n){p(e,(e=>At(e,t,n||[])))}));return function(t,n,o){return e.apply(this,arguments)}}(),m=(e,t)=>t?((e,t)=>{const n=`__p__${uo()}`;f(n,t,void 0),g('window["'+n+'"] = function(){'+e+"};"),delete bt[n]})(e,t):g(e)}))(),po()})()};