var g;
if(!window.__idm_init__&&navigator.platform.startsWith("Win")&&document.documentElement.localName=="html"){window.__idm_init__=!0;typeof browser=="undefined"&&(browser=chrome);const V=Object.values,W=RegExp.prototype.test,M=Array.from,N=Array.prototype.includes,H=Math.random,X=Function.call.bind(Array.prototype.slice),O=Function.apply.bind(Array.prototype.push),F=Function.call.bind(Array.prototype.forEach),Y=Function.call.bind(String.prototype.charCodeAt),Z=String.fromCharCode;Array.prototype.at||(Array.prototype.at=
function(a){a<0&&(a+=this.length);return this[a]});AbortSignal.timeout||(AbortSignal.timeout=function(a){let b=new AbortController;globalThis.setTimeout(b.abort.bind(b),a);return b.signal});const aa=["date","content-type","content-length"];function ba(a,b){b&&(a[b]=!0);return a}function I(a){return a.replace(/[a-z]/gi,function(b){return Z((b=Y(b))+((b&31)>13?-13:13))})}const ca={16:!0,17:!0,18:!0,45:!0,46:!0},J=N.bind(["video","audio","object","embed"]),y=RegExp("(?!)"),da=RegExp(" *\\$([<>{}|&*+=@!#%:?^~-])(\\d*) *"),
ea=W.bind(/^rgba?\(\d+,\s*\d+,\s*\d+,\s*0\)/),fa=globalThis,G=window.self===window.top;var B=window.origin||document.origin||location.origin,K=location,P=location.hostname.toLowerCase()+location.pathname+location.search;function Q(){browser.runtime.getFrameId?this.ma=browser.runtime.getFrameId(window):G&&(this.ma=0);this.Ia=[];this.na=[];this.Y=[];this.A={};this.jb();window.__idm_connect__=this.jb.bind(this,!0);this.j(1,window,"resize",this.Bc);this.j(1,window,"scroll",this.Cc);this.j(1,window,"blur",
this.tc);this.j(1,window,"keydown",this.sb,!0);this.j(1,window,"keyup",this.sb,!0);this.j(1,window,"mousedown",this.vc,!0);this.j(1,window,"mouseup",this.xc,!0);this.j(1,window,"mousemove",this.wc,!0);this.j(1,window,"click",this.uc,!0);this.j(1,document,"beforeload",this.rc,!0);this.j(1,document,"DOMContentLoaded",this.rb);document.readyState!="interactive"&&document.readyState!="complete"||this.rb()}g=Q.prototype;g.Ja="idmrs:///";g.va=y;g.v=0;g.C=0;g.oa=-1;g.pa=-1;g.yb=1;g.u="";g.$=0;g.m="";g.Pa=
"";g.M="";g.qa="";g.Wa=y;g.cb=y;g.N=y;g.fb=y;g.Xa=y;g.I={};g.Ya="(?!)";g.Za="(?!)";g.$a="(?!)";g.ab="(?!)";g.bb="(?!)";g.eb=I('$> *[ebyr="znva"]:abg(uvqqra) ivqrb, :fpbcr >qvi#cynlre ivqrb, lgzhfvp-cynlre ivqrb');g.gb=I("$> lgzhfvp-cynlre qvi#fbat-vzntr vzt");g.Va=I("$<< $> :fpbcr >ivqrb +qvi >pnainf");g.ua=y;g.ra=":root:empty";g.ta=0;g.sa=y;g.Aa=y;g.Ba='$& div.xxzkxad $& :scope >div[class] $& section main[role="main"] $& div.xw7yly9 >div >div[style]:only-child $& div >article <';g.Da='$& div.xxzkxad $& :scope >div[class] $& section main[role="main"] $& div:first-child >div[role="button"][aria-hidden], article[role="presentation"] $& div:first-child >div[style]:first-child:empty < $& div[role="presentation"] >div >ul';
g.za='$+ article:scope, div.x1xfsgkm:scope $* main[role="main"] article, main[role="main"] >div >div.x1xfsgkm';g.Ea="$= poster $< <<<<<< $> div:scope >img:first-child, div[data-instancekey] div >img:first-child $= src";g.Ca=RegExp("/(?:p|reel|reels|stories/[\\w.-]+)/([\\w-]{11}|\\d{19})(?:[/?#]|$)");g.Qa=y;g.Ra=RegExp("^(?:[^/]+|player\\.vimeo\\.com/video)/(\\d{2,})");g.Ua="$| video:scope $| video";g.Sa="$> :scope >div.player";g.Ta="$& div.vp-video $& div.vp-telecine";g.jb=function(a){this.tb(-1);
this.g=a=browser.runtime.connect({name:(G?"top":"sub")+(a?":retry":"")+(location.protocol=="file:"?":file":"")});this.j(-1,a,"onMessage",this.zc);this.j(-1,a,"onDisconnect",this.yc)};g.yc=function(){browser.runtime.lastError;this.tb();this.g=this.X=null;window.__idm_init__=!1;window.__idm_connect__=null};g.zc=function(a){switch(a.shift()){case 11:this.Tb.apply(this,a);break;case 17:this.Ub.apply(this,a);break;case 12:this.Wb.apply(this,a);break;case 13:this.Vb=a.shift();break;case 14:this.Zb.apply(this,
a);break;case 15:this.$b.apply(this,a);break;case 16:this.ac.apply(this,a);break;case 18:this.Yb.apply(this,a)}};g.Ec=function(a,b){var c=this.K>=105;let d=this.K>=108;switch(this.B=a){case 1:this.L=this.bc=!0;this.$=2;if(a=b.shift())this.m=a;if(a=b.shift())this.Wa=RegExp(a,"s");if(a=b.shift())this.N=RegExp(a);if(a=b.shift())this.fb=RegExp(a);if(a=b.shift())this.I=a.split(/[|:]/).reduce(ba,{});if(a=b.shift())this.Xa=RegExp(a);if(a=b.shift())this.Ya=a;if(a=b.shift())this.Za=a;(a=b.shift())&&c&&(this.$a=
a);(a=b.shift())&&c&&(this.ab=a);(a=b.shift())&&c&&(this.bb=a);(a=b.shift())&&d&&(this.cb=RegExp(a,"s"));(a=b.shift())&&d&&(this.eb=a);if(a=b.shift())this.Va=a;if(a=b.shift())this.Oa=a;if(a=b.shift())this.cc=a;if(a=b.shift())this.qc=a;if(a=b.shift())this.oc=a;if(a=b.shift())this.gb=a;break;case 2:this.lb();this.L=!0;this.$=3;if(a=b.shift())this.m=a;if(a=b.shift())this.M=a;if(a=b.shift())this.ua=RegExp(a);if(a=b.shift())this.Bb=a;if(a=b.shift())this.Eb=a;b.shift();if(a=b.shift())this.ya=a.startsWith("$")?
a:`$< ${a.slice(1)} <`;if(a=b.shift())this.Fb=a;if(a=b.shift())this.Ab=a.startsWith("$")?a:`$* ${a}`;if(a=b.shift())this.Fa=a.startsWith("$")?a:`$< ${a.slice(1)} <`;if(a=b.shift())this.Gb=a;if(a=b.shift())this.ra=a;if(a=b.shift())this.xb=a.startsWith("$")?a:`$* ${a}`;if(c=b.shift())this.ta=c;if(a=b.shift())this.Cb=a;if(a=b.shift())this.sa=RegExp(a);break;case 4:this.lb();this.L=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.Pa=a;if(a=b.shift())this.M=a;if(a=b.shift())this.Aa=RegExp(a);if(a=b.shift())this.Lb=
a;if(a=b.shift())this.Ba=a;if(a=b.shift())this.Da=a;if(a=b.shift())this.Mb=a;if(a=b.shift())this.za=a;if(a=b.shift())this.Ib=a;if(a=b.shift())this.Ga=a;if(a=b.shift())this.Ea=a;b.shift();if(a=b.shift())this.Jb=a;if(a=b.shift())this.Ca=RegExp(a);break;case 3:if(a=b.shift())this.Qa=RegExp(a);if(a=b.shift())this.Ra=RegExp(a);if(a=b.shift())this.Ua=a;if(a=b.shift())this.Sa=a;if(a=b.shift())this.Ta=a;break;case 5:this.L=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.M=a;if(a=b.shift())this.Nb=a;break;
default:this.L=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.Na=a}this.m.includes("^/")&&((b=this.Pa)?b="https?://"+b.slice(+b.startsWith("^"),-b.endsWith("$")||void 0):b=B.replaceAll(".","\\."),this.m=this.m.replaceAll("^/",`^(?:${b})?/`))};g.ha=function(a){if(this.B&&this.U(arguments))switch(this.B){case 1:this.nc(a);break;case 2:this.jc(a);break;case 4:this.kc(a);break;case 3:this.mc(a);break;case 5:this.lc(a)}};g.da=function(a){let b=this.g;for(let c of document.getElementsByTagName("script"))!c.src&&
a.test(c.text)&&b.postMessage([34,null,-1,c.text]);b.postMessage([34,this.D()])};g.ka=function(a,b,c,d){if(this.zb&&c){let e=a instanceof Element?this.S(a):0,f=this.Y,h=f.indexOf(null);h<0&&(h=f.length);f[h]=[a,b,d];this.la(1229212981,h,e,c)}else d(a,b)};g.Ac=function(a,b){var c=this.Y.splice(a,1,null).shift();if(c){a=c[0];let d=c[1];c=c[2];a instanceof Element&&!document.contains(a)&&(b=void 0);c(a,d,b)}};g.Dc=function(a){var b=a.data;if(Array.isArray(b)&&a.origin==B)switch(b[0]){case 1229212977:this.zb=
!0;a=btoa(H().toString().substr(2,9));b=btoa(H().toString().substr(2,9));this.la(1229212978,this.X,this.u,a,b,aa,this.qa,this.L,this.bc,this.m,this.M);break;case 1229212979:this.g.postMessage([46,b[1],b[2],b[3]]);break;case 1229212980:this.g.postMessage([36,b[1],b[2]]);break;case 1229212982:this.Ac(b[1],b[2])}};g.la=function(a,...b){window.postMessage(X(arguments),"/")};g.ea=function(){let a=window.devicePixelRatio,b=document.width,c=document.body.scrollWidth;b&&c&&(a=b==c?0:b/c);return a};g.lb=function(){this.u||
(this.u=btoa(H().toString().substr(2,9)))};g.S=function(a){let b,c=a.l;c||(c=a.l=this.X<<13|this.yb++,this.A[c]=a,(b=this.u)&&a.setAttribute(b,c));return c};g.P=function(a){let b=this.u,c=this.A;b&&a.removeAttribute(b);this.h&&(a.removeAttribute("__idm_uri__"),a.removeAttribute("__idm_obs__"));a.G&&(window.clearTimeout(a.G),a.G=null);a.F&&(a.F.disconnect(),a.F=null);this.Z.unobserve(a);this.V.unobserve(a);delete c[a.l];delete c[a.o];delete c[a.i];a.l=a.o=a.i=a.J=a.T=null};g.hb=function(a,b,c,d,e){let f=
this.A,h=this.S(a);if(b||c){if(b&&f[b]||c&&f[c])return;d||=a.localName;a.o=b;a.i=c||=`${this.Ja}${d}/${b}`;b&&(f[b]=a);c&&(f[c]=a);this.h&&a.setAttribute("__idm_uri__",c)}a.F||(b=a.F=new MutationObserver(this.W.bind(this)),this.h&&a.setAttribute("__idm_obs__",1),b.observe(a,{attributes:!0,attributeFilter:["style"]}),b.observe(a.parentElement,{childList:!0}),this.Z.observe(a),e&&this.V.observe(a));this.B==1&&r(a,this.Oa)&&(a.fa=!0,a.dc=10);return h};g.H=function(a,b,c,d,e){if(b=this.hb(a,b,c,d,e))c=
this.R(a),this.g.postMessage([41,b,a.localName,a.src||a.data,a.i,a.o,c])};g.ib=function(a,b,c){if(!a.l&&b.l){this.h&&a.setAttribute("__idm_uri__",b.i);a.T=new WeakRef(b);b.T=new WeakRef(a);if(!a.F){let d=a.F=new MutationObserver(this.W.bind(this));this.h&&a.setAttribute("__idm_obs__",1);d.observe(a,{attributes:!0,attributeFilter:["style"]});d.observe(a.parentElement,{childList:!0});this.Z.observe(a)}this.V.observe(a);this.V.observe(b);c&&this.ub(a,b)}};g.Hb=function(a){if(!a.l){var b=a.T;b&&((b=b.deref())?
this.ub(a,b):a.T=null)}};g.ub=function(a,b){let c=this.u,d=this.A,e=a.l=b.l,f=a.o=b.o,h=a.i=b.i;b.l=b.o=b.i=null;c&&b.removeAttribute(c);c&&a.setAttribute(c,e);d[e]=a;f&&(d[f]=a);h&&(d[h]=a)};g.Sb=function(a,b,c,d,e,f){let h,k,m,p;let n,l,t=window.getComputedStyle.bind(window);try{let v=0;m=document.activeElement;m&&J(m.localName)||(m=document.elementFromPoint(this.oa,this.pa))&&!J(m.localName)&&(m=null);for(let q of document.querySelectorAll("video,audio,object,embed")){let C=q.localName,x;var w=
C=="object"||C=="embed";if(w){let E=q.type.toLowerCase();if(E.startsWith("text/")||E.startsWith("image/"))continue;if(C=="embed"&&E!="application/x-shockwave-flash")continue}if(q.i&&!q.fa&&(e||f))if(e?e==q.o:f==q.i)h=q;else continue;else if(x=q.src||q.data)x!=a&&x!=b||(h=q);else if(!w)for(let E of q.getElementsByTagName("source"))if((x=E.src)&&(x==a||x==b)&&(h=q))break;if(h)if(t(q).objectFit=="cover")k=q,h=null;else break;if(k||m||p)continue;if(x){if((x==c||x==d)&&(p=q))continue;if(C=="video"&&x.startsWith("data:audio/"))continue}let A=
q.clientWidth,z=q.clientHeight;if(!A||!z)continue;let R=q.getBoundingClientRect();if(R.right+window.scrollX<=0||R.bottom+window.scrollY<=0)continue;let S=t(q);if(q.J||S.visibility=="hidden"||S.display=="none")C=="video"&&(l||=q);else{w=A*z;if(v<w&&A*1.35>z&&A<z*3){v=w;var u=q}n||=q}}}catch(v){}(a=h||k||m||p)?a.localName!="video"&&t(a).visibility=="hidden"&&(a=null):a=u||n||l;a&&(a.localName!="embed"||a.clientWidth||a.clientHeight||(u=a.parentElement,u.localName=="object"&&(a=u)),this.hb(a,e,f));return a};
g.Rb=function(a,b,c){let d=null,e,f=browser.runtime.getFrameId;for(let h of document.getElementsByTagName("iframe")){let k=h.ob;k==null&&f&&(k=h.ob=f(h));if(k==a){d=h;break}else d||!(e=h.src)||e!=b&&e!=c||(d=h)}return d&&this.S(d)};g.R=function(a){let b=null;try{let c=window.getComputedStyle(a),d=a.getBoundingClientRect(),e=this.$,f=Math.round(d.width),h=Math.round(d.height),k;if(c.visibility=="hidden"&&!a.contentWindow)return f>h*5?null:!1;if(c.opacity==0||a.J)return!1;if(this.B==1&&a.offsetTop+
a.offsetHeight==0){for(let u=a;u=u.parentElement;){let v=window.getComputedStyle(u);if(v.display!="block")break;if(v.opacity==0)return!1}d=a.parentElement.parentElement.getBoundingClientRect();e=0;c.display=="none"&&r(a,this.Va)&&(f=Math.round(d.width),h=Math.round(d.height))}let m=Math.round(d.left)+a.clientLeft,p=Math.round(d.top)+a.clientTop;for(let u=0,v=0,q=a,C=c,x,A;e--&&C.display=="block"&&(x=q.parentElement)&&x.localName=="div";q=x,C=A){A=window.getComputedStyle(x);u-=q.offsetLeft;v-=q.offsetTop;
if(A.overflowX=="hidden"){let z=f-x.offsetWidth-u;u>0&&(f-=u,m+=u);z>0&&(f-=z);e=0}if(A.overflowY=="hidden"){let z=h-x.offsetHeight-v;v>0&&(h-=v,p+=v);z>0&&(h-=z);e=0}}switch(a.localName){case "video":document.contains(a)&&(a.videoWidth||a.i||a.readyState<1&&a.networkState==2)&&(b=!1);if(f<15||h<10)return b;break;case "audio":if(f<1&&h<1)return b;k=!0}let n=document.documentElement,l=n.scrollWidth||n.clientWidth||document.body.scrollWidth,t=n.scrollHeight||n.clientHeight||document.body.scrollHeight;
if(m>=l||p>=t||k&&!m&&!p)return b;m==0&&p==-t&&f==l&&h==t&&(p=0);let w=a.dc||0;b=[m,p+w,m+f,p+h-w,this.ea()]}catch(c){}return b};g.Kb=function(a){var b=a.ec;if(b){b=document.elementsFromPoint((b.left+b.right)/2,(b.top+b.bottom)/2);for(var c,d;(c=b.shift())&&!c.isSameNode(a);){let e=window.getComputedStyle(c);if(e.visibility=="visible"&&e.opacity!="0"&&!ea(e.backgroundColor)){d=!0;break}}a.J=d}};g.D=function(){let a=G?80:90;try{var b=window.top.document.title}catch(c){}b||(b=(b=document.head.querySelector('meta[property="og:title"]'))&&
b.getAttribute("content"),a=70);b&&(b=b.replace(/^\(\d+\)/,"").replace(/[ \t\r\n\u25B6]+/g," "),b=new String(b.trim()),b.src=a);return b};g.Xb=function(){if(!document.elementsFromPoint)return 0;var a=document.documentElement;let b=a.clientWidth||a.offsetWidth;a=(a.clientHeight||window.innerHeight)/4;var c=document.elementsFromPoint(0,0);let d=0,e=0,f=0;for(let k of c)if(k.offsetWidth>=b){var h=window.getComputedStyle(k);h.opacity>=.95&&(c=h.zIndex,h.position=="fixed"?(h=k.offsetHeight+k.offsetTop,
d<h&&h<a&&(d=h,e=c)):f<c&&(f=c))}e<f&&(d=0);return d};g.Tb=function(a,b,c,d,e,f,h,k,m,p,n,l,...t){this.K=a;this.X=b;if(n||=K.hostname.toLowerCase().split(".").at(-2))this.va=RegExp(`^(?:\\(\\d+\\)\\s+)?(.+?)\\s+[-|@]+\\s*${n}$`,"i"),this.Ja=`idmrs://${n}/`;if(d){this.ma=d;try{window.frameElement&&(window.frameElement.ob=d)}catch(w){}}this.nb(f);m&&(this.qa=m);e&&this.Ec(e,t);p&&(fa.idm=this,this.h=!0,this.u="__idm_id__",T("text/javascript",p));l&&(this.j(2,window,"message",this.Dc),T("text/javascript",
l));document.readyState=="loading"?this.Ka=!0:this.ha()};g.Ub=function(a){P=location.hostname.toLowerCase()+location.pathname+location.search;this.La&&this.v&&(this.v=0,this.Ma=window.setTimeout(this.ja.bind(this,!1),3E3));this.ha(!0);a&&this.nb();for(let b of new Set(V(this.A)))this.Kb(b)};g.nb=function(a){if(this.U(arguments)){var b=[21,K.href,document.referrer];a&&b.push(document.getElementsByTagName("video").length,document.getElementsByTagName("audio").length);this.g.postMessage(b)}};g.Zb=function(a){var b=
a?this.U(arguments):1;if(b>0||b<0&&this.B!=1){b=this.D();let c=this.ea(),d=this.Xb();this.g.postMessage([24,b,b&&b.src,c,d])}};g.ac=function(a,b,c,d,e){c||=this.Rb(b,d,e);d=(d=c&&this.A[c])&&this.R(d);this.g.postMessage([22,a,b,c,d])};g.Yb=function(a,b){let c,d,e=document.getElementsByTagName("a");for(let f of e)try{if(f.href==b){c=f.download||null;d=f.innerText.trim()||f.title||null;break}}catch(h){}this.g.postMessage([35,a,c,d])};g.$b=function(a,b,c,d,e,f,h,k){if(this.U(arguments)){var m=[23,a,
b,!1],p,n;var l=this.A;if(b)(l=l[b])||(m[3]=!0);else{l=k&&l[k]||h&&l[h];if(!l||l.fa)l=this.Sb(c,d,e,f,k,h);if(l){if(this.Na&&(p=r(l,this.Na)))var t=200;else if(p=l.getAttribute("operadetachedviewtitle"))t=130;m[2]=b=l.l;m[5]=l.localName;m[6]=l.src||l.data}else if(k||h)m[3]=!0;!p&&(p=this.D())&&(t=p.src,(n=this.va.exec(p))&&(p=n[1]));m[7]=p;m[8]=t}if(l)if(p=this.R(l),p!=null||document.contains(l)){if(m[4]=p,a&&this.B==1&&this.ba)try{m[9]=window.sessionStorage.getItem(this.ba)}catch(w){}}else this.P(l),
m[3]=!0;this.g.postMessage(m)}};g.Wb=function(a,b,c,d){let e=d?RegExp(d,"i"):null;d=this.mb(document,e,b);let f=document.getElementsByTagName("iframe");for(let h of f)try{let k=h.contentDocument;k&&!h.src&&O(d,this.mb(k,e,b))}catch(k){}a=[27,a,this.ma,d.length];c||(a[4]=d,a[5]=K.href,G&&(a[6]=K.href,a[7]=document.title));this.g.postMessage(a)};g.mb=function(a,b,c){let d=[],e={};var f="";let h="",k=!c,m;if(c&&(m=a.getSelection(),!m||m.isCollapsed&&!m.toString().trim()))return d;for(let n of a.getElementsByTagName("a"))if(k||
m.containsNode(n,!0))try{let l=n.href;l&&!e[l]&&b.test(l)&&(e[l]=d.push([l,2,n.download||null,n.innerText.trim()||n.title]));c&&e[l]&&(h+=n.innerText,h+="\n")}catch(l){}for(let n of a.getElementsByTagName("area"))if(k||m.containsNode(n,!0))try{let l=n.href;l&&!e[l]&&b.test(l)&&(e[l]=d.push([l,2,null,n.alt]))}catch(l){}for(let n of a.getElementsByTagName("img"))if(k||m.containsNode(n,!0))try{let l=n.src;l&&!e[l]&&b.test(l)&&(e[l]=d.push([l,3,null,`<<<=IDMTRANSMITIMGPREFIX=>>>${n.alt}`]));k&&n.onclick&&
(f+=n.onclick,f+="\n")}catch(l){}if(c){if(f=m.toString()){c=this.O(h);for(var p of this.O(f))p&&!e[p]&&b.test(p)&&!c.includes(p)&&(e[p]=d.push([p,1]))}for(let n of a.getElementsByTagName("textarea"))if(a=n.selectionStart,f=n.selectionEnd,(p=m.isCollapsed&&a<f)||m.containsNode(n,!0))try{let l=p?n.value.substring(a,f):n.value;for(let t of this.O(l))t&&!e[t]&&b.test(t)&&(e[t]=d.push([t,1]))}catch(l){}}else{for(let n of a.getElementsByTagName("iframe"))try{let l=n.src;l&&!e[l]&&b.test(l)&&(e[l]=d.push([l,
4]))}catch(l){}for(let n of a.getElementsByTagName("script"))f+=n.innerText,f+="\n";if(f)for(let n of this.O(f))n&&!e[n]&&b.test(n)&&(e[n]=d.push([n,5]))}return d};g.O=function(a){if(!this.Ha){var b="\\b\\w+://(?:[%T]*(?::[%T]*)?@)?[%H.]+\\.[%H]+(?::\\d+)?(?:/(?:(?: +(?!\\w+:))?[%T/~;])*)?(?:\\?[%Q]*)?(?:#[%T]*)?".replace(/%\w/g,function(d){return this[d]}.bind({"%H":"\\w\\- -﻿","%T":"\\w\\-.+*()$!,% -﻿","%Q":"^\\s\\[\\]{}()"}));this.Ha=RegExp(b,"gi")}let c=[];for(;b=this.Ha.exec(a);)c.push(b.shift());
return c};g.U=function(a){let b=this.v;b||(a=M(a&&a.callee?a:arguments),a.unshift(arguments.callee.caller),this.na.push(a));return b};g.rb=function(a){let b;try{b=window.top.document.getElementsByTagName("title")[0]}catch(c){}this.v=a&&b?-1:1;b&&(a=this.La,a||(a=this.La=new MutationObserver(this.ja.bind(this))),a.observe(b,{childList:!0}),this.h&&b.setAttribute("__idm_obs__",1));this.Z=new ResizeObserver(this.W.bind(this));this.V=new IntersectionObserver(this.W.bind(this),{threshold:.2});this.Ka&&
(this.Ka=!1,this.ha());for(let c,d=this.na;c=d.shift();)c.shift().apply(this,c)};g.W=function(a){if(this.g)for(let b of a)if(b.target.l)if(a=b.target,a.isConnected){let c=b.isIntersecting;if(c!=null){let d=a.J;a.J=!c;a.ec=c?b.intersectionRect:null;c&&d&&this.Hb(a)}a.G&&window.clearTimeout(a.G);a.G=window.setTimeout(this.sc.bind(this,a),200)}else this.g.postMessage([23,null,a.l,!0]),this.P(a)};g.sc=function(a){if(!this.g)return this.P(a);a.G=null;let b=document.contains(a),c;if(b){if(c=this.R(a),this.B==
1&&a.fa)if(c){let d=r(a,this.Oa);d?.href&&d.href!=a.i&&this.H(a,null,d.href)}else a.i=a.o=null,b=!1}else this.P(a);this.g.postMessage([23,null,a.l,!b,c])};g.ja=function(a){if(a)window.clearTimeout(this.Ma),this.Ma=window.setTimeout(this.ja.bind(this,!1),1E3);else{this.v<0?this.v=1:++this.v;for(let b,c=this.na;b=c.shift();)b.shift().apply(this,b)}};g.rc=function(a){var b=a.target;let c=b.localName;J(c)&&a.url&&(b=this.S(b),this.g.postMessage([25,b,c,a.url]))};g.sb=function(a){!a.repeat&&ca[a.keyCode]&&
this.g.postMessage([31,a.keyCode,a.type=="keydown"])};g.vc=function(a){this.Vb&&this.g.postMessage([28]);if(a.button==0){let b=a.view.getSelection();b?.isCollapsed&&!b.toString().trim()&&(this.C=1);this.g.postMessage([32,a.button,!0])}};g.xc=function(a){if(a.button==0){this.oa=a.clientX;this.pa=a.clientY;this.g.postMessage([32,a.button,!1]);let b=a.view.getSelection();b&&this.C&&(this.C=b.isCollapsed&&!b.toString().trim()?0:2)&&this.g.postMessage([26,a.clientX,a.clientY,this.ea()])}};g.wc=function(){this.C==
2&&(this.C=0)};g.uc=function(a){a=a.target;a.localName=="a"&&this.g.postMessage([39,a.hasAttribute("download"),a.href,a.download])};g.Cc=function(){this.g.postMessage([29])};g.Bc=function(a){a=a.target;this.g.postMessage([30,a.innerWidth,a.innerHeight])};g.tc=function(){this.C=0;this.g.postMessage([33])};g.j=function(a,b,c,d,...e){e=M(arguments);e[3]=d.bind(this);this.Ia.push(e);a<0?(b=b[c],b.addListener.apply(b,e.slice(3))):b.addEventListener.apply(b,e.slice(2))};g.tb=function(a){let b=this.Ia;for(let c=
0;c<b.length;c++){let d=b[c][0];if(a&&a!=d)continue;let e=b.splice(c--,1).pop(),f=e.splice(0,2).pop();d<0?(f=f[e.shift()],f.removeListener.apply(f,e)):f.removeEventListener.apply(f,e)}};g.nc=function(a){this.aa&&(window.clearTimeout(this.aa),this.aa=null);var b=this.fb.exec(K.pathname+K.search);b&&this.wb(b[1]);if(!a){this.la(1229212983,this.oc);var c,d;a=0;for(var e of document.getElementsByTagName("script")){if(e.src){if(b=this.N.exec(e.src))a|=1,this.I[b[1]]?d=b[1]:c=e.src}else if(b=this.cb.exec(e.text)){a|=
2;var f=b[1]&&parseInt(b[1],10);var h=b[2];var k=b[3]=="true";var m=b[4]||b[5];var p=b[7]&&parseInt(b[7],10);if(b=this.N.exec(b[6]))this.I[b[1]]?d=b[1]:c||=B+b[0]}else if(this.Wa.test(e.text)){a|=4;var n=e.outerHTML}if(a==7)break}b=this.K>=101;e=this.K>=105;(a=k?h:m)?this.ba=U(a):this.ka(window,k||!b?136:138,k?this.cc:this.qc,this.Gc.bind(this));if(d||f||h||m||p||k!=null)var l={[124]:d,[144]:c,[118]:f,[136]:k||b?h:m,[138]:m,[143]:p,[139]:k};c&&e?(d=new XMLHttpRequest,d.responseType="text",d.timeout=
1E4,d.onreadystatechange=this.Hc.bind(this,c,l,n,d),d.open("GET",c,!0),d.send()):(l&&this.g.postMessage([37,1,2,l]),n&&this.g.postMessage([34,this.D(),null,n]))}};g.wb=function(a,b,c){let d=!b;d&&(b=r(document.body,this.gb));let e=r(document.body,this.eb),f=!!e?.offsetWidth,h=!f&&b||e;h&&d&&this.H(h,a,null,"video");e&&b&&e!==b&&(d&&f?this.ib(b,e):this.ib(e,b,f));!e&&(c||=0)<10&&(this.aa=window.setTimeout(this.wb.bind(this,a,b,++c),500))};g.Hc=function(a,b,c,d){if(d.readyState==4){var e=d.response,
f=this.N.exec(a);a=this.Xa.exec(e);var h=f&&f[1],k=a&&parseInt(a[1]||a[2],10);if(k&&(!this.I[k]||!this.I[h])){a=[null,119,120,135,141,142];f=[null,this.Ya,this.Za,this.$a,this.ab,this.bb];d={[118]:k,[124]:h,[144]:d.responseURL};let m=[];h=!0;for(k=0;h&&++k<f.length;){let p=f[k];k>1&&(p=p.replace(/\$\{(\d+)\.(\d+)\}/g,(n,l,t)=>m[l][t].replaceAll("$","\\$")));try{h=m[k]=RegExp(p,"s").exec(e)}catch(n){h=null}}if(k>=3){for(e=1;e<a.length;e++)m[e]&&(d[a[e]]=m[e][0]);this.g.postMessage([37,1,1,d])}else this.K>=
110&&(d[140]=e,this.g.postMessage([37,1,4,d]))}b&&this.g.postMessage([37,1,2,b]);c&&this.g.postMessage([34,this.D(),null,c])}};g.Gc=function(a,b,c){c&&(this.ba=U(c),this.g.postMessage([37,1,2,{[b]:c}]))};function U(a){let b=0,c=6038198,d=0,e;for(e=a.length>>1;b<e;b++)c=c*31+a.charCodeAt(b)|0;for(e=a.length;b<e;b++)d=d*31+a.charCodeAt(b)|0;return c.toString(16)+d.toString(16)}g.jc=function d(b,c){b?(c&&b.shift().disconnect(),this.ia.disconnect(),this.xa.disconnect(),this.wa.clear()):(this.da(this.ua),
this.ia=new MutationObserver(this.Pb.bind(this)),this.xa=new MutationObserver(this.Ob.bind(this)),this.wa=new Set);if(c=this.Db=r(document.body,this.Eb)){if(b=this.ia,b.observe(c,{childList:!0}),this.h&&c.setAttribute("__idm_obs__","P"),!this.kb(c,!0)&&(c=r(c,this.Fb))){var e=r(c,this.ya);e?(b.observe(e,{childList:!0}),this.h&&e.setAttribute("__idm_obs__","P"),b.observe(c,{childList:!0}),this.h&&c.setAttribute("__idm_obs__","P")):(b.observe(c.parentNode,{childList:!0}),this.h&&c.parentNode.setAttribute("__idm_obs__",
"P"))}}else!b&&(c=r(document.body,this.Bb))&&(e=new MutationObserver(d.bind(this,b=[])),b.push(e),e.observe(c,{childList:!0}),this.h&&c.setAttribute("__idm_obs__","R"))};g.kb=function(b,c){let d=this.ia,e=this.ya,f=this.Ab,h=this.xa,k=this.wa,m=0;for(let p of r(b,f,[]))k.has(p)||r(p,f)||(k.add(p),h.observe(p,{childList:!0,subtree:!0}),this.h&&p.setAttribute("__idm_obs__","M"),c&&(b=r(p,e))&&(m++,d.observe(b,{childList:!0}),this.h&&b.setAttribute("__idm_obs__","P")),F(p.getElementsByTagName("video"),
this.ca.bind(this)));return m};g.Pb=function(b){let c=this.Db;for(let d of b){b=d.target.isSameNode(c);for(let e of d.addedNodes)e.nodeType==1&&this.kb(e,b)}};g.Ob=function(b){let c=this.Y,d=this.Fa;for(let e of b)for(let f of e.addedNodes)if(f.nodeType==1)if(b=f.getElementsByTagName("video"),b.length)F(b,this.ca.bind(this));else for(let h of c)if(h){b=h[0];let k=r(b,d);k&&k.contains(f)&&this.ca(b,!0)}};g.ca=function(b,c){if(!b.i){var d=r(b,this.Fa),e=d&&r(d,this.Gb);if(!e){let k=this.ra,m=this.ta,
p=N.bind(["div","span","a"]),n,l,t,w,u;for(let v=d;v&&m--&&p(v.localName);v=v.parentNode){l=v;let q;var f=v;var h=`${k}:scope:first-child:only-of-type`;for(q=0;h[q]=="<";q++);q&&(h=h.slice(q));for(f=f.closest(h);f&&q--;f=f.parentElement);if(f)break;if((t=v.previousSibling)&&t.localName=="div"){n||=v.querySelector('div[role="slider"]');(u=v.querySelectorAll(k)).length==1?f=u[0]:(w=v.nextSibling)&&(u=w.querySelectorAll("ul:scope "+k)).length==1?f=u[0]:n&&(u=t.querySelectorAll(k)).length>1&&(f=u[u.length-
1]);break}}!f&&l&&(u=r(l,this.xb,[])).length==1&&(f=u[0]);!f&&d&&(f=d.querySelector(`:scope >${k}`));f&&(f=f.href);!f&&document.getElementsByTagName("video").length==1&&(e=this.sa.exec(K.href))&&(e=e[1])}e||f?this.H(b,e,f):c||this.ka(b,0,this.Cb,this.Qb.bind(this))}};g.Qb=function(b,c,d){d&&this.H(b,d)};g.kc=function(b){!b&&(this.da(this.Aa),b=r(document.body,this.Lb))&&(D(b,this.Ba,this.fc.bind(this)),D(b,this.Da,this.ga.bind(this)),D(b,this.Mb,this.ga.bind(this)),D(document.body,this.Ib,this.ga.bind(this)))};
g.pb=function(b,c,d){!c&&document.getElementsByTagName("video").length==1&&(c=this.Ca.exec(K.href))&&(c=c[1]);this.H(b,c,d,"video",!0)};g.fc=function(b){for(let c of r(b,this.za,[]))F(r(c,this.Ga,[]),this.qb.bind(this))};g.ga=function(b){F(r(b,this.Ga,[]),this.qb.bind(this))};g.qb=function(b){if(!b.i){var c=r(b,this.Ea);c?this.pb(b,null,c):this.ka(b,0,this.Jb,this.hc.bind(this))}};g.hc=function(b,c,d){d&&this.pb(b,d)};g.mc=function(b){b||(this.da(this.Qa),(b=r(document.body,this.Sa))&&D(b,this.Ta,
this.Fc.bind(this)))};g.Fc=function(b){if(b=r(b,this.Ua)){let c=this.Ra.exec(P);c&&this.H(b,c[1])}};g.lc=function(b){if(!b){var c=r(document.body,this.Nb);c&&(b=this.D(),c=c.outerHTML,this.g.postMessage([34,b,null,c.slice(0,c.indexOf(">")+1)]))}};function T(b,c){let d=document.createElement(b.startsWith("image/")?"img":"script");d.src=`data:${b};base64,${c}`;d.onload=d.remove.bind(d);document.documentElement.appendChild(d)}function r(b,c,d){function e(l,t,w){for(;w&&t--;)w=w.parentElement;w&&(isNaN(l)||
this.push(l),this.push(w));return w}if(!c)return d;let f,h,k,m=!0,p=d||[],n=c.split(da);for(n.length==1?n.unshift(">",NaN):n.shift();b&&(f=n.shift());){c=parseInt(n.shift(),10);h=n.shift().trim();for(k=1;h[h.length-k]=="<";k++);--k&&(h=h.slice(0,-k).trim());switch(f){case "<":b=L(h?b.closest(h):b,k);m=!0;break;case ">":b=L(b.querySelector(h),k);m=!0;break;case "{":b.closest(h)&&(b=null);break;case "}":b.querySelector(h)&&(b=null);break;case "|":if(h=h.endsWith(":scope")?b.closest(h):b.querySelector(h))return L(h,
k);m=!1;break;case "&":b=e.call(p,c,k,b.querySelector(h));m=!1;break;case "*":b.querySelectorAll(h).forEach(e.bind(p,c,k));m=!1;break;case "+":h=h?h.endsWith(":scope")?b.closest(h):b.querySelector(h):b;e.call(p,c,k,h);m=!1;break;case "=":if(h=b.getAttribute(h))return h;m=!1;break;case "@":if(h=b.textContent.trim())return h;m=!1}}return p.length?p:m&&b||d}function D(b,c,d,e,f,h){if(e==null){e=r(b,c,[]);h=new MutationObserver(D.bind(null,b,c,d,e));h.observe(b,{childList:!0});this.h&&b.setAttribute("__idm_watch__",
1);this.h&&e.forEach(m=>m.setAttribute("__idm_watch__",1));for(var k of e)h.observe(k,{childList:!0});e.length&&d(e.at(-1))}else for(let m of f){for(let p of m.addedNodes)if(p.nodeType==1)if(f=r(b,c,[]).slice(e.length),(k=f.at(-1))&&p.contains(k)){O(e,f);this.h&&f.forEach(n=>n.setAttribute("__idm_watch__",1));for(let n of f)h.observe(n,{childList:!0});for(let n of k.children)d(n)}else m.target.isSameNode(e.at(-1)||b)&&d(p);for(let p of m.removedNodes)if(p.nodeType==1)for(f=0;f<e.length;f++)if(p.contains(e[f])){e.splice(f);
break}}}function L(b,c){for(;b&&c--;b=b.parentElement);return b}new Q}!0;
